### ISSUE TITLE
Incompatible version kicks for exact same config since 0.8.5

### ISSUE THREAD

**Issue by Alintya** [valheimPlus/ValheimPlus#100]
Having stamina section enabled with a fraction (like 0.5) on any setting while enforcing config kicks every remote client for incompatible version. Possibly happens for fractions in other sections as well but we are tired after debugging for the past 4 hours with countless reinstalls.

0.8.5
```
[Info   : Unity Log] Version generated with enforced mod and config hash : 0.145.6@0.8.5@C294B28C02E8AAECD0E45A51E594B277
[Info   : Unity Log] 02/24/2021 02:37:40: Peer 76561198971166346 has incompatible version, mine:0.145.6@0.8.5@C294B28C02E8AAECD0E45A51E594B277 remote 0.145.6@0.8.5@468B88EDA7051746D56301018AB5FF2C
```
0.8.6
```
[Info   : Unity Log] Version generated with enforced mod and config hash : 0.145.6@0.8.6@C294B28C02E8AAECD0E45A51E594B277
[Info   : Unity Log] 02/24/2021 02:54:18: Peer 76561198971166346 has incompatible version, mine:0.145.6@0.8.6@C294B28C02E8AAECD0E45A51E594B277 remote 0.145.6@0.8.6@468B88EDA7051746D56301018AB5FF2C
```

**Comment by Xiaminou** [comment]
same problem here, half my clients couldn't join until I disabled the version check (on both client and server).

**Comment by nxPublic** [comment]
All clients and the server need to have the proper 0.8.6 installed.

We will investigate this issue but we are very sure these issues are on your end.

**Comment by nickkeane** [comment]
@Alintya What are your client and server hash values? If you click the player.log button, or look at your server log, they should print out if you have enforcement enabled.

Hashes look like this:
0.145.6@0.8.5@BA0EA3D35653F3D32AAAF5E75DF75154

The three sections of that hash (Valheim Version, Valheim+ Version, and .cfg Hash) need to be identical for both client and server.

@nxPublic There's an issue w/ the WindowsClient .zip and .tar.gz artifacts being 0.8.5, not 0.8.6 for the 0.8.6 release. I raised the issue in #101 if you've yet to see it.

**Comment by Alintya** [comment]
> @Alintya What are your client and server hash values? If you click the player.log button, or look at your server log, they should print out if you have enforcement enabled.
> 
> Hashes look like this:
> 0.145.6@0.8.5@BA0EA3D35653F3D32AAAF5E75DF75154
> 
> The three sections of that hash (Valheim Version, Valheim+ Version, and .cfg Hash) need to be identical for both client and server.
> 
> @nxPublic There's an issue w/ the WindowsClient .zip and .tar.gz artifacts being 0.8.5, not 0.8.6 for the 0.8.6 release. I raised the issue in #101 if you've yet to see it.

Just noticed the discrepancy in the version string, updated OP

**Comment by Alintya** [comment]
Reconfirmed the issue with actual 0.8.6, config is the same (straight copy pasted from server to client)

`[Info   : Unity Log] Version generated with enforced mod and config hash : 0.145.6@0.8.6@C294B28C02E8AAECD0E45A51E594B277

[Info   : Unity Log] 02/24/2021 02:54:18: Peer 76561198971166346 has incompatible version, mine:0.145.6@0.8.6@C294B28C02E8AAECD0E45A51E594B277 remote 0.145.6@0.8.6@468B88EDA7051746D56301018AB5FF2C`

**Comment by nickkeane** [comment]
Do you get identical hashes when using the baseline configs
i.e. only [Server] enabled=true enforceConfiguration=true 
so the hashes are printed, with nothing else changed?

Try using my config on both your client and server and see if you get the same .cfg hash:
https://drive.google.com/file/d/1Tqsx66wDhDA2N9sr2hMwipz4ellhpO5X/view?usp=sharing

The correct hash for that config should be BA0EA3D35653F3D32AAAF5E75DF75154

Is your server Linux or Windows based? How are you copying files over? It could be end-of-line characters causing issues.

**Comment by Alintya** [comment]
Yes, I do
As I said, only after enabling stamina with a float value assigned (we tested 0.5 on staminaRegenDelay and 6.5 for staminaRegen) the problem emerges. Default config and enforcing=true with or without enabling other sections, that do not contain float values works just fine.
https://pastebin.com/4BU1GizJ
All windows
Considering everything was fine up until today I suppose it has nothing to do with malformed config files.

**Comment by nickkeane** [comment]
Ahhhh, of course! It's possible that the floats aren't storing an exact value and/or hashing them together is giving inconsistent results.

@nxPublic Don't hash floating point numbers, use fixed point types (like decimal) for config storage and the hashing process, and convert to float for calculations. That might fix this issue.

**Comment by nxPublic** [comment]
We are working on a system to entirely eliminate the versioning structure we have right now.

Float numbers that don't go beyond 0.000~ are never a issue.

As per 
#101 
I am closing this issue.

**Comment by Alintya** [comment]
@nxPublic Well, I am still getting different hashes for the exact same config using the exact same 0.8.6 assembly. #101 was related but this remains a different issue.

**Comment by nxPublic** [comment]
@Alintya In that case I will reopen the issue.

I am investigating it as I type this. Can't promise a fast solution at the moment as I am very busy today and the team has a slow day today.

**Comment by Alintya** [comment]
Nice, I will try to get the source working myself after crawling out of bed.

**Comment by Alintya** [comment]
@nxPublic 
Minimal steps to reproduce:

- install 0.8.6 WindowsServer package to fresh server installation

- install 0.8.6 WindowsClient package to fresh client installation

- change the following settings for both
```
[Server]
enabled=true
enforceConfiguration=true
[Stamina]
enabled=true
staminaRegenDelay=0.5
```

NOTE: I can connect locally without problems (generating the same hash)
2/2 tested remote computers generate a different hash and therefore can't connect

**Comment by nxPublic** [comment]
We have cooked up a solution for this. However we are uncertain if we will deploy it before the release of the networking wrapper.

**Comment by nxPublic** [comment]
Issue is resolved. We have successfully implemented our network wrapper in its first iteration today.

We will be releasing 0.9.0 later today containing a system to automatically synchronize the server configuration with the client on server join.

Sorry for the issues yesterday, we hope this can make up for it.

All credits for the network wrapper go to @zedle ❤️
