### ISSUE TITLE
[Bug] Client Version Hash Mismatch For Release v0.8.6

### ISSUE THREAD

**Issue by nickkeane** [valheimPlus/ValheimPlus#101]
For UnixServer.tar.gz, the version was properly updated to 0.8.6, but not WindowsClient.tar.gz, after installing latest 0.8.6 artifacts.

Server Hash: 0.145.6@0.8.6@BA0EA3D35653F3D32AAAF5E75DF75154
Client Hash: 0.145.6@0.8.5@BA0EA3D35653F3D32AAAF5E75DF75154

Client should be 0.8.6 above.

**Comment by nxPublic** [comment]
All clients and the server need to have the proper 0.8.6 installed.

We will investigate this issue but we are very sure these issues are on your end.

**Comment by sirskunkalot** [comment]
@nxPublic

https://github.com/valheimPlus/ValheimPlus/pull/99

(...sorry, could not resist :))

**Comment by nickkeane** [comment]
@nxPublic 

I installed the WindowsClient.zip and WindowsClient.tar.gz from the 0.8.6.
Their hashes both generate as 0.8.5 for me. There must be some version value in the WindowsClient.zip or .tar.gz builds that wasn't updated to 0.8.6, for the 0.8.6 release. 

Reinstalled client twice with the 0.8.6 Release artifacts.

**Comment by nickkeane** [comment]
Problem Solved! Needed to clear my web browser cache :/.

I was downloading the WindowsClient.zip for 0.8.6, but since it had the same name as before, my browser cached the 0.8.5 version.
