### ISSUE TITLE
[Bug] Disable Password Not Working

### ISSUE THREAD

**Issue by nickkeane** [valheimPlus/ValheimPlus#102]
I have

[Server]
enabled=true
disableServerPassword=true

in my config, but my server still requests a password from the Steam Browser and from the In-Game Browser, and shows the key/lock icons.

I used to have https://github.com/AlexMog/Longship installed that provided password disable functionality that worked perfectly, so that source may be helpful as a reference.

These files in particular: 
https://github.com/AlexMog/Longship/blob/master/Longship/Patches/PatchServerInfo.cs
https://github.com/AlexMog/Longship/blob/master/Longship/Managers/ConfigurationManager.cs

**Comment by nxPublic** [comment]
I will investigate this issue personally today. I am fairly certain that 0.8.6 fixed all issues related.

We do not support Longship as mod loader / additional system at the moment. We might in the future after 1.0.

**Comment by mcdangerous** [comment]
I am also having this issue while using with AMP. Settings such as enforceConfiguration=true seem to be working.

**Comment by astemus** [comment]
You need to remove the password from your server startup, the setting only removes the requirement for that command line password setting.

**Comment by Moikapy** [comment]
This still is an issue if you launch a server with Survival Servers. You can't edit the .bat file for windows preventing you from editing the password.

**Comment by atipper** [comment]
This is an issue for me on Ubuntu using version 0.9 and LGSM. I am not using Longship.
