### ISSUE TITLE
Send config file to players from server.

### ISSUE THREAD

**Issue by PS1TD** [valheimPlus/ValheimPlus#105]
Great job with the mod but I believe it can be improved.

In order to have a server without players who use the settings of this mod in order to gain an unfair advantage over others, I had to enable the setting that would enforce the configs to be the same between the client and the server using hashes. However, I believe that this solution is far from perfect as any player who wants to play on my server has to have the same configuration as the server, which means he has to download it from somewhere. Also if the server owner changes the configuration, all players need to download the updated config.

An improvement to this system would be the ability for clients to download the server configuration on server join. Can such a thing be implemented?

**Comment by nxPublic** [comment]
In our private repository we already have a working network wrapper and the next thing we will be working on is the implementation of that before anything else.

This will allow us to send the server stats to the client on join.
