### ISSUE TITLE
Linux client?

### ISSUE THREAD

**Issue by ssorgatem** [valheimPlus/ValheimPlus#106]
Will the server version work for a Linux client, or is a separate version needed?

**Comment by sirskunkalot** [comment]
Yes, current version 0.8.6/0.8.7 should work with client and server. If you could try it and share your experience here, that would be great :)

**Comment by noxdk** [comment]
I got it working by extracting the contents of UnixServer.tar.gz to the Valheim game directory and by using this custom launch option within Steam:

`DOORSTOP_ENABLE=TRUE DOORSTOP_INVOKE_DLL_PATH=BepInEx/core/BepInEx.Preloader.dll LD_PRELOAD=doorstop_libs/libdoorstop_x64.so %command%`

**Comment by sirskunkalot** [comment]
Great, thanks for reporting this.

Is it not working if DOORSTOP_ENABLE etc. are in the run script?

**Comment by noxdk** [comment]
Yes, it also works from the run script. I just had to add the variables in the custom launch option in order to join dedicated servers directly from the Steam server list.

**Comment by sirskunkalot** [comment]
Thanks again, that is some valuable information :)

**Comment by natis1** [comment]
If you install BepInExPack Valheim 5.4.602 or newer you can drag and drop in the config and plugin folders from the windows client valheim plus and it will work without any command line trickery by just launching `./start_game_bepinex.sh %command%` https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/
