### ISSUE TITLE
[Feature Request] Display cart/boats on map

### ISSUE THREAD

**Issue by maci0** [valheimPlus/ValheimPlus#107]
Would be good if carts and boats would be visible on the map so you don't misplaced them :D

**Comment by Solence1** [comment]
to be fair, there is a marker system in the game

**Comment by Algorithman** [comment]
I made a PR for automatic portal marking, i think it also could be used for ships/carts. Difficulty is to get notified when the ship moves (not players moving the ship, i'm thinking of the waves).
With a minimum delay for updates i think i could make it work.

@Solence1  As for the marker system, if it would be shared that would be an argument. For now, players from different time zones can screw it up quite easily, even if they mark the position.

**Comment by astranberg** [comment]
@Algorithman link please.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Map as "Display carts and boats on the map".
