### ISSUE TITLE
[Feature Request] Config Profiles

### ISSUE THREAD

**Issue by schtauffen** [valheimPlus/ValheimPlus#110]
I have a dedicated server that I play on which forces a config but would like my single player games to have a different config.

It would be great if V+ supported profiles somehow so I don't have to rename my config files all the time.

Thanks for the great mod!

**Comment by astranberg** [comment]
Consider merge with #116.

**Comment by weshaw** [comment]
> I have a dedicated server that I play on which forces a config but would like my single player games to have a different config.
> 
> It would be great if V+ supported profiles somehow so I don't have to rename my config files all the time.
> 
> Thanks for the great mod!

I create a thing that does this if you want to check it out.
[ValheimPlus-ConfigSwitcher](https://github.com/weshaw/ValheimPlus-ConfigSwitcher)
