### ISSUE TITLE
[Feature Request] auto equip shield

### ISSUE THREAD

**Issue by Lovis83854** [valheimPlus/ValheimPlus#113]
look for an option to have it auto equip the shield when i switch to a 1-handed weapon or remember the combination i used last like when i get the hotkey to equip my spear or axe it will also equip the shield i have.

or the ability to add both item to one hotkey

**Comment by pwilson90** [comment]
FWIW in the base game if you put sheathe your stuff with 'r', hitting 'r' again pulls out the same equipment.

Not to take away from the request, a hotkey for both would be nice.

**Comment by Lovis83854** [comment]
> 
> 
> FWIW in the base game if you put sheathe your stuff with 'r', hitting 'r' again pulls out the same equipment.
> 
> Not to take away from the request, a hotkey for both would be nice.
