### ISSUE TITLE
[Documentation] Server side only settings

### ISSUE THREAD

**Issue by Toucan-Sam** [valheimPlus/ValheimPlus#114]
I'd like to see some documentation around what sections of settings qualify as 'server side only'. V+ is an excellent mod, but I want to keep my dedicated server as accessible as possible by not asking people to install overheads before they can play.

Something that highlights which feature sets can be enabled and fully functional without requiring client side modification would be amazing.

I did some basic searches in the open/closed issues but didn't see anything. Feel free to close if this is solved or referenced elsewhere.

**Comment by nxPublic** [comment]
We are working on a documentation on http://valheim.plus and we will make sure to mention client side and server sided features.

**Comment by OldSaltGorg** [comment]
Hey, has there been any progress on this? Still find it difficult which settings are Server-only and which ones require both client and server to have the mod installed. Clarity on this would be a huge help, thanks!
