### ISSUE TITLE
[Feature Request] Deconstruct Items

### ISSUE THREAD

**Issue by All-Schuck-Up** [valheimPlus/ValheimPlus#115]
Not sure if this is easily done but I would be a nice if the forge could act as a place to select old weapons, tools and armor to break back down into raw resources.

**Comment by maci0** [comment]
naturally it shouldnt give you back 100% of your resources. maybe 50%

**Comment by radmint** [comment]
This feature and the option to have @maci0's resource returned percentage will be included in the next release. Thank you for the suggestion @All-Schuck-Up !

**Comment by All-Schuck-Up** [comment]
Epic! Is there a feature branch public, I'd love to check out the code as I am interested in developing mods? @radmint

**Comment by gnouts** [comment]
Hi, what's this feature name ? 
I tried searching for 'recycle' or 'deconstruct' but nothing showed up, in the readme, the changelog or the cfg file.
