### ISSUE TITLE
[Feature Request] download server config to client

### ISSUE THREAD

**Issue by astranberg** [valheimPlus/ValheimPlus#116]
Updating V+ and changing it's config can be a bit of a pain with multiple people playing on my server, particularly some who are not computer savvy.

It would be a nice feature if the server could force its configuration on the clients.

Thanks for all who work on this project!

**Comment by maci0** [comment]
Agreed. Generally the config of whoever hosts should apply to all clients.

**Comment by nxPublic** [comment]
![image](https://user-images.githubusercontent.com/39051287/109102665-34778f00-76de-11eb-8c11-5d62b5524aff.png)

Is in development. Release most likely later today.
