### ISSUE TITLE
Stock exploration radius

### ISSUE THREAD

**Issue by MagZu** [valheimPlus/ValheimPlus#117]
hey.

I tested your mod and i noticed that even if [map] is set to disabled the exploration radius is still bigger than stock.
Also im wondering if it would be possible to add back stock radius, i tried setting the exploreradius pretty low even 0 but it were still way bigger than stock, i like to use the fog to figure out where i havent been so i like the stock radius.

**Comment by radmint** [comment]
@MagZu I cannot find a way that this would be possible. [You can see here](https://github.com/valheimPlus/ValheimPlus/blob/00cc94a4745698a8ea67be3909287e2ff8a77134/ValheimPlus/SharedMapSystem.cs#L35) that if the Map is not enabled, we kick out of the method immediately. Can you provide a screenshot of the map explore radius without the mod and with?

**Comment by radmint** [comment]
I'm going to close this as unreproducible but please reopen or re-file with screenshots if you are still having this issue
