### ISSUE TITLE
[Feature Request] Mob Spawn visual representation

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#118]
When building a base it is important to be able to block enemies from spawning inside your walls, however it can often be hard to figure out where they are allowed to spawn.
I would like to have a feature that visual represents where enemies are allowed to spawn. (like the Light Level Overlay mod for Minecraft).

**Comment by nxPublic** [comment]
Workbenches prevent spawning of enemies in the radius, the modified radius size is respected from Valheim Plus.
