### ISSUE TITLE
[Typo] ValheimPlus/Fireplace.cs - Sconces lose their resin stack even if the property was set to "True".

### ISSUE THREAD

**Issue by TeppersBen** [valheimPlus/ValheimPlus#120]
Line 18 states the following:
__instance.GetHoverText().Contains("Scounce")

while the hovertext in game is:
"Sconce" 

Direct link to file: https://github.com/valheimPlus/ValheimPlus/blob/master/ValheimPlus/Fireplace.cs#18

**Comment by radmint** [comment]
This will be fixed in the next release along with this bug: https://github.com/valheimPlus/ValheimPlus/issues/97
