### ISSUE TITLE
[Feature Request] ValheimPlus version in config file

### ISSUE THREAD

**Issue by rr222cy** [valheimPlus/ValheimPlus#124]
Hi!
Would it be possible to for example add

```
[Version]
currentVersion="0.9.0"
```

to the configuration file for both client and server? Thus making it easier for users to spot which version they are on, and especially if using multiple config files for different servers (some admins update their servers faster than others).

**Comment by Hydeo** [comment]
I was coming to ask the same thing, afaik you cannot know what is the version installed on the server.

**Comment by radmint** [comment]
Thanks for the suggestion @rr222cy, this will be in the next release as a comment at the top of the .cfg file
; Valheim Plus v0.9.1
