### ISSUE TITLE
[Bug] Version mismatch between WindowsClient and UnixServer libraries on 0.9

### ISSUE THREAD

**Issue by AdamOlczak** [valheimPlus/ValheimPlus#125]
When I did put the version 0.9 on server using UnixServer files, and 0.9 on my computer using WindowsClient libraries (both from .zip files) I couldn't connect due to version mismatch (remote 0.9 (that is windows client) mine 0.9.0 (unix server) )

Image of the log from server: 
![image](https://user-images.githubusercontent.com/4672731/109146588-4dc31e80-7764-11eb-8028-a678269db713.png)

I managed to fix that for my Windows Clients (by using dlls from UnixServer), but that may be an issue for others that don't know that their server is running on Unix.

**Comment by busiderbaer** [comment]
You need to redownload the server / client files, you seem to have the same issue I had earlier. See my discord post here: https://discord.com/channels/810550285008633866/810550325864824912/814439361965588501
