### ISSUE TITLE
ValheimPlus Docker

### ISSUE THREAD

**Issue by ich777** [valheimPlus/ValheimPlus#128]
Hi,
I've created a Docker container for Valheim on Unraid and a few users requested the ValheimPlus mod to be integrated, what I've also done now: [Click](https://github.com/ich777/docker-steamcmd-server/tree/valheim) (it's the 'valheim' branch in the Repo)
The contianer is pretty easy to install with only a few Variables needed and it will download everything automatically (also added a Backup function for the world because the world destroy bug is not fixed yet I think).

Is it possible to get a information from somewhere if something trivial changes like from 0.8.0 to 0.8.5, this update breaks the complete Docker structure and it wasn't working but I've released a quick fix and now it is back up and running again.

I've also seen that the Github url changed from nxPublic/ValheimPlus to ValheimPlusValheimPlus but the old Repo is forwarded to the new and I don't want to push another update of the container because of the world destray bug.

Regards

**Comment by radmint** [comment]
@ich777 please see our Discord for any release-notes and notifications.

**Comment by gOOvER** [comment]
@ich777 The Name of the startscript changed:)

**Comment by ich777** [comment]
@gOOvER yes I know, already implementd this.

It's a little difficult for me since I habe no Discord and don't want to be on Discord.
But I will stick with the release notes.
