### ISSUE TITLE
[Feature Request] Search Bar

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#129]
I would like to have a search option to quickly filter out what items are shown, in the forge and workbench, but also in the chests. This would go well with the option for larger inventories (https://github.com/valheimPlus/ValheimPlus/pull/126).
As inventories get bigger it becomes increasingly harder to find the items you're looking for.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Hud as "Search bars".
