### ISSUE TITLE
V+ complains about newer version since 0.9.0

### ISSUE THREAD

**Issue by Algorithman** [valheimPlus/ValheimPlus#131]
Fix: either compare remoteversion > localversion or rename the 0.9 version to 0.9.0 (as in the plugin)
Thx

**Comment by nxPublic** [comment]
This is already long resolved. Just redownload the packages, I silently fixed that.

**Comment by Algorithman** [comment]
if (ValheimPlusPlugin.newestVersion != ValheimPlusPlugin.version)
            {
                return true;
            }

Not in the source though
