### ISSUE TITLE
[Feature Request] Admin character check

### ISSUE THREAD

**Issue by Skrumpy** [valheimPlus/ValheimPlus#132]
Create an admin command that allows server admins to peak at character skill levels and inventory items. This would help to determine "cheaters" on servers who want to investigate claims. This could help server admins quite a bit until SSC and other anti-cheat mechanisms are employed.

EX:

`skillcheck <playername>`

 would return;

     Playername's skills;
         Wood cutting = 100
         Sneak = 100'

Similarly 

'itemcheck <playername>' 

would list all "equipped" items

     Playername's equipped items;
         Meningjord'

Finally.

'inventorycheck <playername>' 

would list all non-equipped items in the players current inventory and hotbar.

**Comment by nxPublic** [comment]
We are working on a more sophisticated and detailed approach. We will keep you updated.
