### ISSUE TITLE
[Documentation] Confusion about run_bepinex.sh in Unix install instructions

### ISSUE THREAD

**Issue by networkException** [valheimPlus/ValheimPlus#133]
The specified file in [here](https://github.com/valheimPlus/ValheimPlus#server-unix) does not exist after extracting [UnixServer.zip@0.9](https://github.com/valheimPlus/ValheimPlus/releases/download/0.9/UnixServer.zip)

**Comment by yobson1** [comment]
Should say start_server_bepinex.sh
