### ISSUE TITLE
Downloaded Windowsclient - No Functions are working

### ISSUE THREAD

**Issue by itzWebby1** [valheimPlus/ValheimPlus#135]
I recently downloaded and I believe I followed all instructions. No functions of the mod are working for me currently.

[AdvancedBuildingMode]
; https://docs.unity3d.com/ScriptReference/KeyCode.html <- a list of keycodes

; Change false to true to enable this section, if you set this to false the mode will not be accesible
enabled=true

; Enter the advanced building mode with this key when building
enterAdvancedBuildingMode=F1

; Exit the advanced building mode with this key when building
exitAdvancedBuildingMode=F2

[AdvancedEditingMode]

; Change false to true to enable this section, if you set this to false the mode will not be accesible
enabled=true

; https://docs.unity3d.com/ScriptReference/KeyCode.html <- a list of keycodes

; Enter the advanced editing mode with this key
enterAdvancedEditingMode=Keypad

; Reset the object to its original position and rotation
resetAdvancedEditingMode=F7

; Exit the advanced editing mode with this key and reset the object
abortAndExitAdvancedEditingMode=F8

; Confirm the placement of the object and place it
confirmPlacementOfAdvancedEditingMode=KeypadEnter

[Beehive]

; Change false to true to enable this section
enabled=true

; configure the speed at which the bees produce honey in seconds, 1200 seconds are 24 ingame hours
honeyProductionSpeed=1200

; configure the maximum amount of honey in beehives
maximumHoneyPerBeehive=6

[Building]

; Change false to true to enable this section
enabled=true

; Remove some of the Invalid placement messages, most notably provides the ability to place objects into other objects
noInvalidPlacementRestriction=true

; Removes the weather damage from rain
noWeatherDamage=true

; The maximum range that you can place build objects at
maximumPlacementDistance=5

[Items]

; Change false to true to enable this section
enabled=true

; Enables you to teleport with ores and other usually restricted objects
noTeleportPrevention=false

; Increase or reduce item weight by % percent. The value -50 will reduce item weight of every object by 50%.
baseItemWeightReduction=0

; Increase the size of all item stacks by %. The value 50 would set a usual item stack of 100 to be 150.
itemStackMultiplier=0

[Fermenter]

; Change false to true to enable this section
enabled=false

; configure the time that the fermenter takes to produce its product, 2400 seconds are 48 ingame hours
fermenterDuration=2400

; configure the total amount of produced items from a fermenter
fermenterItemsProduced=6

[Fireplace]

; If changed to enabled all fireplaces do not need to be refilled.
enabled=true

; If you enable this option only placed torches do not need to be refilled.
onlyTorches=true

[Food]

; Change false to true to enable this section
enabled=false

; Increase or reduce the time that food lasts by %. The value 50 would cause food to run out 50% slower.
foodDurationMultiplier=0

[Furnace]

; Change false to true to enable this section
enabled=false

; Maximum amount of ore in a furnace
maximumOre=10

; Maximum amount of coal in a furnace
maximumCoal=20

; The total amount of coal used to produce a single smelted ingot.
coalUsedPerProduct=2

; The time it takes for the furnace to produce a single ingot in seconds.
productionSpeed=30

[Game]

; Change false to true to enable this section
enabled=false

; The games damage multiplier per person nearby in difficultyScaleRange(m) radius.
gameDifficultyDamageScale=0.4

; The games health multiplier per person nearby in difficultyScaleRange(m) radius.
gameDifficultyHealthScale=0.4 

; Adds additional players to the difficulty calculation in multiplayer unrelated to the actual amount
extraPlayerCountNearby=0

; Sets the nearby player count always to this value + extraPlayerCountNearby
setFixedPlayerCountTo=0

; The range in meters at which other players count towards nearby players for the difficulty scale
difficultyScaleRange=200

[Hotkeys]
; https://docs.unity3d.com/ScriptReference/KeyCode.html <- a list of keycodes

; Change false to true to enable this section
enabled=false

; Roll forwards on key pressed
rollForwards=F9

; Roll backwards on key pressed
rollBackwards=F10

[Hud]

; Change false to true to enable this section
enabled=false

; Shows the required amount of items AND the amount of items in your inventory in build mode and while crafting.
showRequiredItems=false

; Shows small notifications about all skill experienced gained in the top left corner.
experienceGainedNotifications=false

[Kiln]

; Change false to true to enable this section
enabled=false

; Maximum amount of wood in a Kiln
maximumWood=20

; The time it takes for the Kiln to produce a single piece of coal in seconds.
productionSpeed=30

[Map]

; Change false to true to enable this section
enabled=true

; With this enabled you will receive the same exploration progression as other players on the server
shareMapProgression=true

; The radius of the map that you explore when moving
exploreRadius=100

; Automatically turn on the Map option to share your position when joining or starting a game
playerPositionPublicOnJoin=false

; Prevents you and other people on the server to turn off their map sharing option
preventPlayerFromTurningOffPublicPosition=true

; Remove the Map marker of your death when you have picked up your tombstone items
removeDeathPinOnTombstoneEmpty=true

[Player]

; Change false to true to enable this section
enabled=false

; The base amount of carry weight of your character
baseMaximumWeight=300

; Increase the buff you receive to your carry weight from Megingjord's girdle
baseMegingjordBuff=150

; Increase auto pickup range of all items
baseAutoPickUpRange=2

; Disable all types of camera shake
disableCameraShake=false

; The base unarmed damage multiplied by your skill level
baseUnarmedDamage=10

[Server]

; Change false to true to enable this section
enabled=false

; Modify the amount of players on your Server
maxPlayers=10

; Removes the requirement to have a server password
disableServerPassword=false

; This setting adds a version control check to verifiy that the server and yourself have the same configuration file installed.
enforceConfiguration=false

; This settings add a version control check to make sure that people that try to join your game or the server you try to join has V+ installed
enforceMod=false

; The total amount of data that the server and client can send per second in kilobyte
dataRate=60

; The interval in seconds that the game auto saves at (client only)
autoSaveInterval=1200

[Stamina]

; Change false to true to enable this section
enabled=false

; Changes the flat amount of stamina cost of using the dodge roll
dodgeStaminaUsage=10

; Changes the stamina drain of being overweight
encumberedStaminaDrain=10

; Changes the stamina cost of jumping
jumpStaminaDrain=10

; Changes the stamina cost of running
runStaminaDrain=10

; Changes the stamina drain by sneaking
sneakStaminaDrain=10

; Changes the total amount of stamina recovered per second
staminaRegen=5

; Changes the delay until stamina regeneration sets in
staminaRegenDelay=1

; Changes the stamina drain of swimming
swimStaminaDrain=5

[StaminaUsage]
; Change false to true to enable this section
enabled=false
; Each of these values reduces the stamina drain by %. The value 50 would result in 50% less stamina cost.
axes=0
bows=0
clubs=0
knives=0
pickaxes=0
polearms=0
spears=0
swords=0
unarmed=0
hammer=0
hoe=0

[Workbench]
; Change false to true to enable this section
enabled=false

; Set the workbench radius in meters
workbenchRange=20

; Disables the roof and exposure requirement to use a workbench
disableRoofCheck=false

[Time]

; Change false to true to enable this section
enabled=false

; Total amount of time one complete day and night circle takes to complete
totalDayTimeInSeconds=1200

; Increase the speed at which time passes at night by %. The value 50 would result in a 50% reduced amount of night time.
nightTimeSpeedMultiplier=0

[Ward]

; Change false to true to enable this section
enabled=false

; The range of wards by meters
wardRange=20

[StructuralIntegrity]

; Change false to true to enable this section
enabled=false

; Disables the entire structural integrity system and allows for placement in free air, does not prevent building damage.
disableStructuralIntegrity=false

; Each of these values reduce the loss of structural integrity by % less. The value 100 would result in disabled structural integrity and allow placement in free air.
wood=0
stone=0
iron=0
hardWood=0

[Experience]

; Change false to true to enable this section
enabled=false

; Each of these values represent the increase to experience gained by % increased. The value 50 would result in 50% increased experience gained for the respective skill by name.
swords=0
knives=0
clubs=0
polearms=0
spears=0
blocking=0
axes=0
bows=0
fireMagic=0
frostMagic=0
unarmed=0
pickaxes=0
woodCutting=0
jump=0
sneak=0
run=0
swim=0

[Camera]

; Change false to true to enable this section
enabled=false

; The maximum zoom distance to your character
cameraMaximumZoomDistance=6

; The maximum zoom distance to your character when in a boat
cameraBoatMaximumZoomDistance=6

; The game camera FOV
cameraFOV=65

[Wagon]

; Change false to true to enable this section
enabled=true

; Change the base vagon physical mass of the vagon object
wagonBaseMass=20

; This value changes the game physical weight of Vagons by +/- more/less from item weight inside. The value 50 would increase the weight by 50% more. The value -100 would remove the entire extra weight.
wagonExtraMassFromItems=-100

**Comment by JF10R** [comment]
Make sure your `valheim_plus.cfg` file is located in the following folder: `[Valheim install folder]\BepInEx\config`.
If it's the case and it is still not working, (and you are trying to play on a local world):

Could you upload your latest `Player.log` file, which should be located in this folder:
**Windows**
 `C:\users\%username%\AppData\LocalLow\IronGate\Valheim`
 
 **Linux**
 `­~/.config/unity3d/IronGate/Valheim`
 
 This log should include information about ValheimPlus or BepInEx trying to hook into the Valheim process, and thus errors related to it.
 
 If we cannot find any mention of ValheimPlus or BepInEx in it, it means you should try to reinstall ValheimPlus on your client.
 
 ----
 
If you are playing on a dedicated server that is not hosted locally, your client installation could be working just fine, but the server does not have the mod installed.

**Comment by radmint** [comment]
@itzWebby1 please try @JF10R's suggestions and close if this resolved your issue.
