### ISSUE TITLE
[Request] Please add ValheimPlus to thunderstore.io mod repository

### ISSUE THREAD

**Issue by jordanbarnes94** [valheimPlus/ValheimPlus#138]
https://valheim.thunderstore.io/

I want to manage ValheimPlus through r2modman, is it possible to upload the mod to this site?

**Comment by nxPublic** [comment]
We are in contact with them. We will do so soon.

**Comment by jordanbarnes94** [comment]
That's really great to hear! I have had such a big headache trying to get r2modman to load ValheimPlus. Even after I figured out ManifestV2 it would not play nice with the manager.

**Comment by JourneyOver** [comment]
I've honestly had no issues myself with V+ and having r2modman load it, just gotta know how to set it up correctly!

but hopefully once NX gets it on thunderstore, things will be slightly easier for most folks.

(kinda wish all mods for valheim would end up on there instead of nexus tbh)

**Comment by ouvoun** [comment]
@JourneyOver What's the process you've used to install using r2modman? I'd really love to use it and the timeline for official support is unclear.

**Comment by ebkr** [comment]
> @JourneyOver What's the process you've used to install using r2modman? I'd really love to use it and the timeline for official support is unclear.

https://github.com/ebkr/r2modmanPlus/wiki/Installing-mods-locally#developers
Basically all of these files should belong in the root of a zip file:
- icon.png
- manifest.json (according to the link above)
- ValheimPlus plugins folder

In r2modman go to Settings -> Import local mod -> Select zip

**Comment by alrick** [comment]
Any news about the r2modman and Thunderstore integration ?

**Comment by Daimyo21** [comment]
Would it be acceptable if there was a community managed Valheim+ version on r2modman/Thunderstore? As a way to contribute in assisting with project and getting the mod to less technical individuals/friends?

**Comment by spannerman79** [comment]
If someone can supply an `icon.png` I can create the `manifest.json`, zip structure excluding `ValheimPlus.dll` (for obvious reasons) in a zip where you can add the dll yourselves, update the version number in the json and to give that zip to those that are less technically minded.

**Comment by nxPublic** [comment]
The next 0.9.6 will be uploaded to thunderstore.
