### ISSUE TITLE
[Feature Request] Control the Frequency of Random Events

### ISSUE THREAD

**Issue by MiR4i** [valheimPlus/ValheimPlus#143]
In addition to the ability to adjust the difficulty scaling under the [Game] section, I'd love to also be able to control the frequency at which the random events occur, so that the environment feels either a bit more dangerous, or a little less hostile.  Depending on the events that are available in each biome, it may be worth breaking this down into a biome-specific adjustment.

For example:
```
[Events]

; Adjust the frequency at which random events occur, specific to each biome.
; Examples: 100 is a 100% increase (double) / -50 is a 50% decrease (half) / -100 is a 100% decrease (no events) / 0 = game default
Meadows=50
BlackForest=50
Swamp=-20
Mountain=25
Plains=25
Ashlands=0
Mistlands=0
```

**Comment by Daimyo21** [comment]
Other parameters that would complement this:

-disable troll raids
-min/max enemy and wave numbers
-Distance from which enemy spawn near base
-duration of raid events. 
-can raid events occur away from a base?

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Monsters as "Raid Settings".

**Comment by Andrey059918** [comment]
Small addition to request: ability to change raids target from player's camp to player
