### ISSUE TITLE
[Feature request] Additional Map Icons

### ISSUE THREAD

**Issue by finalsolarflare** [valheimPlus/ValheimPlus#147]
There are currently 5 different map icons which can be added - 🔥 fire, 🏠 house, ⬆️ ?, ⚪ circle and 🔮 portal.

Is it possible to add more icons? Examples like these emojis below.

🍄 Mushroom
🫐 Berry
🐗 Boar
⚓ Ship
⭐ Spawner
⛏️ Ore
🛖 Abandoned Building
🪦 Burial Chamber /Crypt

**Comment by zedle** [comment]
@Mixone-FinallyHere This may be cool with what we're working on - but we need someone to design the graphics @nxPublic 

The major issue is we will no longer support vanilla clients with changes like these.

**Comment by nxPublic** [comment]
We are working on a great solution on this.

**Comment by nxPublic** [comment]
![image](https://user-images.githubusercontent.com/39051287/111867739-2a3e5e80-8933-11eb-8453-17013b191027.png)
Still in development.

**Comment by mdcohen** [comment]
I had to block you because you are annoying: Congratulations.
