### ISSUE TITLE
Is the nightTimeSpeedMultiplier parameter not working?

### ISSUE THREAD

**Issue by muro1214** [valheimPlus/ValheimPlus#154]
I set the nightTimeSpeedMultiplier parameter as follows, but the night time does not seem to be accelerating.

~~~
; Total amount of time one complete day and night circle takes to complete
totalDayTimeInSeconds=1200

; Increase the speed at which time passes at night by %. The value 50 would result in a 50% reduced amount of night time.
nightTimeSpeedMultiplier=98
~~~

Maybe, the default case is...
* total day and night time = 1200 sec
* day time = 600 sec
* night time = 600 sec

nightTimeSpeedMultiplier=98 case is...
* total day and night time = 1200 sec
* day time = 600 + 600 x 0.98 = 1188 sec
* night time = 600 x ( 1- 0.98) = 12 sec

But it stayed night for at least five more minutes.

[Envaironment]
* Game version = 0.146.11
* V+ version = 0.9

**Comment by JF10R** [comment]
Although it doesn't fix your issue, I would like to clarify the default values:
Day time is 21 minutes.
Night time is 9 minutes.

Source: https://valheim.fandom.com/wiki/Day_and_Night_Cycle

**Comment by muro1214** [comment]
@JF10R Thank you for the information on default values!

**Comment by xiaodoudou** [comment]
Base on the code, it seems it triggers after the **Awake** event.
Which could means it should trigger from my understanding after a first cycle?

Base on your configuration totalDayTimeInSeconds 1200s => 20 minutes
Base on my assumption the default value daytime is 55% and night time is 45% and we have a hook that triggers every time the time is updated on the server-side.

This means the night will be multiplied on each server tick for the updated time; in your case, you will make each tick going 98% faster. What it does that it bumps the delta of time between the previous and current tick and multiplies it by 98% not on his global aspect as the server tick will always occur on the same tick aspect.

So you wish that your nighttime to be 12 seconds, but it will take more time as it does that on tick aspects.

More tests need to be done, but I would suggest you go around 294 as a multiplier; without knowing what is the tick rate of that event the math will be a bit random to give you. My logic is if 98 takes ~5min; 130 should give you ~2.5min; 294 should give less than a minute.

Will give a try on my side to help you.

**Comment by xiaodoudou** [comment]
From my point of view, to simplify the logic, to have more linear time calculation.
At the moment we do, time spent + time spent * multiplier

The default value should be 1.0 and we should act on the tick without adding it again.

The code is:
```   
addToTime((long)Configuration.Current.Time.nightTimeSpeedMultiplier, Time.deltaTime); 
[...]
double num = ZNet.instance.GetTimeSeconds();
num += (double)deltaTime *  (((double)deltaTime / 100) * amount);
ZNet.instance.SetNetTime(num);
```
We should go for something like:
```   
addToTime((long)Configuration.Current.Time.nightTimeSpeedMultiplier, Time.deltaTime); 
[...]
double num = ZNet.instance.GetTimeSeconds();
num += (double)deltaTime *  amount;
ZNet.instance.SetNetTime(num);
```

Then if we switch the value to 2.0 it means the time goes 2 times faster during the night.

**Comment by muro1214** [comment]
The source code for the `addToTime` function in V+ 0.8.5 was as follows.

~~~C#
double num = ZNet.instance.GetTimeSeconds();
 num += (double)deltaTime * amount;
ZNet.instance.SetNetTime(num);
~~~

In this case, when the nightTimeSpeedMultiplier parameter was set to 50, the night time was approximately 10 seconds.

**Comment by xiaodoudou** [comment]
Do you know how much the average deltaTime is every tick of that Hook? Every 1s, 5s?

**Comment by muro1214** [comment]
I'm sorry. I don't know.

**Comment by xiaodoudou** [comment]
After a bit of debugging, here the result:

- the deltaTime is 0.02; this means it ticks every 200ms.
- the totalDayTimeInSeconds is applied on server launch.

**Comment by xiaodoudou** [comment]
If we take @muro1214 setting which is the nightTimeSpeedMultiplier=98 

The result will be:

- Every day tick remain to 0.02s
- Every night tick will be 0,000392s + 0.02s =0.0200392s 

It demonstrate the new logic for 98% doesn't make it almost 2 times faster.
The math should be: `(double)deltaTime *  amount;` as it was before as automatically the tick is added anyway.

Hope that helps,

**Comment by radmint** [comment]
This fix by @xiaodoudou  has been merged and will be tested and in the next release. I'm going to close this bug and please open another one if the issue has not been fixed.
