### ISSUE TITLE
Possible to re-add enforceConfiguration for server settings only?

### ISSUE THREAD

**Issue by Meathoook** [valheimPlus/ValheimPlus#155]
With the latest version you removed the enforceConfiguration setting. You don't really need to install the Valheim Plus Client if you only want to edit server settings like changeing maximum slots or to remove the server password.

Is there a chance to re-add it or rename it to something that only works if you change server settings?

**Comment by razerrazer** [comment]
I also want this feature to be-re added.

**Comment by Algorithman** [comment]
I'm working on a config revamp.
Server side settings are synced to the clients, but other stuff (like Camera or AdvancedBuildingMode) can be set per client.
Also server settings can be changed in the console.

**Comment by Meathoook** [comment]
> Also server settings can be changed in the console.

I guess this only works with Valheim Plus installed on the server?

How can you change server settings, like slots, from the console?
Do you only write the command that is in the config-file?

Is there a requirement to change them?
Like do you need to be admin or have the Valheim Plus client?

**Comment by Algorithman** [comment]
For client only values it's just setting the value in memory (written to config on shutdown)
For server values, it's a rpc call to the server which in turn starts another rpc on each client.
Depending on what the actual value does, it should be active immediately.
For inventory, there are probably side-effects (when lowering the value at least), but that would also occur if you set if to 40 and then restart the server with 20.
To make it perfect, one would need to implement a proper INotifypropertyChanged system. But i don't know if that works out with unity.
