### ISSUE TITLE
Chests not accessible after installing of mod

### ISSUE THREAD

**Issue by pieterhouwen** [valheimPlus/ValheimPlus#156]
I cannot access chests anymore after installing this mod. How can I fix this?
I also cannot open doors anymore, it just says "Access Denied"

**Comment by radmint** [comment]
@pieterhouwen please share mod version, OS version, and .cfg

**Comment by pieterhouwen** [comment]
@radmint Turns out I was being trolled by my fellow players. They placed a ward without informing the sysadmin.... Good times
