### ISSUE TITLE
[Feature Request] Any chance we could get a loot/gather multiplier added

### ISSUE THREAD

**Issue by gitmitzu** [valheimPlus/ValheimPlus#158]
There is already an existing mod that does this but there is no option to enforce configuration on clients,

Thanks

**Comment by acidrs03** [comment]
> There is already an existing mod that does this but there is no option to enforce configuration on clients,
> 
> Thanks

This would be a great addition. Being able to change the gather rate percentage would add a nice feature to the mod.

**Comment by radmint** [comment]
This PR addresses this: https://github.com/valheimPlus/ValheimPlus/pull/175

**Comment by nxPublic** [comment]
Added with custom solution in 0.9.3

```ini
[Gathering]

; Change false to true to enable this section
enabled=false

; Each of these values increase or reduce the dropped items from destroyed objects with tools (Stones, Trees, Resource nodes, etc.) by %
; The value 50 will increase the dropped wood from trees from 10 to 15. The value -50 will reduce the amount of dropped wood from 10 to 5.
wood=0
stone=0
fineWood=0
coreWood=0
elderBark=0
ironScrap=0
tinOre=0
copperOre=0
silverOre=0
chitin=0
```
