### ISSUE TITLE
Feature request: Bigger bags

### ISSUE THREAD

**Issue by broizter** [valheimPlus/ValheimPlus#16]
One of the biggest problem with Valheim is the limited amount of items you can fit inside your bag. I guess this one might be a bit difficult to implement since it would require an UI change in-game. Another way to tackle this problem would be to give an option to increase stack sizes of items.

**Comment by GaelicGamer** [comment]
I found a lot of the methods around this and will probably tinker with it tonight, just as a FYI

**Comment by GaelicGamer** [comment]
Yeah, I got this working with save/load, just need to test it more locally with deaths and other inventory transfer things to make sure it doesn't lose items or similar in those instances.

**Comment by GaelicGamer** [comment]
This is without an update to the UI graphics though, so the new slots look a little funny, but they work, so meh.

**Comment by Mixone-FinallyHere** [comment]
This is addressed in upcoming release, to be closed
