### ISSUE TITLE
Automatic Installer / Updater

### ISSUE THREAD

**Issue by Witteborn** [valheimPlus/ValheimPlus#163]
I thought it would be really useful to have an automatic install/update system for this mod.

Both the game and the mod get quite a lot of updates that result in having to reinstall the latest version.
I don't intend to promote my own project [ValheimPlusInstaller](https://github.com/Witteborn/ValheimPlusInstaller)

Rather, I would like to discuss whether the functionality is desired by the maintainers/community and share the work which has been done so far.
I know the current state of this installer is far from polished, so I would like to create a to-do list of things that need to be done to fully implement this into the mod project/solution itself.

Thank you in advance

**Comment by yobson1** [comment]
I use this bash script on Linux to update. Has optional force flag to skip version check, requires jq.
```bash
#!/bin/bash
echo 'Checking for ValheimPlus updates'

releases=$(curl -s https://api.github.com/repos/valheimPlus/ValheimPlus/releases)
latestVersion=$(echo "$releases" | jq -r ".[0].tag_name")

if [[ $* != *--force* ]]
then
        currentVersion=$([ -f 'curver.txt' ] && echo $(cat curver.txt) || echo "0.0.0")

        echo "Current version: $currentVersion"

        if [[ $latestVersion != $currentVersion ]]
        then
                echo "Newer version $latestVersion found"
        else
                echo "$currentVersion is latest"
                exit
        fi
else
        echo "Skipping version check"
fi

echo "Downloading ValheimPlus $latestVersion"

downloadURL=$(echo "$releases" | grep -m 1 "browser_download_url.*UnixServer.\zip" | cut -d : -f 2,3 | tr -d \")
echo "$downloadURL" | wget -qi - --show-progress

echo 'Installing ValheimPlus'

unzip -q -o UnixServer.zip
rm UnixServer.zip
chmod u+x start_server_bepinex.sh

echo $latestVersion > curver.txt

echo 'Done'
```

**Comment by Witteborn** [comment]
Thank you, I just added support for Unix.

Please let me know if you encounter any issues.

**Comment by radmint** [comment]
Thank you @Witteborn this is in progress by several awesome contributors.

**Comment by nxPublic** [comment]
Check this out https://github.com/dyoung522/valheim-plus-installer
