### ISSUE TITLE
Object Reference not set to an instance of an object 

### ISSUE THREAD

**Issue by neverke1** [valheimPlus/ValheimPlus#164]
Everytime I start the game the bepinex log dumps this out in red and not sure if it's known or not, might as well send it in. 

![image](https://user-images.githubusercontent.com/68199224/109367572-b4485980-7896-11eb-9f1d-8c498ca1e13a.png)

**Comment by radmint** [comment]
Thank you for reporting @neverke1, this doesn't have any affect on the game but is a case of an uncaught exception. I think we've fixed this in the next release but I'll leave this open until I verify that.

**Comment by radmint** [comment]
This error should be properly handled in the next release. I'm going to close this now and if you still see the issue, open a new bug please.
