### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Witteborn** [valheimPlus/ValheimPlus#165]
Valheim Plus Compiler Requirements

3. Download this ~this~ repositories executable version.
Repo: https://github.com/MrPurple6411/Bepinex-Tools/releases/tag/1.0.0-Publicizer
Exec: https://mega.nz/file/oQxEjCJI#_XPXEjwLfv9zpcF2HRakYzepMwaUXflA9txxhx4tACA

**Comment by radmint** [comment]
Since your fix is pending merge, I'm going to close this issue. Thank you @Witteborn!
