### ISSUE TITLE
Console spam and & Lag

### ISSUE THREAD

**Issue by unovalegends** [valheimPlus/ValheimPlus#168]
Since the new update, the server has been acting strange. There is weird console spam that happens here a link of it https://pastebin.com/EHgc0V39 

After 2 people join the server everyone in the server starts to lag. No one can open certain chests, use portals, or open doors. Also, when someone logs off everything they did within those 5 hours progress gets delete as a rollback happens.

**Comment by Alintya** [comment]
Same kind of problems here on 0.146.11 and 0.9

**Comment by nxPublic** [comment]
Your dataRate= in the [Server] section is too high.

**Comment by unovalegends** [comment]
Okay, so what is the rate I should up?

**Comment by nxPublic** [comment]
Currently we suggest to not go above 360~

Set it to 120 and up it until you get errors.

**Comment by unovalegends** [comment]
Well it was set at 360 prior and now lower it to 60 and it still lagging occurs.

**Comment by Alintya** [comment]
@nxPublic what destroyed it tho? I was running 600 and beyond just fine before 0.9

**Comment by nxPublic** [comment]
We have a suspicion on what might be causing this issue.

0.9.2 is hopefully out later today CET, if I can manage that it will hopefully fix several issues related.
