### ISSUE TITLE
[Feature Request] Max ping / packet-loss settings

### ISSUE THREAD

**Issue by rr222cy** [valheimPlus/ValheimPlus#169]
Hi!

I have a suggestion for a feature that would be really nice, might not be possible but here goes. Been experiencing at times users connecting to servers with a bad internet connection. Either a slow one causing sync issues between client and server through high ping or unstable connections causing packet loss and de-sync for other players on the server.

To be able to set maximum ping/packet-loss or the like would be great!

**Comment by radmint** [comment]
I don't think this would be a good idea. What should happen if someone's client hits the maximum ping? Would they get booted? What about when a client gets a blip for a second and that exceeds the max? When you share your server, you should give the location of the server and imply that that's the only region people should try to join from.

**Comment by rr222cy** [comment]
> 
> 
> I don't think this would be a good idea. What should happen if someone's client hits the maximum ping? Would they get booted? What about when a client gets a blip for a second and that exceeds the max? When you share your server, you should give the location of the server and imply that that's the only region people should try to join from.

Since it would be optional I don't really see it being a problem, the roof for the setting I would suppose would be set quite high though to not get booted on "OK" connections. It's not really about regions, for example I'm hosting a server and only have players connected to it within a 300 kilometer radius, however everyone is using different ISP:s and one is using a very bad 4G connection causing issues for others.

But perhaps it's not in the scope for ValheimPlus and I would completely understand that, just a small suggestion born from need! 😄
