### ISSUE TITLE
Feature request: Allow cheats on dedicated servers

### ISSUE THREAD

**Issue by broizter** [valheimPlus/ValheimPlus#17]
Currently cheats does nothing when used on a dedicated server. An option to enable them would be awesome!

**Comment by MadJayQ** [comment]
I've been tinkering with implementing these (and more!) based on my PR https://github.com/nxPublic/ValheimPlus/pull/69 The games vanilla console is kind of a mess.

**Comment by Loivado** [comment]
Would love to see that, we could do planned events for the servers with that. :)

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Server as "Permission System for Console Commands".
