### ISSUE TITLE
Improve configuration note for Fireplace/onlyTorches

### ISSUE THREAD

**Issue by xiaodoudou** [valheimPlus/ValheimPlus#171]
Hi,

We should improve the configuration note for the onlyTorches parameter we can see here:
https://github.com/valheimPlus/ValheimPlus/blob/80831fc4a62805a1a18103b2ef8b0aa26859fd13/valheim_plus.cfg#L87

If the section is set to Flase, the onlyTorches parameter won't be triggered.

**Comment by rr222cy** [comment]
Agreed, I suggest formatting it like:

```
[Fireplace]
needToRefillFireplaces = true;
needToRefillTorches = false;
```
