### ISSUE TITLE
[Feature Request] Share map markers too

### ISSUE THREAD

**Issue by astranberg** [valheimPlus/ValheimPlus#176]
Enough said. Would love to be able to share markers with my buddies, like "built a dock over here."

**Comment by radmint** [comment]
Please follow [this issue](https://github.com/valheimPlus/ValheimPlus/issues/176) for updates, I'm going to close this as a "duplicate" so that issues remain easy to find and sort through. Thank you for the request!

**Comment by astranberg** [comment]
Do you mind linking the other thread?

**Comment by radmint** [comment]
@astranberg I linked it in my comment in the "this issue" text https://github.com/valheimPlus/ValheimPlus/issues/176

**Comment by astranberg** [comment]
This is #176. The link just brings me back here.

**Comment by radmint** [comment]
Oh jeez my b sorry about that. Here's the right one: https://github.com/valheimPlus/ValheimPlus/issues/50
