### ISSUE TITLE
[FEATURE REQUEST] Permissions Files for server commands

### ISSUE THREAD

**Issue by ZanzyTHEbar** [valheimPlus/ValheimPlus#178]
Hey guys, LOVE what you are doing here. I know some C#, C++ and mostly Javascript - i work on minecraft servers professionally. 
I've setup a dedicated Valheim server for my discord community - we all love it.. However ... we would like a Rank system and a Permissions system. What i mean by that is, on a Minecraft server, your Dev commands/admin commands are controlled via permissions nodes using a permissions plugin that hooks into the mod/plugins API. This allows an Admin to assign mod privilege's to certain Ranks or User groups. While one could use this to monetize their server, we have absolutely no interest in that. Instead this is a Quality of Life thing. You see ... we all love the game, but some people in our server CONSTANTLY spawn in food, high level gear, mats, and it ruins the immersion and gameplay for the rest of us. Now, we could kick this player - but thats not a good solution, and other players will just join and do the same thing. The thing is we LOVE the mod and all that it offers, we simply want to be able to GRANT users spawning privilages (for instance) if they EARN them by being an active member of the discord and dedicated server. 

I am 100% down to help bring this to life, i honestly don't know where to start, but we NEED this functionality. 

Now, i know that the mods are Client-Side and not Server-side - so a permissions plugin is ... well pretty damn hard tbh - perhaps a server-side congif file that overides a client-side permissions file when connecting to servers that have the permissions "plugin" enabled?

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Server as "Permission System for Console Commands".
