### ISSUE TITLE
Bash script for launching game client on Unix Server release broken

### ISSUE THREAD

**Issue by Broam** [valheimPlus/ValheimPlus#180]
Turns out the Unix "Server" install also works for Linux Game Clients, except that line 35 fails with "Bad substitution"

**Comment by Broam** [comment]
Modifying the script to launch the executable directly after all the preload lines makes the game client run, I just don't know enough about bash to fix the problem

**Comment by taleden** [comment]
I had this same problem, it's because the script shebang is "#!/bin/sh" when it should be "#!/bin/bash" -- the invalid substitution it's trying to do is something the bash shell understands, but sh doesn't. So either fix that first line, or just call the script via bash explicitly: "bash ./start_game_bepinex.sh".

**Comment by scorpnet** [comment]
I managed to get the bash command to work under GNOME, but when I switched to KDE it refuses to run

./start_game_bepinex.sh: line 35: 115629 Aborted                 (core dumped) "$exec" ${@:2}

**Comment by scorpnet** [comment]
Well, switching back to GNOME did not work either, I can't get it to run anymore at all.

**Comment by nxPublic** [comment]
We added a additional run.sh to the next release and updated to the latest BepInEx version. 

We do not provide assistance with setting up your Unix Server Instance.

If you want help check out the discord help channels: http://discord.valheim.plus

**Comment by Broam** [comment]
"We do not provide assistance with setting up your Unix Server Instance."

Not material. I'm using Linux to run the _client_
