### ISSUE TITLE
[FEATURE REQUEST] Pvp Server

### ISSUE THREAD

**Issue by dariuskis** [valheimPlus/ValheimPlus#181]
It would be realy nice if pvp feature would be in valheimplus , when you can turn on pvp status and cant turn off, or on specify day pvp status turns on and you cant turn off. And on pvp servers would be realy nice to disable some times like that cheater sword because its too op, or disable every single item from other servers, only thouse items witch you make in this server.

**Comment by radmint** [comment]
@dariuskis please follow[ this issue](https://github.com/valheimPlus/ValheimPlus/issues/26) for any updates. Closing this as "duplicate" so that issue remain easy to find and sort through. Thank you for requesting!
