### ISSUE TITLE
[Enhancement] ValheimPlus.dll file version

### ISSUE THREAD

**Issue by rr222cy** [valheimPlus/ValheimPlus#184]
Just a small suggestion of an enhancement for tools working with ValheimPlus and need to fetch currently installed version of ValheimPlus. To add file version to the ValheimPlus.dll.

As of now all releases show the version as being 1.0.0.0

Suggested change for e.g. version 0.9

0.9.0.0

**Comment by nxPublic** [comment]
Will be included from 0.9.3 onwards.
