### ISSUE TITLE
[Feature Request] Control the speed at which holding E inserts items.

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#185]
Right now holding E to insert items into Kilns or Smelters is much slower than tapping E very fast.
It would be a cool addition to be able to control that.

**Comment by astranberg** [comment]
Mind if I expand your idea to include holding left click as well?

**Comment by Xiaminou** [comment]
Of course, the idea is to make it easier to insert a large quantity of items into a Smelters/Kilns, doesn't really matter how it's done.
Thank you.

**Comment by Keydose** [comment]
To add to this, maybe the rate could be based on a speed cap in the config and could start slow and build up speed (quickly) via an exponential or linear scale based on how long you've been holding the button down.

**Comment by astranberg** [comment]
There are a few mods ya'll might find useful:
- [Hold Attack](https://www.nexusmods.com/valheim/mods/236)
- [Craft Build Smelt Cook Fuel Pull From Containers](https://www.nexusmods.com/valheim/mods/40) which has the ability to press Shift+E to send max into the container (i.e. a full 10 ores in at once).

**Comment by nxPublic** [comment]
#188 is the better option.
