### ISSUE TITLE
[Feature Request] Configuration GUI

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#187]
This might be more of a long-term feature, but I think it would massively improve the user-friendliness of this mod.
As the config file grows and grows it becomes increasingly difficult to navigate and to find what you're looking for, I suggest developing a user interface to generate that config file with all your preferred settings. I would look similar to a game's options menu with tabs for each category of the config file.

**Comment by rr222cy** [comment]
I'm working on one, you can find it here: https://github.com/rr222cy/ValheimPlus-Manager

Done a pull request here as well so if it gets approved it should become available in this repository in the future. :)

**Comment by nxPublic** [comment]
We are actually working on this, still. It shouldn't be long anymore.

**Comment by Mixone-FinallyHere** [comment]
Implemented in version 0.9.8
