### ISSUE TITLE
[Feature Request] Add all resources to kiln/smelter/etc. in one keypress

### ISSUE THREAD

**Issue by neoKushan** [valheimPlus/ValheimPlus#188]
I have my Kiln set to be able to hold 200 wood instead of the default 25, which is a fantastic help but it's a huge faff mashing the key 200 times just to fill it.

Would be nice to have a small QoL option to just dump everything you've got into it with a single keypress, maybe even just by holding down the button.

**Comment by Qwertronix** [comment]
If the logic for it can be worked out easily enough, another approach might be to just insert one stack at a time from the player's inventory (i.e. respecting each stack size).

**Comment by greenskye** [comment]
[This mod](https://www.nexusmods.com/valheim/mods/107) implements 'insert stack at a time' behaviour. Would like to see something similar for V+
