### ISSUE TITLE
Night time speed question?

### ISSUE THREAD

**Issue by rez6** [valheimPlus/ValheimPlus#193]
Does night time speed multiplier work correctly or am i entering a number wrong, i tried just 5 and 980 but not sure if i notice any change on my dedicated server, do i need to add a % sign? just trying to make night time pass faster, thanks! :)

**Comment by xiaodoudou** [comment]
Hi @rez6 

The last update of V+ change the logic on it and the math doesn't really follow the configuration notes.
You can check #154 there is already a bug reported.

Cheers,

**Comment by radmint** [comment]
@rez6 please follow discussion here: https://github.com/valheimPlus/ValheimPlus/issues/193 . So that we keep our issues easy to find and sort through, I'm going to close this as a duplicate.
