### ISSUE TITLE
[Feature Request] Server Side Map

### ISSUE THREAD

**Issue by maci0** [valheimPlus/ValheimPlus#194]
Should be possible to add this https://github.com/Mydayyy/Valheim-ServerSideMap it's also open source.

**Comment by Mixone-FinallyHere** [comment]
A synchronized Map is already in the mod

A coming soon patch will make it update on join

**Comment by maci0** [comment]
Couple of hours ago that code also got some addition to share map markers. Maybe it could be borrowed and integrated into V+

**Comment by radmint** [comment]
@maci0 please don't share others' code and ask us to put it in our mod. We don't take others' code and if you find a feature in another mod that we don't have, you should use that mod. Like Mix said, we have a map sharing feature with an upcoming patch. Closing this as a duplicate.

**Comment by maci0** [comment]
Understood. Didn't know what the current status of the V+ implementation of that feature was. And given the other code was open source it may or may not have been worth a look to avoid duplicate work or have a reference at least.
