### ISSUE TITLE
[BUG] showRequiredItems=true clipping text when more than 10 items

### ISSUE THREAD

**Issue by ShammyLevva** [valheimPlus/ValheimPlus#195]
Crafting an iron requiring 20 Iron I have 30 in inventory the Iron bar text clips if the showRequiredItems is true

![image](https://user-images.githubusercontent.com/29687786/109442545-6e26fd80-7a30-11eb-9f2a-60fe24304e95.png)

**Comment by xiaodoudou** [comment]
A quick fix would be to reduce font size after a certain length.

**Comment by radmint** [comment]
We've merged @xiaodoudou's fix for this so I'm going to close this as resolved and it will be in the next release. Please open a new bug if this issue persists after the next release.
