### ISSUE TITLE
[Feature Request] Translucid unplaced object

### ISSUE THREAD

**Issue by xiaodoudou** [valheimPlus/ValheimPlus#196]
Hi,

The idea would be to have opacity on the unplaced object with an overlay color (blue/yellow/green) to mimic what over games of the kind are doing.
The purpose is pretty simple; it helps with better visibility to ensure your object is fully aligned before placing it.

I have seen some WIP on copy feature you guys are working on and I believe it could be achieved ;-).

Cheers,

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ABM: Add color filter on object being modified for better visbility](https://trello.com/c/WModuITt/43-abm-add-color-filter-on-object-being-modified-for-better-visbility)

**Comment by nxPublic** [comment]
Our grid alignment mode for 0.9.6 and the accuracy of all the different placement modes should be good enough.
