### ISSUE TITLE
Disable transfers and better wards.

### ISSUE THREAD

**Issue by unovalegends** [valheimPlus/ValheimPlus#198]
Feature request- I was wondering if you were able to set a feature where server owners can disable and prevent players from transferring their characters and items and gear from other servers. Also, a feature the gets wards stronger protection so players can't break anything inside the ward.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ward protection improvements](https://trello.com/c/Ge8p6HZO/37-ward-protection-improvements)

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disable player/server item transfer](https://trello.com/c/jBjDkUlY/41-disable-player-server-item-transfer)

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Have ward protect players from breaking things inside its range](https://trello.com/c/q3MayWSN/42-have-ward-protect-players-from-breaking-things-inside-its-range)

**Comment by YannMCX** [comment]
There's already an issue with this feature : #75

**Comment by radmint** [comment]
@YannMCX we kept this feature request up to track the ward improvements https://trello.com/c/Ge8p6HZO/37-ward-protection-improvements

**Comment by nxPublic** [comment]
Closed because of duplication.

**Comment by mdcohen** [comment]
Shut the fudge up and go to sleep. You’re making us mad by now. And nobody
wants to make us mad. Trust me.
