### ISSUE TITLE
[Improvement] Fireplace settings

### ISSUE THREAD

**Issue by rr222cy** [valheimPlus/ValheimPlus#201]
Hi!

A common issue popping up several times a day is confusion regarding the config-file settings for [Fireplace]. From a devs point of view it's logical, from a normal user- confusing.

How it looks today

```
[Fireplace]
; If changed to enabled all fireplaces do not need to be refilled.
enabled=true
; If you enable this option only placed torches do not need to be refilled.
onlyTorches=true
```

Suggestion for how to improve it

```
[Fireplace]
; Set to true to enable the settings
enabled=true
; Set to true to disable the need for refilling fireplaces
fireplaceNoRefilling=true
; Set to true to disable the need for refilling torches
torchesNoRefilling=true
```

**Comment by rr222cy** [comment]
Haha, I forgot I already suggested something similar over here: https://github.com/valheimPlus/ValheimPlus/issues/171 🙈 

Maintainers, you can close this or set it as the primary Issue thread. Sorry for the duplicate!

**Comment by radmint** [comment]
Thanks @rr222cy we're definitely working on better documentation! I'll close this as a duplicate and we'll keep our eyes on #171
