### ISSUE TITLE
Incompatible Versions - enforceMod=true Clientside

### ISSUE THREAD

**Issue by Liukus** [valheimPlus/ValheimPlus#202]
Short and sweet: freshly installed both 0.9 server and client files. Set up my server config how I'd like it. Set the enforceMod=false.
Cannot connect my enforceMod=true client running the exact same version to the server. If I change the client-side to false I connect no problem. 

Shouldn't the server allowing all connections allow a client-side that's checking versions of the same version?

Server log reads that the clientside 0.146.11@0.9 isn't the same as 0.146.11 of the server.

I get this may be an issue with keeping the server available for vanilla connections, as both would read 0.146.11. Is there a workaround, or am I going to have to get my players to modify their default install so this will work?

Update for 0.147.3 - No change, but can include more info:
Server Log with enforceMod=false on client, false on server: 03/02/2021 12:35:02: VERSION check their:0.147.3  mine:0.147.3
Server Log with enforceMod=true on client, false on server: 03/02/2021 12:47:06: VERSION check their:0.147.3@0.9  mine:0.147.3
Update 2: I combed my player log file on the client for the feedback from it's connection fail.
03/02/2021 12:47:03: Connected
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 12:47:03: Got connection SteamID 90143613425129483
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Version generator started. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Version generated with enforced mod : 0.147.3 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 12:47:07: Got connectoin error msg ErrorVersion
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 12:47:07: Lost connection to server:ErrorVersion

What's interesting is that the Version generated with enforced mod : 0.147.3 isn't actually outputting to the log what it's sending to the server. While the code should be outputting that to the log in both Console.cs and Version.cs, it's not adding in the plugin version in the logs: 
"
{
                        Debug.Log($"Version generated with enforced mod : {__result}");
                        __result = gameVersion + "@" + ValheimPlusPlugin.version;
                        return false;
                    }"

**Comment by paulvilla** [comment]
Exactly, I am having the same problem, it expels the users for incompatible version, I am the administrator and I use the same file in client / server.

At the moment I can only enter if I deactivate it

**Comment by nxPublic** [comment]
Please post your entire server console logs.

We can only help you if you post your server logs to have some idea what might be going wrong for you.

**Comment by kheldaroz-droid** [comment]
i think the @0.9 is coming from ValheimPlus

**Comment by kheldaroz-droid** [comment]
ok my issue was caused by not installing the correct version - i had the dedicated server version installed on the client not the client version
