### ISSUE TITLE
[Feature Request] Terrain Height Manipulation Configuration

### ISSUE THREAD

**Issue by Samsterious** [valheimPlus/ValheimPlus#203]
Currently, players have a maximum and minimum height which appears to be determined by the natural heightmap. Being able to modify or disable the maximum delta height would permit more freedom, for instance to level large areas of terrain that begin on a long slope.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Terrain Height Manipulation Configuration](https://trello.com/c/DcOrvflZ/40-terrain-height-manipulation-configuration)

**Comment by Dragory** [comment]
Being able to modify the minimum height ("dig limit") would also allow canals where it's currently not possible.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under World as "Remove Ground Height Limits".
