### ISSUE TITLE
[Feature Request] Change Map sync

### ISSUE THREAD

**Issue by darkvergus** [valheimPlus/ValheimPlus#204]
Change the map sync between clients to be serversided or maybe add another option. This will allow for everyone to have the same map and have it update when they rejoin.

**Comment by radmint** [comment]
@darkvergus this is in progress at the moment. I'm going to close this feature request as a duplicate. Please follow this issue for updates going forward: https://github.com/valheimPlus/ValheimPlus/issues/50
