### ISSUE TITLE
[Feature Request] Mute sound when in background

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#205]
Add an option for the client to mute Valheim's sound when it's in the background.
It should be in the base game but since it's not I'm hoping you guys can help with that.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mute sound when in background](https://trello.com/c/lTa26r9D/39-mute-sound-when-in-background)

**Comment by nxPublic** [comment]
This has been added for 0.9.7 by #430
