### ISSUE TITLE
disconnection with the new version of Valheim v(0.147.3) - v.Valheim_mod (0.9)

### ISSUE THREAD

**Issue by paulvilla** [valheimPlus/ValheimPlus#207]
After the new version that Valheim has released, it no longer enters the server, it doesn't even ask for the password.

I have reinstalled the server and the client and later the mod and the same thing keeps happening.

SO Client: Windows 10
OS Server: Debian 10

**Comment by xiaodoudou** [comment]
If both client and server are validated and launch w/o V+; does it works?

Could you provide your client logs of BepInEx?

**Comment by paulvilla** [comment]
I close the entry that the version does work, the problem is in the verification of the file
