### ISSUE TITLE
[Bug] Cannot sleep when totalDayTimeInSeconds is changed

### ISSUE THREAD

**Issue by NicholasEwing** [valheimPlus/ValheimPlus#209]
When changing the day/night cycle time (`totalDayTimeInSeconds`) to a non-default value, players on dedicated Valheim+ servers cannot sleep.

Let me know if you need any further steps to reproduce.

**Comment by darkvergus** [comment]
I believe this is a duplicate to #170 and has already been fixed in the latest version that is to be released with the merge #172

**Comment by NicholasEwing** [comment]
Thanks, sorry I didn't check for existing tickets are thoroughly as I could've. Closing due to due to duplicate #170
