### ISSUE TITLE
[Feature Request] Show ammo count when bow is equipped

### ISSUE THREAD

**Issue by Bhudev35** [valheimPlus/ValheimPlus#210]
Hopefully I didn't miss someone else requesting this, but add an option to the hud that show Arrow count when a bow is equipped.

**Comment by fant0mas9** [comment]
And arrow type equipped would be a useful combination with this.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show ammo count when bow is equipped](https://trello.com/c/I11oAePL/54-show-ammo-count-when-bow-is-equipped)

**Comment by Mixone-FinallyHere** [comment]
Implemented in #517
