### ISSUE TITLE
[Feature Request] Option to make all items float

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#213]
Self-explanatory, add a config option that makes all items float so we can stop losing items to the abyss.

**Comment by Casualfield** [comment]
Agreed.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Option to make all items float](https://trello.com/c/OhXBHSfB/53-option-to-make-all-items-float)

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Items as "Option to make all items float".
