### ISSUE TITLE
[Bug?] Torches run out of fuel with infinite fuel turned on

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#214]
I think it has to do with server restarts and/or the area being unloaded. My torches (and sconces and variants) keep running out of fuel. I leave one day with all torches on and the next day they are all off.

**Comment by zedle** [comment]
This may be fixed in the upcoming release. @Mixone-FinallyHere ^

**Comment by nxPublic** [comment]
Should be fixed with 0.9.3

**Comment by Xiaminou** [comment]
So far so good, restarted twice, torches are still lit.
