### ISSUE TITLE
has incompatible version, mine:0.147.3 remote 0.147.3@0.9

### ISSUE THREAD

**Issue by christi1705** [valheimPlus/ValheimPlus#219]
03/03/2021 22:58:08: Peer 76561198082126346 has incompatible version, mine:0.147.3 remote 0.147.3@0.9

Used the latest versions..

**Comment by baughj** [comment]
I am also getting this using latest release on Ubuntu 20.04.

**Comment by Akkowicz** [comment]
Install **libc6-dev** and **mono-complete**, restart the application and try again.

**Comment by baughj** [comment]
I can replicate this error reliably:

Valheim installed via
`./steamcmd +login anonymous +force_install_dir /home/steam/valheimserver/ +app_update 896660 validate +exit`

Release installed with `tar -xzvf ../UnixServer.tar.gz` (eg into valheimserver dir)

On startup, I am getting a preloader log file with an error similar to here `https://github.com/BepInEx/BepInEx/issues/162`
I also don't see anything from `BepInEx` in the logs.

If I edit the mapping file ` valheim_server_Data/MonoBleedingEdge/etc/config` and add 
`<dllmap dll="dl" target="libdl.so.2"/>` it works - _but_ you have to reinstall entirely as it seems that once it has the wrong version it does not autocorrect itself (meaning I had to rm -rf valheim and the mod, reinstall valheim, install the mod, edit the file, and start the server)

After that I do indeed see it running and it does work.

```
[Info   :Valheim Plus] Configuration file loaded succesfully.
[Info   :Valheim Plus] ValheimPlus [0.9] is up to date.
```

Just tried with @Akkowicz suggestion and that is definitely the easier fix. 👍

**Comment by christi1705** [comment]
Thanks for your help :)
Install the missing dependencies solved my problem (Y)

**Comment by gOOvER** [comment]
> Install **libc6-dev** and **mono-complete**, restart the application and try again.

Is mono really needed?
