### ISSUE TITLE
[BUG] Missing "Remove death marker on the map on collecting your tombstone" cfg

### ISSUE THREAD

**Issue by alrick** [valheimPlus/ValheimPlus#220]
On the main page (https://github.com/valheimPlus/ValheimPlus) there is a config on the map section stating : "Remove death marker on the map on collecting your tombstone".

But I can't see it in the cfg file : https://github.com/valheimPlus/ValheimPlus/blob/master/valheim_plus.cfg

**Comment by radmint** [comment]
Fix merged
