### ISSUE TITLE
[Feature Request] Chance to produce "Exceptional" item

### ISSUE THREAD

**Issue by shilliash** [valheimPlus/ValheimPlus#221]
On every craft player can have a chance of crafting exceptional item - that may have different stats as for example:

- better durability (5% more than basic value)
- lesser stamina drain on action (5% less)
- bigger knockback rate (5% more)

Those exemplary modifiers can depend on individual item stats as they are quite different from item to item.

It would be perfect if crafting skill is also introduced and you can have a chance of crafting "Exceptional" item only if specific crafting skill is high enough. 

Crafting skill example:

Bowcrafting   
- it increases 0,2 points for every bow crafted 
- exceptional item crafting chance is 1,5% for Bowcrafting skill  <=10
- exceptional item crafting chance is 2,5% for Bowcrafting  skill <=20
- exceptional item crafting chance is 5% for Bowcrafting <=30
- exceptional item crafting chance is 7,5% for Bowcrafting <=40
- exceptional item crafting chance is 10% for Bowcrafting <=50
(...)
- exceptional item crafting chance is 25% for Bowcrafting <=100

It goes perfect with "Disenchanting Items" - that idea is already there in Trello and here. 
Keep up the great work.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exceptional item creation chance](https://trello.com/c/lVk6r1kd/52-exceptional-item-creation-chance)

**Comment by nxPublic** [comment]
While we like the idea, we have to turn this down for now since it would be too much of a interference with the game balance and mechanics. Essentially we aren't at the point of adding new content to the game yet.
