### ISSUE TITLE
[Feature Request] Berries yeld increase option

### ISSUE THREAD

**Issue by shilliash** [valheimPlus/ValheimPlus#222]
As subjected it is kind of self explanatory. I am considering weird player receives only 1 berry from entire bush - would be awesome if we have a chance to modify that to 2 or 3 pcs from one bush via V+

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [modifiers for production of berries on all kinds of bushes](https://trello.com/c/t56Nebci/51-modifiers-for-production-of-berries-on-all-kinds-of-bushes)

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Items as "Modifiers for Berries and Bushes".
