### ISSUE TITLE
[BUG]Unix Server package has outdated BepInExPack causing "incompatible version" issue

### ISSUE THREAD

**Issue by jad0083** [valheimPlus/ValheimPlus#228]
Good Day,

Seems like the Unix Server edition (as far as I've been able to test), has an outdated BepinExPack, which causes clients to error out with "incompatible version".

downloading the latest version from here, and extracting over fixes the issue:
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/ - latest release was 3/4/21

updating the server and client packages with the latest version should fix the issue.

**Comment by stingwraith** [comment]
> Good Day,
> 
> Seems like the Unix Server edition (as far as I've been able to test), has an outdated BepinExPack, which causes clients to error out with "incompatible version".
> 
> downloading the latest version from here, and extracting over fixes the issue:
> https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/ - latest release was 3/4/21
> 
> updating the server and client packages with the latest version should fix the issue.

I've updated both server and client from the link you provided but I am still getting version mismatch error.

Curiously, if I don't have any BepInEx installed client-side, I don't get the error, but the mod doesn't work(where previously I would still get the version mismatch error).

**Comment by radmint** [comment]
Thank @jad0083 please use the Bug template provided for filing bugs. I'm closing this and you may open another using the template if you wish.

**Comment by nxPublic** [comment]
The version mismatch error has not do anything with the supplied BepInEx version.

**Comment by stingwraith** [comment]
> The version mismatch error is not related to the supplied BepInEx version.

Is there any way to sort this out? I have re-installed both client-side and server-side twice from each BepInEx release(GitHub + noted above) and I always get version mismatch:(

**Comment by tanis2000** [comment]
This is happening to me as well, any hint at what the issue might be?
