### ISSUE TITLE
[FEATURE REQUEST] Disable Portals

### ISSUE THREAD

**Issue by ocgineer** [valheimPlus/ValheimPlus#229]
For more "immersive" or "hardcore" servers it would be nice to disable the portal creation or teleport function altogether for everyone or an option for only admins to place portals where everyone else still can use them, so players will have to use the boats more often other than for transporting metals.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Portal difficulty increase](https://trello.com/c/4OmvNMOC/50-portal-difficulty-increase)

**Comment by nxPublic** [comment]
![image](https://user-images.githubusercontent.com/39051287/110122278-460f0580-7d74-11eb-9a62-8bb96075f00d.png)

In 0.9.4
