### ISSUE TITLE
[FEATURE REQUEST] Keep the mouse cursor in the same spot as when it looses focus

### ISSUE THREAD

**Issue by ChristopherHaws** [valheimPlus/ValheimPlus#231]
**Is your feature request related to a problem? If so, please describe.**
Every time I open and close chests, stop looking at my inventory, or exit the build menu my mouse cursor moves gets re-centered by the game so that when I reopen the chest, inventory, or build menu, I have to move my mouse back to the previous location.

**Describe the solution you'd like**
I would love it if the game remembered my mouse location when it looses focus instead of being re-centered on the screen.

**Additional context**
This is how Minecraft (at least bedrock edition) handles this and it feels very natural.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Keep the mouse cursor in the same spot as when it looses focus](https://trello.com/c/uFXPDfnq/55-keep-the-mouse-cursor-in-the-same-spot-as-when-it-looses-focus)
