### ISSUE TITLE
[FEATURE REQUEST] Sharing Map icons

### ISSUE THREAD

**Issue by Digifreakl** [valheimPlus/ValheimPlus#233]
Hello

When playing with friends it would be nice if we could share map Icons, so not everyone has to set a icon on a specific location 

My Idea was :

Idea A: if someone has a icon , it gets shared to other players (like a sync)

Idea B: If someone sets a icon, every player currently online gets one on his map (drawback is, some players will have multiple icons on same location, until all player have it)

just saw it was already requested

**Comment by SerinitySW** [comment]
Not sure why you closed this, I still very much want this feature. Maybe even the ability to only sync certain icons?
