### ISSUE TITLE
[BUG] v0.9.3 object instance not set constant error

### ISSUE THREAD

**Issue by ShammyLevva** [valheimPlus/ValheimPlus#235]
Just upgraded to v0.9.3 from v0.9 and login. Once character appears it produces a constant stream of errors as follows, the errors only stop when I logout. Since the build is only 1 hour old I thought an urgent bug report was required. I'll have a look myself to see if I can create a patch but meantime here is the report that someone who was working on that area might fix more quickly than I could. 

[Info   : Unity Log] 03/05/2021 13:17:57: Minimap: Adding unique location (4.7, 33.1, 7.0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.ModifyPlacingRestrictionOfGhost.Postfix (Player& __instance) (at <7f3756a8cdc342ac98d8e07c307fe758>:0)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacementGhost>(Player,bool)
Player.LateUpdate () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.ModifyPlacingRestrictionOfGhost.Postfix (Player& __instance) (at <7f3756a8cdc342ac98d8e07c307fe758>:0)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacementGhost>(Player,bool)
Player.LateUpdate () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)

**Comment by nxPublic** [comment]
I see the issue, its not actually a problem.

It should not affect anything in a practice.

**Comment by ShammyLevva** [comment]
I've tested further and can confirm with 100% certainty that the issue is turned on or off by changing the line in config

cropNotifier=true  ; turns on bug
cropNotifier=false ; bug no longer appears

**Comment by nxPublic** [comment]
We are aware of the issue, fixed it already locally.

There should not be any practical gameplay issue with this though.

**Comment by nxPublic** [comment]
I will make sure to release a 0.9.4 tomorrow, I already have new features ready for that anyway.

It will contain a fix, for now I'd suggest to turn off the crop notifications.

**Comment by ShammyLevva** [comment]
yup turned off - I'm a dev myself so well aware of unintended consequences of a bug so just wanted to make devs aware before the uninformed start waving their torches and pitchforks (or cultivators) and storming the castle demanding a fix or suggesting you broke their world when it's just an inconsequential reporting error. It's the red text that scares them :)

**Comment by nxPublic** [comment]
Fixed in today 0.9.4, release in about a hour or two max.
