### ISSUE TITLE
[Bug] LOX without proper "level markers" (stars)

### ISSUE THREAD

**Issue by shilliash** [valheimPlus/ValheimPlus#236]
- Windows Client
- 0.4.13
- 0,9.3

**Describe the bug**

It seems that those big furries have different levels but actual 1 and 2-star markers does not appear on top of them. 
We've been farming them and some of them have significantly higher damage/HP value but they aren't marked accordingly. 

Thast probably game bug (code error) - nothing to do with mod itself. 

All other animals in game have stars/levels visible excluding those.

**Comment by nxPublic** [comment]
We are not responsible for game bugs, that's coffestains job. We already do enough for them.
