### ISSUE TITLE
Console window disabled in single player mode[BUG]

### ISSUE THREAD

**Issue by rmyer** [valheimPlus/ValheimPlus#237]
- OS: Windows Client
- Valheim Game Version 0.147.3
 - Mod Version 0.9.3

In single player mode the Console Window (F5) is disabled.  You can no longer use any commands (i.e., imacheater, god, etc.)

**To Reproduce**
1. Go to game and log in single player mode
2. Click on F5
3. See error - console window is empty and will not respond to any commands typed into the console

**Expected behavior**
The Console Window (F5) should respond just like it did in the previous version of this mod.

**Troubleshooting**
I completely uninstalled and reinstalled the game twice.  Each time I ran the game in single player mode first and executed the F5 command and can confirm that it functioned normally.  Once I installed the 0.9.3 mod and went back into the game again to execute the Console Command it failed.

**Comment by nxPublic** [comment]
This is a BepInEx related issue.
