### ISSUE TITLE
[FEATURE REQUEST] Auto update game/client mod at game launch

### ISSUE THREAD

**Issue by guillian77** [valheimPlus/ValheimPlus#238]
Hi

I think it's a good idea to add an option to auto update mod when launching the game.

It can be enabled in a config file or with a script/executable.

I have tried to write a batch script using curl but my competences in batch are limited and I think it's not the more adapted "language".
Also github ask me credential. So I stop to write script here.

```BATCH
curl --silent "https://github.com/valheimPlus/ValheimPlus/releases/latest/download/WindowsClient.zip"
```

I hope this feature does not exist yet and you don't lost your time to read my issue.

Best regards

**Comment by gOOvER** [comment]
Then you heed a check, where V+ runs; there are not only Widows ;)

**Comment by guillian77** [comment]
I switch to powershell to develop the updater.
Executable have to be placed in root game directory

It can be use to launch or update the WindowsClient mod.

An orverview can be found on my repository https://bitbucket.org/guillian77/valheimplus-updater/src/master/

**Comment by nxPublic** [comment]
We won't be adding anything like that anytime soon.

This is too high of a security risk to implement for any mod. If you see a mod doing this, I would be very very very cautious.

**Comment by guillian77** [comment]
Yes it's not faIse. I understand your point of view

**Comment by adaliszk** [comment]
In many Container environments, this would not work because not every host solution allows containers to change their contents outside of volumes, and in many cases, the containers do not have an internet connection to pull resources like that.

**Comment by guillian77** [comment]
> Dans de nombreux environnements de conteneurs, cela ne fonctionnerait pas car toutes les solutions hôtes ne permettent pas aux conteneurs de modifier leur contenu en dehors des volumes et, dans de nombreux cas, les conteneurs ne disposent pas d'une connexion Internet pour extraire des ressources de ce type.

I don't speak about a solution for server side utilisation.

**Comment by xiaodoudou** [comment]
@guillian77 meme pour une situation de download cote client; cela va introduire un risque en terme de securite. Tant que le jeu en lui meme n'introduit pas les mods de maniere officielle avec un system de signature cela sera jamais fiable pour les joueurs.

For not French speakers:
@guillian77 even in a client-side download situation it will introduce a security risk. Until the game itself doesn't introduce officially mods with a signature approach it will never be secured for the users.

**Comment by guillian77** [comment]
> @guillian77 meme pour une situation de download cote client; cela va introduire un risque en terme de securite. Tant que le jeu en lui meme n'introduit pas les mods de maniere officielle avec un system de signature cela sera jamais fiable pour les joueurs.
> 
> For none French speakers:
> @guillian77 even in a client-side download situation it will introduce a security risk. Until the game itself doesn't introduce officially mods with a signature approach it will never be secured for the users.

Yes I understand your arguments and you have got reason. Maybe in the futur :P
I made my little script for my own use and some friends are playing with me on my server.
If someone want to use it for himself, it's free. But I am really not a "Powershell" developper.

Thanks for your sincere answers, and thanks for your work
