### ISSUE TITLE
[BUG] cfg overwritten on update

### ISSUE THREAD

**Issue by blacksythe** [valheimPlus/ValheimPlus#239]
- OS: [All distros]
- Valheim Game Version [e.g. 0.4.11, etc] 147.3
 - Mod Version [e.g. 0.9, 0.9.2, etc.] 0.9.3

**Describe the bug**
A clear and concise description of what the bug is and how you found it.
Updating causes .cfg files to be overwritten.
A better way to do this would be to include the basic cfg file separately for first time users and have it auto generate on first launch.
Updating to a new version should modify/update the existing cfg file not replace the existing one
**To Reproduce**
1. Update valheim plus

**Expected behavior**
explained above

**Troubleshooting**
What steps have you taken to try to fix?
made a backup for now and manually update the new cfg
**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

**Comment by gOOvER** [comment]
Yeah, +100 for this. And pls stop changing on every Update the v+ cfg. 

Add a valheim.cfg.example is a better way

**Comment by KairuByte** [comment]
I mentioned this in the discord, but this is also a pain for dedicated servers with an auto update feature. While each server owner/host/panel maker can take into consideration that V+ will likely have a cfg which will overwrite the existing, it leaves them with only three real options. First is to overwrite it and lose the original data, second is to rename the existing and place it, third is to ignore the new file.

None of these is a good option IMHO. It all leaves work to be done after the fact, for a process that can be fully automated by the plugin itself. On first boot, simply update the existing cfg, or create it if it does not exist.

**Comment by lvarado** [comment]
FWIW, I did notice some config values didn't seem to be backwards compatible when I updated, so I'm not sure how well automation would work until this project is more stable. At the very least, creating a backup like `valheim_plus.cfg.{date}.bak` instead of overwriting the file would make things easier to diff and manually update.

**Comment by KairuByte** [comment]
It's not that the config needs to be left untouched, it's that previous values need to be transferred into the new format.

If a new value is included, or its type changed, then leave it default. But for the vast majority of values, there is a direct 1:1 relation between the old and new versions.

**Comment by lvarado** [comment]
That would be ideal. The values that aren't backwards compatible still present a problem though, like the whole `[Stamina]` and `[StaminaUsage]` sections have changed from some kind of unit to percentage:

https://www.diffchecker.com/lI9hxucf

For example if you had `dodgeStaminaUsage` changed from the default `10` to `5` to reduce it by half, carrying this value over with the 0.9.3 update would increase it by 5% instead. But hopefully this will be eliminated after the early thrashing is done.

**Comment by KairuByte** [comment]
While some situations which are truly not compatible will crop up, that change in particular is computationally solvable.

**Comment by nxPublic** [comment]
We are aware, we are working on it.

**Comment by masonen** [comment]
Great to here. sthl a user cfg which can inherit from the main cfg and just setting the values one does want to override would be neat.

**Comment by spannerman79** [comment]
> We are aware, we are working on it.

Great to hear!

This would make it _extremely_ useful for systems that can pull the latest `ValheimPlus.dll` since https://github.com/valheimPlus/ValheimPlus/issues/324 was so kindly done :smiley:

**Comment by highwaybobbery** [comment]
Just wanted to mention this happens whenever you redeploy mods in vortex as well, I assume it's the same problem.

**Comment by psilvaazevedo** [comment]
My problem related to this, is that if the server reset the config file that previously had configured more slots to a chest and the server ran with the default configuration, user will lost items, because the chest will be resized.

**Comment by masonen** [comment]
Yep Same Happened to med.Rerolled to recent world Backup which was luckily there. Same applies to items in inventory Would bei netter items would bei Just droped in that Case. But i think thats Something dir another issueAm 28.03.2021 21:07 schrieb Pedro Azevedo ***@***.***>:
My problem related to this, is that if the server reset the config file that previously had configured more slots to a chest and the server ran with the default configuration, user will lost items, because the chest will be resized.

**Comment by nxPublic** [comment]
0.9.7 introduced a reliable updating system for cfg files.
