### ISSUE TITLE
Unable to Join Server 0.9.3[BUG]

### ISSUE THREAD

**Issue by Nappa231** [valheimPlus/ValheimPlus#241]
I have copied the mod files into both client and dedicated server folders and updated the new config. Every time anyone tries to join the server it starts to join and then says "Disconnected". This happens on both lan clients and internet clients. It does not even prompt to enter a password for the server. I am uncertain as to what to look for to fix this.

**Comment by KairuByte** [comment]
Want to make sure just in case: If you leave "enforceMod" set to "true", no one with vanilla Valheim can connect. There will be a version mismatch, and anyone attempting to connect will be disconnected.

**Comment by Nappa231** [comment]
I have set that to false. Still sits saying connected and then disconnects. I was able to connect fine in 0.9 but not since upgrading to 0.9.3.

**Comment by blacksythe** [comment]
Try changing the port, sounds odd i know, but i had this with vanilla as well.

**Comment by nxPublic** [comment]
Unrelated to the mod, its not a issue of V+. The issues are on your ends.
