### ISSUE TITLE
[BUG] value of 0 stamina cost of running

### ISSUE THREAD

**Issue by raawbin** [valheimPlus/ValheimPlus#242]
- OS: [Windows Client, Linux Server]
- Valheim Game Version [0.147.3]
 - Mod Version [before 0.9, after 0.9.3]

**Describe the bug**
Changed the value of the stamina cost of running to 0 in the version 0.9 and now after updating it to 0.9.3 the value doesn't seem to affect the stamina drain at all.

**To Reproduce**
1. Change the stamina cost of running to value 0
2. Log into game
3. Run around
4. observe the stamina drain

**Expected behavior**
No stamina drain while running.

**Troubleshooting**
Changed the value to -5, didn't affect the stamina drain.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/et37F43W

**Comment by cheese-demon** [comment]
The stamina usage values are all in percentages now, where in 0.9 and previous they were specific values. To change the stamina cost of running to 0 you would need to put -100 in for runStaminaDrain

**Comment by raawbin** [comment]
must have missed that, thank you very much
