### ISSUE TITLE
[BUG] Torches craft as broken with 0 max durability

### ISSUE THREAD

**Issue by Varinius** [valheimPlus/ValheimPlus#243]
- OS: Windows Client
- Valheim Game Version 0.147.3
 - Mod Version 0.9.3

**Describe the bug**
Crafting torches with durability config as 50% extra makes them craft as broken. They now have x/0 durability.

**To Reproduce**
1. Change durability in config
2. Start game and craft a torch in workbench
3. Torch is broken

**Expected behavior**
Torch max durability is not 0 and doesn't craft broken

**Comment by nxPublic** [comment]
What exact Durability to you change that causes this behavior?

**Comment by nxPublic** [comment]
Fixed in 0.9.5
