### ISSUE TITLE
Typo/Documentation : Tool name 'Hoe'

### ISSUE THREAD

**Issue by Dfluke** [valheimPlus/ValheimPlus#246]
System :
   N/A

Actual Behavior :
   Typo in code comments for case within the durability checks. 'How' is written, expected 'Hoe'

Expected Behavior :
   Correct tool name to 'Hoe'

https://github.com/valheimPlus/ValheimPlus/blob/07e8b2b6a563bb275426eeaad0dff0c968b37279/ValheimPlus/GameClasses/ItemDrop.cs#L68

**Comment by nxPublic** [comment]
Fixed in 0.9.4 later today
