### ISSUE TITLE
Virus Scanner is flagging files

### ISSUE THREAD

**Issue by releep** [valheimPlus/ValheimPlus#249]
Filename: ValheimPlus.dll
Threat name: WS.Reputation.1

Filename: HarmonyXInterop.dll
Threat name: WS.Reputation.1

Filename: Valheim.DisplayBepInExInfo.dll
Threat name: WS.Reputation.1

Filename: BepInEx.dll
Threat name: WS.Reputation.1

These files are flagging as unsafe and are automatically deleted by Norton. I've never had norton flagg anything from valheim plus before. just wanted to double check that these files are indeed the correct files and have not been changed by anyone but the developer.

**Comment by nxPublic** [comment]
You can be free of concern, we would not be able to hide anything malicious in our DLL's.

We can do nothing about these false positives.
