### ISSUE TITLE
[BUG] ABM

### ISSUE THREAD

**Issue by thugjitsugamers** [valheimPlus/ValheimPlus#250]
trying to use ABM and it states that it is active...then immediately says exit ABM...does this twice in a row

**Comment by thugjitsugamers** [comment]
ABM doesn't work with 2 players in the same area

**Comment by nxPublic** [comment]
We are investigating this issue.

**Comment by jesstech** [comment]
From my understanding, this will happen if ValheimPlus is not enabled on the server and your player does not have ownership of the build area.

**Comment by Loivado** [comment]
@jesstech on what is your assumption based on? 
We have the same problem with ABM and AEM on our server. The server is Valheim+ and all Clients are Valheim+.
Our map was created on a vanilla server though, but I don't think that's where issue source is laying. 

As @thugjitsugamers described earlier: 
1. One or more players enter your area (seems like to be 500 meters for our server base for example and we are having no wards anywhere on the map)
2. You try to enter ABM or AEM
-> ABM activates -> ABM deactivates -> ABM activates -> ABM deactivates

**Comment by That3DPrinterGuy** [comment]
Tested on our server, if you set the map reveal to 150 and players are just outside that distance ABM will work, short term solution is to wait to build while everyone is out gathering/fighting.

**Comment by jesstech** [comment]
> @jesstech on what is your assumption based on?
> We have the same problem with ABM and AEM on our server. The server is Valheim+ and all Clients are Valheim+.
> Our map was created on a vanilla server though, but I don't think that's where the issue source is laying. (atleast for us)

Conjecture, really.  My server admin has since installed V+ on the server and the issue persists for us regardless of whose client “owns” the build area.  Still, I think the underlying issue is related—other player clients are unaware/interrupting the subroutine.
