### ISSUE TITLE
[FEATURE REQUEST] Consider editing the Merchant inventory.

### ISSUE THREAD

**Issue by Dfluke** [valheimPlus/ValheimPlus#252]
Wondering if it would be possible to edit the wares that the merchant has for sale. Merchant could sell wares of varying rarity, if possible, specifiable via user config....

Investigate if it is possible for the trader's ware listing to be edited.

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consider editing the Merchant inventory](https://trello.com/c/X5gtdfre/57-consider-editing-the-merchant-inventory)

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Items as "System to modify merchant items and costs".
