### ISSUE TITLE
[FEATURE REQUEST] autoSaveInterval & totalDayTimeInSeconds

### ISSUE THREAD

**Issue by SiniestroO** [valheimPlus/ValheimPlus#253]
Hello, i can't find the "autoSaveInterval" option that was present on v0.9.0 in v0.9.3. is it possible to add the command and expect it to work?

also, the "totalDayTimeInSeconds" option to set the duration of the day on the last version, worked perfectly well for me (i just x2 the day duration) i wan't to know if the options in this new version although they are disabled can be activated.

thanks.

**Comment by radmint** [comment]
Autosave wasn't working correctly so it was removed. As you can see by the text in the .cfg file "THIS FEATURE IS STILL IN DEVELOPMENT AND IS RIGHT NOW DISABLED UNTIL FURTHER NOTICE", we have disabled time configurations and there isn't a way to turn it on until we fix.
