### ISSUE TITLE
[BUG] Startup script bug (easy fix)

### ISSUE THREAD

**Issue by havedill** [valheimPlus/ValheimPlus#256]
Short description of the issue/bug:
Startup script breaks if Unix path contains spaces.

Example
---------
~/Steam/steamapps/common/Valheim dedicated server
./start_server_bepinex.sh: 93: export: server/doorstop_libs:: bad variable name

Resolution
-----------
Quotations around the variable $LD_LIBRARY_PATH

export LD_LIBRARY_PATH=./linux64:"$LD_LIBRARY_PATH"

Mod version:
0.9.3

Sinleplayer or Multiplayer?
N/A

The operation system used:
Ubuntu 20.04

Link to your .cfg file (https://pastebin.com/):
N/A

**Comment by nxPublic** [comment]
Changes added, consider doing a PR for stuff like this ;)
