### ISSUE TITLE
Stamina [BUG]

### ISSUE THREAD

**Issue by UglyNiiiiiick** [valheimPlus/ValheimPlus#257]
Using newest update of VP but for some reason now the stamina usage has returned to default and Im unable to change it. Where as it was fine before the latest update

**Comment by nxPublic** [comment]
Thats a little low in terms of info

Please post your config file to [http://pastebin.com](http://pastebin.com) and link it here.

**Comment by radmint** [comment]
@UglyNiiiiiick please use bug template when filing bug instead of deleting it. We request that information for a reason. I'm closing this and please open a new one with additional info.
