### ISSUE TITLE
[FEATURE REQUEST] Portal Names

### ISSUE THREAD

**Issue by aaskjer** [valheimPlus/ValheimPlus#258]
would be awesome if you could add an option to display portal names while looking at it, like this: https://prnt.sc/10eg8vz

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prominent portal names](https://trello.com/c/acX9HpYq/56-prominent-portal-names)

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Hud as "Show portal names".
