### ISSUE TITLE
Feature Request- Pvp Mode

### ISSUE THREAD

**Issue by Thondargg** [valheimPlus/ValheimPlus#26]
Hello, I have two questions. Is there a way to force everyone to have PVP on all the time? Do these mods allow a stable server with 50 players? 

I want to set up a server with 50 max for my group but I have not heard of anyone actually seeing that work yet

**Comment by Gee19** [comment]
+1 to this, it could make for very interesting public servers where PvP is force enabled after X amount of days.

**Comment by cschar** [comment]
This would be super fun to set up with 20 people... is this feature hard to implement?

**Comment by Thondargg** [comment]
So far i am having no issues with it, i just send a mod pack to everyone i
play with, they install it, and bam we are all good to go. The small gang
wars have escalated quickly!

**Comment by nxPublic** [comment]
We are working on our own PVP addition to Valheim Plus. More on this soon!
