### ISSUE TITLE
[BUG]StaminaUsage on tools only applies to native actions

### ISSUE THREAD

**Issue by astemus** [valheimPlus/ValheimPlus#260]
- OS: Windows Client
- Valheim Game Version: 0.147.3
 - Mod Version: 0.9.4

**Describe the bug**
I'm having a problem with StaminaUsage, set it to true, and set any tool to -100, but I still drain stamina while sprinting and jumping. Previously, I had it set so hammer was unlimited stamina, but now it only reduces the hammer usage like repair and building. Was this an intentional change?

**To Reproduce**
To reproduce, simply set any StaminaUsage to -100 and while holding that tool, sprint or jump.

**Expected behavior**
Previously, reducing StaminaUsage applied to all actions while holding that tool, including sprint and jump.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

[StaminaUsage]
; Change false to true to enable this section
enabled=true
; Each of these values modifies the stamina drain by %.
; The value 50 would result in 50% more stamina cost.
; The value -50 would result in 50% less stamina cost.
axes=-100
blocking=-100
bows=-100
clubs=-100
knives=-100
pickaxes=-100
polearms=-100
spears=-100
swords=-100
unarmed=-100
hammer=-100
hoe=-100
cultivator=-100

**Additional context**
This may not be a bug but an intended design decision, in which case I can tell my players so, and move on from there. If this is the case, it would be nice to have an option where one tool eliminated jump/sprint costs as well, though that is a separate issue I can post if so.

**Comment by nxPublic** [comment]
This was a intentional change.
