### ISSUE TITLE
[FEATURE REQUEST] Quick Install/Update Script included in docs?

### ISSUE THREAD

**Issue by JustinGrote** [valheimPlus/ValheimPlus#263]
I made a install/update script here, works for dedicated servers too, maybe include in docs?
https://gist.githubusercontent.com/JustinGrote/f57f021a19c2400e46fb22abcd92609a

**Comment by radmint** [comment]
Thanks @JustinGrote we appreciate the suggestion but we have others working on a manager/install gui that we think will be more helpful.
