### ISSUE TITLE
Lose the negative numbers.

### ISSUE THREAD

**Issue by SiniestroO** [valheimPlus/ValheimPlus#264]
it would be nice to see the negative numbers disappear from the config file...

easily done by using 0% (as none) 100% (as default value) 200% (double), etc..

i used "-100" stamina usage on the hammer, hoe and rake and they still use stamina, i don't know if its a bug or i'm doing it wrong.

also the config file is confusing at times in the way the descriptions are explained, and it should have the default and original values in every line you can change in the description so for people that wan't to have a balanced experience and tweak the cfg 100 times can tweak the cfg at will without losing the original value.

thanks.

**Comment by KairuByte** [comment]
You're assuming the lowest should be 0%?

If I set it to -200 I _gain_ stamina instead of losing it.

**Comment by SiniestroO** [comment]
> You're assuming the lowest should be 0%?
> 
> If I set it to -200 I _gain_ stamina instead of losing it.

you shouldn't....that's the point... negative numbers don't work well here, like i said in the OP i set stamina usage of tools to -100 and still they use stamina when it shouldn't.

if 100% stamina is de default value and you set 50% it should cost 50% less stamina to use the tool... if you set 0% .. well...none, and if you set 200% it would cost double the stamina....easy, simple, concise.

**Comment by KairuByte** [comment]
Except some servers may want to regain stamina when doing specific things. That's my point.

*Your* use case wants 0% to be the minimum, but I might want to require users to run around to regain stamina, in order to be able to swing their sword.

Just because it doesn't make sense to you, doesn't mean it's an invalid use case.

That said, if -100 does not currently work to reduce usage to 0, I'd say that's a bug as it's obviously not working as intended.

**Comment by SiniestroO** [comment]
> Except some servers may want to regain stamina when doing specific things. That's my point.
> 
> _Your_ use case wants 0% to be the minimum, but I might want to require users to run around to regain stamina, in order to be able to swing their sword.
> 
> Just because it doesn't make sense to you, doesn't mean it's an invalid use case.
> 
> That said, if -100 does not currently work to reduce usage to 0, I'd say that's a bug as it's obviously not working as intended.

it don't make any sense anything you are saying, sorry....maybe is that English is my second language or maybe i'm not explaining myself correctly.

if you set to 0% it shouldn't use ANY stamina, this means that you will retain you full bar of stamina when using a weapon/tool if you set it to 0%.... (there are other mods that do this and work perfectly fine, in fact i was using those mods cause Val Plus didn't work correctly.)

**Comment by KairuByte** [comment]
But if I _specifically_ want to regain stamina when running, it's not possible without negatives.

It _should_ be possible to regain stamina, for servers to do weird events and such.

**Comment by SiniestroO** [comment]
> But if I _specifically_ want to regain stamina when running, it's not possible without negatives.
> 
> It _should_ be possible to regain stamina, for servers to do weird events and such.

you shouldn't use ANY stamina whatsoever using the tools... that's the point. you won't lose ANY so you don't have to regain ANY not even running or jumping...

**Comment by beerik94** [comment]
He is telling you that some servers might setup it up that you lose stamina except for when you block an attack with a shield and you gain stamina when you do that.
You never know what people want to have on their server so we have to account for every option.
