### ISSUE TITLE
[BUG] Chests randomly losing "ownership"

### ISSUE THREAD

**Issue by cblack-f3** [valheimPlus/ValheimPlus#265]
- OS: Windows Client
- Valheim Game Version: Latest
 - Mod Version: 0.9.4 (has occurred before on 0.9,x)

**Describe the bug**
Some chests have randomly become inaccessible.  Logfile shows:
```
[Info   : Unity Log] 03/06/2021 13:44:27: Player 1084757880 wants to open piece_chest_wood(Clone)   im: 1084757880
[Info   : Unity Log] 03/06/2021 13:44:27:   but im not the owner
```
There are no wards on this server yet, I am the only one here.  This happened before, so I just destroyed the chest with a sword then rebuilt.

Please let me know if anything else would be useful for debugging

**Link to pastebin client cfg file (https://pastebin.com/C6UHhxfS)**

**Link to pastebin server cfg (https://pastebin.com/zwRETcfK)**

**Comment by radmint** [comment]
@cblack-f3 please add the https://pastebin.com link to your cfg otherwise we won't know what settings to check to see if we can reproduce the error.

**Comment by cblack-f3** [comment]
I was not sure if that meant the "server" or the "client" cfg.. in any case I have never touched that file so its what is in the release.

Updated OP to include it

**Comment by xiaodoudou** [comment]
@cblack-f3 did you use AdvancedEditingMode on that chest?
Seems on your config file only the enabled section is the [Server] section, could you provide your server config?

**Comment by phatal808** [comment]
This would explain something odd that happened to me yesterday.  I had 4 across and 2 tall cubby of chests setup.  2 of the chests I could no longer access.  I tried breaking everything supporting the 2 chests and they would not fall or break either.  I don't use the advanced editing modes client side or server side.  This was before the recent update so I'll give you my config from last.
[valheim_plus.zip](https://github.com/valheimPlus/ValheimPlus/files/6096793/valheim_plus.zip)

**Comment by radmint** [comment]
@phatal808 please use pastebin for sharing your .cfg. @cblack-f3 are you using any other mods?

**Comment by cblack-f3** [comment]
I am asking my bud for the server config file.

In the meantime, this is what I do for a workaround: Aim at object, hit numpad 0 (default edit key), then immediately numpad enter to end edit mode.  FYI these chests were not placed or edited with AEM/ABM previous to the issue

**Comment by cblack-f3** [comment]
OK I've added the cfg file from server to OP: https://pastebin.com/zwRETcfK

**Comment by cblack-f3** [comment]
Sorry missed the last part of your question - no other mods.

**Comment by nxPublic** [comment]
I don't think we really now what could cause this issue, its most likely a game issue in general. We also had no other reports of this happening that i know of.

**Comment by Freigeist** [comment]
> I don't think we really now what could cause this issue, its most likely a game issue in general. We also had no other reports of this happening that i know of.

I think I can confirm it's a game issue, I had this happen a few times in the unmodded game too.

**Comment by healiha** [comment]
Some more info here: ownership in that case refere to who is hosting the current area, not who the chest was created by.
When you're not able to open a chest, it's because of resync/latency issue.
When's player want to open a chest and he's not the host of the current area, it will ask the hosting player (first one present in it) if he can open the chest. When the dataRate limite has been reached it will cause long waiting time until the chest can actually be opened.
