### ISSUE TITLE
Torches and Item Despawn

### ISSUE THREAD

**Issue by VikingStocky** [valheimPlus/ValheimPlus#267]
Item despawn is not working for me.
Items is on.
Dropped Item On Ground duration 7200.

GPortal, Plus 9.4

Also, I have not been able to set torches to not need fuel, but fireplaces still need fuel.
I tried all combinations, no luck.
Is there a correct combination, or not possible?

**Comment by radmint** [comment]
Thanks for submitting @VikingStocky please re-submit with the bug template filled out otherwise we cannot track the cause of your problem.
