### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Loivado** [valheimPlus/ValheimPlus#268]
- OS: Windows Server
- Valheim Game Version 0.147.3
- Mod Version 0.9.3
 
**Describe the bug**
The mill only fits in 20 barley and you can't change it in the config

**To Reproduce**
1. Have a Valheim Server 
2. Move save file to Valheim+ Server
3. Try to put in barley into the mill
4. Step 1 and 2 could be optional, I think it's for all servers.

**Expected behavior**
- The mill can fit 50 barley in
- You could change the input behaviour in the config (I couldn't find anything related to the mill)

**Troubleshooting**
none known

**Screenshots**
![2021-03-06 23_05_31-Valheim](https://user-images.githubusercontent.com/22766892/110222226-014cb100-7ed1-11eb-825d-7003f4bfd445.png)

**Link to [pastebin](https://pastebin.com/mbVmbjf3):**

**Additional context**
Fandom wiki Valheim about mills: https://valheim.fandom.com/wiki/Windmill

**Comment by radmint** [comment]
@Loivado please use the "Feature request" template for this and re-submit.
