### ISSUE TITLE
Workbench radius not working past 50mts

### ISSUE THREAD

**Issue by SiniestroO** [valheimPlus/ValheimPlus#270]
- OS: [Windows Client]
- Valheim Game Version [latest]
 - Mod Version [0.9.4]

**Describe the bug**
workbench radius not passing the 50mts.

**To Reproduce**
changing "workbenchRange" to more than 50mts not working

**Expected behavior**
more than 50mts

**Troubleshooting**
increasing it to more than 100 didn't work either.

**Comment by VikingStocky** [comment]
Mine works at 60

**Comment by SiniestroO** [comment]
> Mine works at 60

mine doesn't, but it worked at 80 in the 0.9.2 version, didn't check in 3 but definitely not working on .4 for me.

**Comment by SiniestroO** [comment]
nevermind... apparently a typo somewhere disabled the entire cfg file not a single function was working i had to re donwload everything and configure it again.
