### ISSUE TITLE
[FEATURE REQUEST] Mill Improvement - Get back to 50 capacity

### ISSUE THREAD

**Issue by Loivado** [valheimPlus/ValheimPlus#271]
**Description**
See closed bug here: https://github.com/valheimPlus/ValheimPlus/issues/268
After switching to Valheim+ the mill only fits in 20 barley and you can't change it in the config. It's weird to not have the vanilla capacity although you can't change it.
The vanilla mill fits 50 barley as also stated in the fandom wiki: https://valheim.fandom.com/wiki/Windmill

It seems that something is already interacting with the mill capacity(?)
It would be good to have atleast the vanilla 50 capacity or a number you can change as for the furnace and kiln. 

**Describe the solution you'd like**
Have a block in the config to change the mill input capacity:

[Mill]
; Change false to true to enable this section
enabled=true
; Maximum amount of barley in a mill
maximumBarley=50

**Comment by xiaodoudou** [comment]
It is more a bug; related to the smelter as a Windmill are both are linked in terms of the code base of Valheim.
I believe it needs a check on `m_windmill` property.
