### ISSUE TITLE
[FEATURE REQUEST] disable ping on login

### ISSUE THREAD

**Issue by tlane13** [valheimPlus/ValheimPlus#273]
Sometimes I'd like to have a secret base location, especially on a more pvp oriented server. The ping that happens when you log in can accidentally reveal the location of your base. 

It would be nice to have a feature to disable this ping from happening when logging in. 

```
[Map]

; Change false to true to enable this section
enabled=false

; With this enabled your location will not be broadcasted to other players when you login
dontPingLocationOnLogin=false
```

**Comment by nxPublic** [comment]
This is on our to do list.

**Comment by mdcohen** [comment]
Dude go to bed.

**Comment by nxPublic** [comment]
This has been added for 0.9.7
