### ISSUE TITLE
Auto snap on 

### ISSUE THREAD

**Issue by execpanda** [valheimPlus/ValheimPlus#274]
Someway to auto lock things onto things. Like auto snap a bed onto a cart or boat. Im planning on having a RP Viking funeral and id liek to set the boat off into the sunset with the person laying on the bad(as if dead)  as in the provided link. Would this be possible?https://imgur.com/a/LqrjtD8

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Building as "Lock Items Together".
