### ISSUE TITLE
[BUG] Windmill and Spin Wheel bugged capacity (-4)

### ISSUE THREAD

**Issue by Rocco1987** [valheimPlus/ValheimPlus#275]
- OS: Windows Client, Linux Server (zaphosting)
- Valheim Game Version current
 - Mod Version 094

**Describe the bug**
Unable to use windmill or spinning wheel in single player and multiplayer. Capacity is -4

**To Reproduce**
Unable to determine what caused the issue. seemed to be working in 093

**Expected behavior**
To put items in the crafting tools to produce expected items.

**Troubleshooting**
I've tried disabling auto chest pickup for kiln and furnace. which is the only config line I modified since my 093 config.

https://pastebin.com/tyWm0Sd8

**Comment by radmint** [comment]
I think this is your issue @Rocco1987. Though the kiln configuration shouldn't be applying to non-kiln "Smelters" so I'm going to make a change for that. Closing this as resolved.
![image](https://user-images.githubusercontent.com/23347804/110247809-e99e1880-7f22-11eb-8e8e-43b3e639907c.png)
