### ISSUE TITLE
[FEATURE REQUEST] Shield block power, parry tuning and block chance

### ISSUE THREAD

**Issue by Zerville** [valheimPlus/ValheimPlus#278]
To make The difficulty scaling (hard mode) more doable The shield block needs a pretty big buff. 
So a possibility to modify shield block power would be very nice. 

Perhaps also making parrying having a scalable modification on stamina loss depending on block skill and a bigger block power bonus than block itself. 

Also thinking of a "reflex" like an automatic block chance depending on your block skill. Without actually having your shield in shield mode as long as it is equipped in your hand. 

These features from top to bottom priority order. 

Thanks for a really great mod for this game!

**Comment by shilliash** [comment]
Good input. I would say that mobs "staggered chance" should be changed - currently it is 100% chance for that on succesful parry. 

Idealy it should be dependant on blocking skill + size of shield + tier of shield. It would make tower shields / serpent shield useable at least on harder mobs - currently they are pretty useless if you ask me.

Even simple modification when stagger has % chance to trigger on succesful parry (70-100%) would be pretty nice for a start on top of things you've mentioned.

**Comment by nxPublic** [comment]
We have added a shield block rating multiplier that can be adjusted to your liking in 0.9.5. I think everything beyond that would go to deep into adding new content/mechanics to the game that we are not quite ready for yet.
