### ISSUE TITLE
[BUG] 0 Fuel Torch even when freshly crafted

### ISSUE THREAD

**Issue by yakunique** [valheimPlus/ValheimPlus#280]
- OS: Windows 10
- Valheim Game Version 0.147.3
 - Mod Version 0.9.4
 - I've been hosting the room for me and my friends. Normal non dedicated room.

Torch now have 0 fuel even when freshly crafted. It just started happening since yesterday and now neither me nor my friends are able to have a Filled Torch. Crafting or spawning it still gives a 0 fuel torch in our inventory.

I was thinking maybe the Fireplace options in the cfg might be the cause but I disabled both by changing them to False and the issue is still here.

My valheim_plus.cfg pastbin here [pastebin](https://pastebin.com/b0dwwkEG)

I'm honestly not sure if the mod or the game is the issue though and am hoping someone can help us out here. Thanks!

**Comment by radmint** [comment]
Thanks for the report @yakunique, we are aware of this issue and have a fix for it in the upcoming release

**Comment by yakunique** [comment]
> Thanks for the report @yakunique, we are aware of this issue and have a fix for it in the upcoming release

Sweet! Looking forward. Great job with the mod by the way, definitely makes the game much more enjoyable.

**Comment by fbda** [comment]
6 days ago... the 0.9.5 have the same "bug". Is there a solution nearby????

**Comment by fbda** [comment]
btw: absolut awesome and great Job with the mod!!!!!! Donation is ready :)

**Comment by yakunique** [comment]
> 6 days ago... the 0.9.5 have the same "bug". Is there a solution nearby????

0.9.5 was only released 9 hours ago actually. I've just updated my client and servers and it's been fixed :)
