### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ahnguyen09** [valheimPlus/ValheimPlus#283]
Windows 10 Pro. 2004 (Build 19041.804) 
Valheim Game Version: 0.147.3
V+ Mod Version: 0.9.4

**Describe the bug**
Unable to drag and drop assembly and got an error publicizing post-processing.

**To Reproduce**
1. Download the assembly publicizer  https://mega.nz/file/oQxEjCJI#_XPXEjwLfv9zpcF2HRakYzepMwaUXflA9txxhx4tACA
2. Extract the zip. 
3. Drag and drop the "assembly_*." on the publicizer.exe. 
    - This does nothing for me. The .exe console just disappears. I had to use cmd prompt to run the publicizer on the DLL
       "AssemblyPublicizer.exe assembly_googleanalytics.dll".
4. Running: "AssemblyPublicizer.exe assembly_postprocessing.dll". Generates and error:
   "ERROR! Cannot create/overwrite the new assembly. Please check the path and its permissions and in case of overwriting 
    existing file ensure that it isn't currently used." 
    - The publicized DLL is created with 0 kb. I have tried cmd with admin and in other folders with no luck.

Enhancement to contributing MD:
- The first step is a little vague: 
   "Unzip the denikson BepInEx then copy the contents of "denikson-BepInExPack_Valheim-5.4.701\BepInExPack_Valheim" to 
    Steam's "steamapp\common\Valhiem" root" 
   I have mistakenly copied(extracted) the entire BepInExPack_Valheim folder to Valhiem root

**Comment by radmint** [comment]
Updated CONTRIBUTING.MD for clarity
