### ISSUE TITLE
[Feature request] Repairs require materials

### ISSUE THREAD

**Issue by shilliash** [valheimPlus/ValheimPlus#287]
As subjected it would add a little bit of realism to the repair process for armors/weapons/tools/boats. Perhaps repairing structures as well. 

There is such a standalone mod already : [https://www.nexusmods.com/valheim/mods/215?tab=description](url)
Not sure if algorithm author is using there is not to harsh and can turn game into excessive farm fest. 

I would say there should be an option to set by server side the amount of materials necessary to fix an item with some server side option i.e:

- fixed cost of 10% of base craft (for level 1 item irrespective of item level)
- 20% 
- 30%

All in all we are fixing an item that exist - in mentioned mod 100% dmg = craft new item - items does not desintegrate in game so that solution is a bit weird at least to me.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Items as "Repairs require materials".
