### ISSUE TITLE
all options enabled by default

### ISSUE THREAD

**Issue by SiniestroO** [valheimPlus/ValheimPlus#292]
i would like to see all the options available enabled by default, doing this will mean most of the common "problems" people have (because they didn't set the master string to enable the whole section) gone... it should be enabled and with the default original values set by default so we can change what we need to change and leave the rest as is without questioning ourselves if you enabled the section to begin with.

maybe just use the "true" "false" strings to enable mods outside the game like ABM, etc.

also, plenty of the options offered in this mod are not the default values, like for example the inventory part... i lost my final tier armor just for trying and disableing that string just because i wanted the items just to be stored from top to bottom.

thanks.

**Comment by ShammyLevva** [comment]
In my opinion this is an actively bad idea. Far better that the server owner (or solo player) chooses to enable features they wish to have on their server and that the default is the vanilla game.

**Comment by SiniestroO** [comment]
> In my opinion this is an actively bad idea. Far better that the server owner (or solo player) chooses to enable features they wish to have on their server and that the default is the vanilla game.

if you have the default options you shouldn't have to disable anything, only the things that are not from the game....in 7 days to die, you have the config at your disposal and you can change whatever you want without having a parent section.

besides like i said, everything that's on the VP config file are 99% from the game changes and 1% things that don't come in the game... so why i have to "true" a parent section just to enable no cost stamina on a hoe? it doesn't make any sense, i've moded lots of games and tweaked lots of config files and i never seen this type of activation for a section unless is something that doesn't come in the game like "ABM".

i see this mod and i compare it with the cfg file from 7 days to die (same engine) even tho 7 days to die has 1000 lines more its easier to configure cause you don't need to change one option to change another.

the same thing happens to the negative numbers and percentages, never seen percentage usage be so convoluted in a config file than this and lots of people are having problems because of this.

it should be more easy.... because this mod eventually will have a cfg file with close to 1000 lines at this rate, believe me on that.

**Comment by SiniestroO** [comment]
the title of the post should say all options enabled/disabled by default not just enabled... my bad.

**Comment by radmint** [comment]
Thanks for the suggestion @SiniestroO. We know that the .cfg format isn't perfect and we're working on what a better solution looks like but for now this is not a solution that we would consider for the following reasons:

1. it would be a communications headache to users and hosting providers to explain why everything appears as enabled by default now. 
2. For users who only use a couple of features, they would have to now turn everything else off just to use one feature
3. By checking for an `enabled` value, we decide whether or not to do extra methods calls, network calls, set ups, etc. For example, if ABM is enabled then we have to do a LOT more set up than just running a regular "build" method.

I appreciate the suggestion and, like I said, we know it's not a perfect system but this isn't something we can do within our current processes.
