### ISSUE TITLE
unarmed damage multiplier broken?

### ISSUE THREAD

**Issue by SiniestroO** [valheimPlus/ValheimPlus#293]
- **OS:** [Windows Client]
- **Valheim Game Version:** [latest]
- **V+ Mod Version:** [0.9.4.]

**Describe the bug**

baseUnarmedDamage at 120 lets me one hit lots low level mobs, even some high level ones, i can one shot Greydwarf Brute's with my bear hands.

i'm lvl 30 on unarmed damage... i don't think this is supposed to work like this.

**Expected behavior**

not one shot enemies with 150+ hp with your hands unless you have like 50+ levels on that skill.

**Comment by mattyteds** [comment]
What is your unarmed skill level?

**Comment by SiniestroO** [comment]
> What is your unarmed skill level? Are you running any other mods that effect skill level or damage? Are you connecting to a server or running a local game? I have this set to the default 120 and don't do much unarmed damage.

no other mods, no, i don't play on a server...my level is 30 or so...i hit 90 to a pig for example, i don't know i didn't really tested it properly but once i one shoted a greydwarf and i thought it was to much so i halfed the value.

**Comment by mattyteds** [comment]
It was probably a crit...

**Comment by SiniestroO** [comment]
> It was probably a crit...

https://youtu.be/KcQ_YW0XKME

if this seems normal... then i will keep leveling my unarmed skill so i can kill the last boss easy.

**Comment by nxPublic** [comment]
Please state your skill level in unarmed and your post your http://pastebin.com valheim_plus.cfg

**Comment by SiniestroO** [comment]
> Please state your skill level in unarmed and your post your http://pastebin.com valheim_plus.cfg

i clearly stated that i'm lvl 30 and the value for unarmed damage is the default 120

**Comment by nxPublic** [comment]
We offer the Configuration files values for a basic guidance when there is no default value to resort to. The base unarmed damage is a value that has been put there by a rough estimate. If you think its to high, please let us know a more suitable default value to resort to and I will make sure we ship future versions of V+ with that value.

The current code for it is:
```c#
CharacterPlayerInstance.GetSkillFactor(Skills.SkillType.Unarmed) * Configuration.Current.Player.baseUnarmedDamage;
```

**Comment by SiniestroO** [comment]
> We offer the Configuration files values for a basic guidance when there is no default value to resort to. The base unarmed damage is a value that has been put there by a rough estimate. If you think its to high, please let us know a more suitable default value to resort to and I will make sure we ship future versions of V+ with that value.
> (Feel free to mention a different math equation as well.)
> 
> The current code for it is:
> 
> ```cs
> CharacterPlayerInstance.GetSkillFactor(Skills.SkillType.Unarmed) * Configuration.Current.Player.baseUnarmedDamage;
> 
> // SkillFactor is skill level / 100
> ```

i tried with 60 after seeing this for the first time and i though it was more in line to what i was used to in the original game before you implemented this option... i know also that bare hands can never beat weapons unless you have the iron fists.

**Comment by nxPublic** [comment]
I have noted this change for 0.9.6 and will make sure to find a suiting equation.

**Comment by highwaybobbery** [comment]
I found at lvl 48 skill that a value of 10 for the mod was fairly close, but for low skill level it's very low. Is it possible to have the code determine what the damage would be unmodded first, and apply this setting as a percentage increase instead?
