### ISSUE TITLE
[BUG] Server halts on Ubuntu 18.04 Initialization

### ISSUE THREAD

**Issue by Troctor** [valheimPlus/ValheimPlus#298]
- **OS:** Ubuntu 18.04 x64
- **Valheim Game Version:** [0.147.3]
- **V+ Mod Version:** 0.9.3-0.9.4

**Describe the bug**

Error is thrown on fresh steam version (default mod settings) leading to server halting before startup,

`[Info   : Unity Log] Version generated with enforced mod : 0.147.3@0.9.4
Version generated with enforced mod : 0.147.3@0.9.4 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
 
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Int32.Parse (System.String s) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
FejdStartup.ParseServerArguments () (at <bf9bd142b7c04f32b4e15d64d8018201>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Awake>(FejdStartup)
 
FormatException: Input string was not in a correct format.
  at System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) [0x00057] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00013] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Int32.Parse (System.String s) [0x00007] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at FejdStartup.ParseServerArguments () [0x000b8] in <bf9bd142b7c04f32b4e15d64d8018201>:0 
  at (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Awake>(FejdStartup)
 `

**To Reproduce**

Install valheimplus to a valheim server running on ubuntu 18.04, no settings modified from default configurations.

**Expected behavior**

Server to start with default settings

**Troubleshooting**

What steps have you taken to try to fix?

Cleared file sources entirely and attempted with default settings

**Additional context**

This bug first occurred in 0.93

**Comment by DanielLavrushin** [comment]
I think I have pretty much the same issue (ubuntu 20.04).

After starting a server (valheim+ 0.9.4) the server stop responding after a while -  the only possible way to get it back is to reboot phisically.

**Comment by X3ph1s** [comment]
Issue Resolved!!!

Adjust your servers startup arguments. Mine used to be "./start_server_bepinex.sh -nographics -batchmode -name "{{SERVER_NAME}}" -port {{SERVER_PORT}} -world "{{WORLD}}" -password "{{PASSWORD}}" > >(sed -uE "{{FILTER}}") & trap "{{STOP}}" 15; wait $!"

Now it is simply "./start_server_bepinex.sh -nographics -batchmode" The .sh script handles the rest of the arguments.

Hope this helps, credit to @Riotline in the V plus Discord.

![unknown](https://user-images.githubusercontent.com/40482291/111056845-2f814200-8437-11eb-92af-77cb25659448.png)

**Comment by Riotline** [comment]
It would seem certain methods of parameter inputs don't like certain formatting. Potentially encoding text or maybe port needs to be inputted as a string. But as stated by the person who mentioned me, I bypassed it by placing the config for startup in the script rather than through the parameters. It is fine for small use cases but if it's run on panels or non-supported managers then it may be a problem.

**Comment by Mixone-FinallyHere** [comment]
This bug does not come from our mod, but rather bepinex or vanilla game
