### ISSUE TITLE
[BUG] disableDamageToPlayerStructures disables Structural Integrity Damage & Affects Boats

### ISSUE THREAD

**Issue by sharkzu** [valheimPlus/ValheimPlus#299]
- **OS:** [Windows Client / Server]
- **Valheim Game Version:** [Latest]
- **V+ Mod Version:** [0.9.4]

**Describe the bug**

disableDamageToPlayerStructures is causing stability damage to be turned off, and is also permitting players to build floating bases due to this. The above option, disableStructuralIntegrity is sat to false. This is also taking effect on boats. NPCs such as the Sea Serpent can't break/damage boats which makes venturing into the ocean a breeze.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Go to your 'valheim_plus' file.
2. Find the [StructuralIntegrity] portion of the config.
3. Enable the Section, then turn disableDamageToPlayerStructures to True.
4. Log back into the game and begin building upwards without supports. You'll see that the building pieces will fall.
5. Take any boat type out into the sea and encounter a Sea Serpent. You'll notice your boat never takes damage.

**Expected behavior**

There should be a configurable list here for what kinds of damages are blocked/allowed when this option is enabled. That way you can control if stability should damage it, if NPCs damage it, if other players can damage it, or if owners can damage their own stuff. For instance, with this option enabled? NPCs aren't damaging boats or structures during events. You should be able to control that. It could look something like this:

disableEnvironmentalDamageToPlayerStructures=true
disableNPCDamageToPlayerStructures=true
disableDamageToSelfOwnedStructures=true
disableOtherPlayerDamageToPlayerStructures=true

disableEnvironmentalDamageToBoats=true
disableNPCDamageToBoats=true
disableOtherPlayerDamageToPlayerStructures=true
disableDamageToSelfOwnedBoats=true

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/ir89z48j

**Additional context**

Please revisit the types of structures covered by this ruling too. Individualize it, offer a blacklist maybe, or a whitelist.

**Comment by nxPublic** [comment]
PR #329 addressed this issue sufficiently for the moment.
