### ISSUE TITLE
Valheim Windows Installer

### ISSUE THREAD

**Issue by CastBlacKing** [valheimPlus/ValheimPlus#323]
# Windows Installer
Hello, today I created a windows installer for Valheim Plus, I believe it is easier for windows users to use it to install Valheim Plus instead of manually moving the files to the root folder of the game.

Many users do not have much knowledge and can have a lot of difficulty to install a MOD in Valheim, then, I created this installer that unlike the known installers its only function is, in a clean way, to install Valheim Plus.

The project repository is public and the project can be changed by anyone, this installer can be adapted to install other versions of Valheim Plus, such as the one I made which installs [my version of V+](https://github.com/Valheim-Brasil/VPlus-Brasil) for my players in the [Brazilian Valheim community](https://github.com/Valheim-Brasil/InstaladorVPlus).

We can add the download link to the installer in the README.md of the project for those who want to use it. Or add it somewhere else, on an official website or on something like that.

## Links
If you want to access the project or the installer, here is the link

Repository: https://github.com/CastBlacKing/ValheimPlus-Installer
First Release: https://github.com/CastBlacKing/ValheimPlus-Installer/releases/tag/1.0.0

**Comment by CastBlacKing** [comment]
# Interface

### Automatic default directory detection
![Detecção automática](https://i.imgur.com/dr4pzGW.png)

### Directory selection and detection of Valheim.exe
![Escolha de diretório](https://i.imgur.com/Escliwt.png)

### Install/Uninstall/Update Options
![Opções](https://i.imgur.com/2eoMmaR.png)

**Comment by nxPublic** [comment]
I am not really sure what to do with this.

Feel free to contact me on discord if you want to discuss any kind of implementation or mentions in the mod descriptions.
