### ISSUE TITLE
[FEATURE REQUEST]Package plugin only

### ISSUE THREAD

**Issue by spannerman79** [valheimPlus/ValheimPlus#324]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

_Did a search for "plugin" on issues, reviewed those, none were similiar to my suggestion._

**Is your feature request related to a problem? If so, please describe.**
Awhile ago over on the nexus you did package just the plugin alone. As there is https://github.com/U-1F31A/BepInEx_Valheim_Full your current packages inlude the older BePinEx files.

**Describe the solution you'd like**
If possible package just the mod and config in the Assets of https://github.com/valheimPlus/ValheimPlus/releases/latest

**Additional context**
I'm using a docker container that is adding modding support for Valheim - see https://github.com/mbround18/valheim-docker

Right now using [BepInExPackFull](https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full/) and automating adding in V+ is an issue (see https://github.com/mbround18/valheim-docker/issues/272#issuecomment-796501039 for further context)

**Comment by nxPublic** [comment]
I will make sure to add that from 0.9.5 onwards.

**Comment by spannerman79** [comment]
Thank you @nxPublic - it is _greatly_ appreciated.
