### ISSUE TITLE
dataRate config request

### ISSUE THREAD

**Issue by ChobitsCrazy** [valheimPlus/ValheimPlus#327]
Hello thank you for the great mod! 

I'd like to request to separate the dataRate config from the Server settings and maybe have that option be disabled independently of the other options. I've recently found a guide to improve dedicated server lag by adjusted the m_dataPerSec in the assembly_valheim.dll file. However it appears that this setting may be overwriting that adjustment.

Link to the reddit guide: https://www.reddit.com/r/valheim/comments/lkea78/valheim_dedicated_server_lag/

Thank you again!

**Comment by Mustache84** [comment]
Bump ^^ I'd like to ++ this FR. It looks like the dll implementation might be a better fix than the in-mod implementation.

**Comment by oliver4888** [comment]
The `dataRate` config option changes the `m_dataPerSec` for you as shown below, so you don't need to edit the dll yourself https://github.com/valheimPlus/ValheimPlus/blob/1076e599ee43d17821ab92587816edd708108b13/ValheimPlus/GameClasses/ZDOMan.cs#L19

**Comment by radmint** [comment]
What @oliver4888 said is correct, V+ has the functionality to overwrite the m_dataPerSec with the dataRate config. Unless I'm misunderstanding your ask?

**Comment by ChobitsCrazy** [comment]
Correct, my request is to have the server/client side be separate from each other.

The guide states to have the server set as a higher number than the clients. i.e. server set to 368640 (6x normal) and the clients should be set to 245760 (4x normal). In this case the client and server would be set the same. Also we utilize the forced shared cfg file so having them different would cause the Incompatible Version error (to my understanding).

The other (maybe simpler) option would be to have this feature disabled independently from the other [server] settings in the cfg.

**Comment by spannerman79** [comment]
One possible suggestion is that its split into two.  One for server, one for client.

That way the need to modify the dll for two different values (one for server, one for client) isn't needed, easier for people to manage.

So for https://github.com/valheimPlus/ValheimPlus/blob/development/valheim_plus.cfg#L436..L437 it would be two values, for example;

`server_dataRate` could be applied only to the server and `client_dataRate` is the setting to apply to the client.  Now only `client_dataRate` would be synced forced to the connecting client.

I'm not even sure that could be done but it is a though.

**Comment by nxPublic** [comment]
This function has been retired for now.
