### ISSUE TITLE
Extra durability calculation

### ISSUE THREAD

**Issue by ChobitsCrazy** [valheimPlus/ValheimPlus#328]
- **OS:** Win Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.4

**Describe the bug**

I set, under [Durability], axes=50. I checked the durability of the base Flint Axe (100) default and it shows as now 151.

**To Reproduce**

Install V+ 0.9.4
Set config option under [Durability] axes=50
crafted Flint Axe and saw 151 durability

**Expected behavior**

Would expect to see 150 durability

**Troubleshooting**
Setting back to 0 changes it to normal 100

**Comment by nxPublic** [comment]
This is intentional. It has to do with how we apply the modifier values and how we divide the float values.
