### ISSUE TITLE
[FEATURE REQUEST] Regenerate Crypts/Burials/Troll Caves

### ISSUE THREAD

**Issue by sharkzu** [valheimPlus/ValheimPlus#330]
**Is your feature request related to a problem? If so, please describe.**
While the map is vast in the world of Valheim, my players are finding it slightly frustrating that most of the troll caves/crypts/burials have been depleted on the entry island. It would be a great addition to V+ if there was a way to replenish these!

**Describe the solution you'd like**
An option in the config file to set a regeneration timer for these items, such as:

[Regenerating Dungeons]
Enabled=True
SecondsBetweenRegeneratingTrollCaves=86400
SecondsBetweenRegeneratingBurials=86400
SecondsBetweenRegeneratingSunkenCrypts=86400

**Comment by Nage3000** [comment]
This is a major issue for server admins, like myself. We are growing and have around 20 members, and we are running out of real estate and resources very quickly. Without the ability to reset ore nodes, crypts, caves, and a bunch of other important features, the only option we'll have left is to completely reset the server, losing all the amazing buildings we've created. Would love to see this built out!

**Comment by sharkzu** [comment]
> This is a major issue for server admins, like myself. We are growing and have around 20 members, and we are running out of real estate and resources very quickly. Without the ability to reset ore nodes, crypts, caves, and a bunch of other important features, the only option we'll have left is to completely reset the server, losing all the amazing buildings we've created. Would love to see this built out!

Agreed! We have about 50-100 players in and out each day on ours and the massive towns people are building, and community hotspots near our altar? It'd be devastating to wipe the map. I really hope they can make this happen! There's a reason they're called ValheimPlus ;)

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under General as "Respawn System for Caves and Dungeons".
