### ISSUE TITLE
[FEATURE REQUEST] Roads (worked ground) increases movement speed and decreases stamina usage

### ISSUE THREAD

**Issue by Skrumpy** [valheimPlus/ValheimPlus#333]
Deleted, do not want to participate in support of a childish narcissist.

**Comment by Skrumpy** [comment]
Grow up nx.

**Comment by nxPublic** [comment]
I don't know man, isn't that a little much to call me childish narcissist for telling you to stop posting bug-reports in our alpha bug report channel without explicitly stating what other mods you are using when reporting them?
