### ISSUE TITLE
[BUG] auto-deposit of smelter/kiln favoring carts when there is a closer chest available

### ISSUE THREAD

**Issue by Zxurian** [valheimPlus/ValheimPlus#337]
- **OS:** Linux Server
- **Valheim Game Version:** `0.147.3@0.9.4`
- **V+ Mod Version:** `0.9.4`

**Describe the bug**
When the kiln & smelter are set to auto deposit, and a chest is next to the building, but a cart is further away, the smelter & kiln are putting items into the cart storage, instead of the closer chest.

**To Reproduce**
Steps for the devs to reproduce the behavior:
1) Build kiln/smelter
2) place chest right next to kiln/smelter
3) put cart further away
4) load kiln/smelter
5) see items be put into cart instead of closest chest.

**Expected behavior**
Based on the configuration description, 
> Instead of dropping the items, they will be placed inside nearby chests instead.
it seems to imply that it will be placed in the nearest chest (could be wrong)

**Troubleshooting**
Tried putting chests at various distances away, it always favors the cart unless I physically move the cart outside the range of the smelter/kiln.
With the screenshot below, you can see the distance between the kiln & the cart, even though there is a chest right next to the kiln, produced coal is being deposited into the cart.

**Screenshots**
![image](https://user-images.githubusercontent.com/573371/111014021-cc78a800-836f-11eb-8105-a55480429b1f.png)

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/q9BhM57n

**Additional context**
no other mods installed.

**Comment by nxPublic** [comment]
This is fixed in 0.9.5
