### ISSUE TITLE
[BUG] System.NullReferenceException: at ValheimPlus.GameClasses.PlayerPositionWatcher.Postfix

### ISSUE THREAD

**Issue by Jtuo** [valheimPlus/ValheimPlus#340]
- **OS:** Linux Server
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5

**Describe the bug**

Since the latest update submitted a few hours ago, the server log has started filling (repeating every two seconds, or so) with the following exception:

```
valheim    | 03/13/2021 14:04:50: Exception in ZRpc::HandlePackage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
valheim    |   at ValheimPlus.GameClasses.PlayerPositionWatcher.Postfix (ZNet& __instance, ZRpc rpc, UnityEngine.Vector3 pos, System.Boolean publicRefPos) [0x000b4] in <2484e5959d8c4ffea68a83b9325bd0d3>:0
valheim    |   at (wrapper dynamic-method) ZNet.DMD<ZNet::RPC_RefPos>(ZNet,ZRpc,UnityEngine.Vector3,bool)
valheim    |   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
valheim    |   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0
valheim    |    --- End of inner exception stack trace ---
valheim    |   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <eae584ce26bc40229c1b1aa476bfa589>:0
valheim    |   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0
valheim    |   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <eae584ce26bc40229c1b1aa476bfa589>:0
valheim    |   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <eae584ce26bc40229c1b1aa476bfa589>:0
valheim    |   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0
valheim    |   at ZRpc+RpcMethod`2[T,U].Invoke (ZRpc rpc, ZPackage pkg) [0x0001d] in <bf9bd142b7c04f32b4e15d64d8018201>:0
valheim    |   at ZRpc.HandlePackage (ZPackage package) [0x00042] in <bf9bd142b7c04f32b4e15d64d8018201>:0
valheim    |   at ZRpc.Update (System.Single dt) [0x0001e] in <bf9bd142b7c04f32b4e15d64d8018201>:0
```

The game seemingly runs fine otherwise. Maybe this needs some investigation? Perhaps related: [commit](https://github.com/valheimPlus/ValheimPlus/commit/37c6e94281164f88625846d1350dbf4d0830a573#diff-6cc0e30c2d44ecf4ecd21c0ca3e903f217e079501161199a47947dcd4e5ab1ca)

I am using the latest docker container from [here](https://github.com/lloesche/valheim-server-docker).

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Start the server
2. Join the server
3. Observe server logs

**Expected behavior**

No errors

**Troubleshooting**

Restarting, verifying server files

**Screenshots**

**Link to [pastebin](https://pastebin.com/raw/MeK2Ydwz) containing .cfg configuration**

**Additional context**

No other modifications

**Comment by WiNiFiX** [comment]
Getting same issue, windows server, no docker container

**Comment by Mylorify** [comment]
Got the same problem since updating, also using the docker container from [here](https://github.com/lloesche/valheim-server-docker).

**Comment by willdotcom** [comment]
i have the same error on Window Server.

**Comment by willdotcom** [comment]
Everyone, the issue is fixed on recent update: https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.5.5
Regards

**Comment by Jtuo** [comment]
> Everyone, the issue is fixed on recent update: https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.5.5
> Regards

I can confirm this, the error seems to be gone - I'll close the issue.
