### ISSUE TITLE
Bad substitution unix game lauch script

### ISSUE THREAD

**Issue by Dark-Schnitzel** [valheimPlus/ValheimPlus#341]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- Kubuntu 20.10
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- 0.147.3
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]
- produced in 0.9.5 seems to affect other versions too: https://github.com/valheimPlus/ValheimPlus/issues/180

**Describe the bug**
the start_game_bepinex returns bad substitution on line 35.

This is due to executing with /bin/sh, line 35 is a bash function. Not on every system /bin/sh points to bash, you need to edit the interpreter on line 1 to /usr/bin/bash or /usr/bin/env bash.

**Comment by nxPublic** [comment]
This has been addressed for 0.9.6 release

**Comment by mdcohen** [comment]
Yea I’ll hop on board and take care of everything.
