### ISSUE TITLE
Fire Source Bugged again

### ISSUE THREAD

**Issue by VikingStocky** [valheimPlus/ValheimPlus#342]
Windows Client
V+ 9.5
GPortal Server

Torches & Fireplaces bugged again.

With fire source on and torches only off, only half the torches light, and fireplaces aren't working either
With fire source on and torches only on, same thing, only half the torches work, and fireplaces aren't working either.

Do we have to add fuel again? Is it old torches only?
Will test again throughout day.

**Comment by radmint** [comment]
@VikingStocky are these newly placed torches/fire sources or already existing ones?

**Comment by VikingStocky** [comment]
I will have an answer for you later.

Figuring it out now.

I have quite a few lights.
![20210311152502_1](https://user-images.githubusercontent.com/80178026/111035094-c1149380-83e6-11eb-9e7d-edcbc75cae14.jpg)

**Comment by radmint** [comment]
fuel has to be added to existing torches/fire sources first per readme:
![image](https://user-images.githubusercontent.com/23347804/111035119-c74a4600-83cd-11eb-81cb-27d2771ab37b.png)

**Comment by VikingStocky** [comment]
Thank you. I will test this now, and add fuel.

I will post an answer afterwards.

**Comment by VikingStocky** [comment]
I have added 1 fuel to all torches and fireplaces.
Waiting to see if timer runs out.
Hard for me to know if they were old ones, or new ones, since I have so many.
Do I have to replace the old ones, or just add fuel?
![Untitled](https://user-images.githubusercontent.com/80178026/111035838-3f266980-83ea-11eb-8a8a-a19360487838.png)

**Comment by VikingStocky** [comment]
Quick update.

GPortal Server settings are Fireplaces = On, Torches Only = Off.
Client settings are default.

I added 1 wood to the fireplaces an hour ago.
Fireplaces have gone out. These were old fireplaces.

Waiting to see if new fireplaces go out, and waiting on the verdict for the torches.

**Comment by VikingStocky** [comment]
New fireplaces have gone out as well. I added them yesterday.

**Comment by VikingStocky** [comment]
Wait, GPortal just updated.

Will start tests over again.

**Comment by fbda** [comment]
What are the settings to get the torches fuel?

**Comment by nialna** [comment]
I got the same issue, can't find any settings combination that keeps them on

**Comment by VikingStocky** [comment]
Seems to be working now, for me.

**Comment by Alienpope** [comment]
0.9.5.5, this stopped working for me since going from 0.9.4, both new and old fireplaces/torches. If someone knows a way to make this work, do tell :)

**Comment by Corgano** [comment]
On the latest version on steam (installed today) with the latest version of  valheim plus.
`[Fireplace]
; If changed to enabled all fireplaces do not need to be refilled.
enabled=true
onlyTorches=false`
Fireplaces still burn out, even if refilled. Torches seem to last forever though.

**Comment by Topside08** [comment]
In the 9.5.5 config [Fireplace] is changed to [FireSource]
If you server host is recycling the old config it could explain the issue there as well

**Comment by Alienpope** [comment]
> In the 9.5.5 config [Fireplace] is changed to [FireSource]
> If you server host is recycling the old config it could explain the issue there as well

Ah! Good to know! Using a server provider so I'll let them know of the issue. Not a bug then probably
