### ISSUE TITLE
[BUG] Config category duplicate?

### ISSUE THREAD

**Issue by ahnguyen09** [valheimPlus/ValheimPlus#346]
This is for the Windows Zip of the latest V+: 0.9.5
The valhiem_plus.cfg specifically.

**Describe the bug**
The config has both "furnace and smelter". This might be there for backward compatibility, however, it looks weird. Are we suppose to fill out both?
`[Smelter]

; Change false to true to enable this section
enabled=true

; Maximum amount of ore in a smelter
maximumOre=20

; Maximum amount of coal in a smelter
maximumCoal=20

; The total amount of coal used to produce a single smelted ingot.
coalUsedPerProduct=1

; The time it takes for the smelter to produce a single ingot in seconds.
productionSpeed=10

; Instead of dropping the items, they will be placed inside nearby chests instead.
autoDeposit=false

; The range of the chest detection for the auto deposit feature. (Maximum is 50)
autoDepositRange=10

[Furnace]

; Change false to true to enable this section
enabled=true

; Maximum amount of ore in a furnace
maximumOre=20

; Maximum amount of coal in a furnace
maximumCoal=20

; The total amount of coal used to produce a single smelted ingot.
coalUsedPerProduct=1

; The time it takes for the furnace to produce a single ingot in seconds.
productionSpeed=10

; Instead of dropping the items, they will be placed inside nearby chests instead.
autoDeposit=false

; The range of the chest detection for the auto deposit feature. (Maximum is 50)
autoDepositRange=10`

**Comment by highwaybobbery** [comment]
Looks like the [Smelter] section is new, not sure if it [Furnace] is still referenced anywhere.

**Comment by christanplaza** [comment]
Maybe furnace is referring to Blast Furnace?

**Comment by ahnguyen09** [comment]
You guys are correct. It looks like the smelter.cs has been updated to account for kiln, blast furnace, and smelter.  
It seems like the new section is meant to allow you to control all 3 with only one config. 

So keep Kiln and furnace false and just change under smelter and it should be good. I tested it but it does NOT seem to work that way.
