### ISSUE TITLE
[BUG] Gravestone does not contain additional inventory rows

### ISSUE THREAD

**Issue by reneg1990** [valheimPlus/ValheimPlus#347]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
Latest version Linux Server + Windows Client

- **Valheim Game Version:** [e.g. 0.4.11, etc]
Latest version

- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]
0.9.5 update from a good 7 hours ago.

**Describe the bug**

When you die and go back to collect your items, your gravestone does no longer have additional inventory space.
So if you have i.e 6 rows of space, your gravestone only has the original 4 rows.

I downgraded to 0.9.4 to test, in this version your gravestone shares the inventory space/rows properly.

**Expected behavior**

Expected behaviour is that the gravestone should have the same amount of rows as the player inventory. Currently you lose every single item that is exceeding the "space in the gravestone" compared to your inventory.

**Comment by VikingStocky** [comment]
I just tested this, since this would be a major bug.

My corpse has the same amount of columns & rows, as my inventory.

Mine is set to 5 rows instead of the default 4.

**Comment by reneg1990** [comment]
I wonder if its specific to 6 Rows, we use 6 rows on the server I run and have the issue there.

All mods we're using is Valheim Plus and Epic Loot. We still get the issue without Epic Loot. Only happens on 9.5. Works fine on 9.4.

I just tried to test again and we have the issue when its set to 6 rows. I see quite a few people reported that today over at nexusmods too.

**Comment by reneg1990** [comment]
I can inform that it seems to be a case where you need to "browse" the items from your corpse. If u have under weight limit, it auto gets added to your inventory (including whats in the "extra rows", but if u exceed weight limits and it has you browse the items (the option where u can click "take all" etc), thats where the items have dissapeared and not showed up.

**Comment by garybrain** [comment]
I had the problem today, we set the server to 6 rows and I placed the armour, belt and wishbone on the bottom row. Was killed in the plains by a Goblin and when I ran back to the corpse I did a run past as I know I did not need to use the "take all" button. When I was at a safe distance the bottom row was empty. Tested it again with a resin in the bottom row and a friend killed me. He looked at the corpse and it only showed 4 rows.

**Comment by VikingStocky** [comment]
Just happened to me now as well. I have 5 rows set.
Lost everything in my bottom row.

**Comment by joklbash** [comment]
Same here with 6 rows set. First 3 rows had inventory, 4th and 5th empty, 6th row had stuff in it. Died (re-died?) and lost bottom row.

**Comment by Zerville** [comment]
Im using gravekeeper mod and it takes care of this issue

**Comment by nxPublic** [comment]
This issue should be fixed in 0.9.5.5
