### ISSUE TITLE
[Feature Request] Increase game difficulty

### ISSUE THREAD

**Issue by GuilhermeFaga** [valheimPlus/ValheimPlus#35]
You can overgear every boss, end game makes goblins be mere pawns and deathsquitos mere flys. It would be cool to make it harder to add a bit of challange.

**Comment by mephasor** [comment]
You can simply use the regular console commands. 
https://steamcommunity.com/sharedfiles/filedetails/?id=2392080520&searchtext=item

**Comment by larssn** [comment]
> You can simply use the regular console commands.
> https://steamcommunity.com/sharedfiles/filedetails/?id=2392080520&searchtext=item

You're talking about the `players` command? If so that makes enemies damage sponges, which is not fun.

**Comment by mephasor** [comment]
I did. If not increase the amount of damage a boss can take, you are talking about adding mechanics to the bosses?

**Comment by GuilhermeFaga** [comment]
The `players` command isn't appropriate to make to game more difficult to only one person, to double the enemy damage you have to make their health 10x higher. But could be the inverse, to double the enemy health, it's damage would increase 10x.

**Comment by nxPublic** [comment]
We will be making more stuff in the future to be able to turn the game in both directions, easy and hard.

```ini
[Game]

; Change false to true to enable this section
enabled=false

; The games damage multiplier per person nearby in difficultyScaleRange(m) radius.
gameDifficultyDamageScale=0.4

; The games health multiplier per person nearby in difficultyScaleRange(m) radius.
gameDifficultyHealthScale=0.4 

; Adds additional players to the difficulty calculation in multiplayer unrelated to the actual amount
extraPlayerCountNearby=0

; Sets the nearby player count always to this value + extraPlayerCountNearby
setFixedPlayerCountTo=0

; The interval in seconds that the game auto saves at (client only)
autoSaveInterval=1200

; The range in meters at which other players count towards nearby players for the difficulty scale
difficultyScaleRange=200
```

Is added for 0.8.5 and should allow for a little more tweaking for now.
