### ISSUE TITLE
[FEATURE REQUEST] Reduce fall damage taken

### ISSUE THREAD

**Issue by ocgineer** [valheimPlus/ValheimPlus#350]
An option to reduce the fall damage taken (by %) would be a nice addition. Died quite a few times by just simply walking off the roof after building and just dying after food buffs ran out.

**Comment by exscape** [comment]
Implemented as of alpha 0.9.7C (or perhaps the previous alpha). Should be in the sharp 0.9.7 release. :)  
#466
