### ISSUE TITLE
Error Exception in ZRpc::HandlePackage:

### ISSUE THREAD

**Issue by willdotcom** [valheimPlus/ValheimPlus#351]
- **OS:** Windows
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5

**Describe the bug**

I just updated the server and after turning it on it started throwing this error every second when someone connects.

**To Reproduce**

When he enters the player he starts throwing that error on the console every second.

**Screenshots**

https://i.imgur.com/PDiP7yf.png

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/vbi5qUx5

**Comment by Jtuo** [comment]
This is the same issue [I have](https://github.com/valheimPlus/ValheimPlus/issues/340)

**Comment by jpgoularts** [comment]
@willdotcom did you manage to solve this?
