### ISSUE TITLE
[BUG] Structural integrity mod fails if players join with out mods

### ISSUE THREAD

**Issue by shall-zdata** [valheimPlus/ValheimPlus#352]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**

If you turn off structure integrity buildings. And join the server with a character without the mods installed the building will fall.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1.  Install valheimplus
3. [StructuralIntegrity]

; Change false to true to enable this section
enabled=true

; Disables the entire structural integrity system and allows for placement in free air, does not prevent building damage.
disableStructuralIntegrity=true
3. Log in with player without modifications
4. Go near a building it will fall. 

**Expected behavior**
Building should stay in tack per server setting

**Comment by nxPublic** [comment]
There is nothing we can do about this issue. Its the way the game works.
