### ISSUE TITLE
[BUG] Mouse Scroll Up in AEM Mode also zooms in

### ISSUE THREAD

**Issue by kjack9** [valheimPlus/ValheimPlus#353]
- **OS:** Windows Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5

**Describe the bug**
When I edit an item with AEM mode and scroll up to turn the item, my camera also zooms in.  Scroll wheel down does not have the same issue.  Does not happen in any other mode.

**To Reproduce**
1. Edit an item with AEM mode
2. Scroll up

**Expected behavior**
Zoom in/out should be disabled during AEM mode.

**Troubleshooting**
Happens with first person mode enabled or disabled in the config file.

**Additional context**
No other mods installed.  V+ is installed on both the Windows client and the Ubuntu dedicated server.  No other players are connected.

**Comment by nxPublic** [comment]
I was not able to reproduce this issue.
