### ISSUE TITLE
[FEATURE REQUEST] Clearing Inventories On Join

### ISSUE THREAD

**Issue by darkrunnerirl** [valheimPlus/ValheimPlus#355]
A major problem right now with the base game is that inventories are stored by character and not by world/server. Since you can hop between singleplayer and multiplayer worlds, and console commands are allowed to be used in singleplayer, griefing has become a major issue. Players can spawn in items such as the Cheat Sword and wreak havoc on unprepared servers and moderation teams. This is why almost all servers are whitelisted right now, as it is the only (though very ineffective) way of dealing with potential griefers. 

ValheimPlus should give a config option that wipes somebody's inventory upon joining a new world or server. This would entirely solve the griefing issue as no longer would people be able to spawn in items on their own worlds and bring them to multiplayer worlds - ValheimPlus' server side config can be forced upon players. 

Though it would pose some annoying instances where somebody's hard work is instantly deleted as they forgot about such a rule, the benefits massively outweigh the downsides. Servers are rather inaccessible right now because one must apply individually to each server to be accepted onto the whitelist, and an option like this would remove the necessity of whitelists. Imagine Minecraft but instead of being allowed to hop onto a server you first had to go to their Discord server and apply - not fun.

**Comment by healiha** [comment]
I hardly doubt this is a good idea.

#75 will address this issue in a more appropriate way.

**Comment by darkrunnerirl** [comment]
> I hardly doubt this is a good idea.
> 
> #75 will address this issue in a more appropriate way.

yea that's probably better but daily reminder this is literally you
![4863386](https://user-images.githubusercontent.com/80544971/111055687-ab36bb00-8446-11eb-9a07-80134998affd.jpg)

**Comment by nxPublic** [comment]
> I hardly doubt this is a good idea.
> 
> #75 will address this issue in a more appropriate way.

We are still on that! Thank you for remembering!

**Comment by ShammyLevva** [comment]
Doesn't seem like a good idea as even a simple disconnect would mean you reconnect and you'd lose everything. Even logging off for the night you'd lose everything next time you logged into that world the next day. There would be no way to tell if this was a "new world" or not without storing data server side thus it would be far better to store the character data server side as suggested in item #75.
