### ISSUE TITLE
[BUG] object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by thomas-barthelemy** [valheimPlus/ValheimPlus#362]
- **OS:** [Linux Server / Ubuntu]
- **Valheim Game Version:** [0.147.3]
- **V+ Mod Version:** [0.9.5.5]

**Describe the bug**

Unix server is no longer starting with Valheim+

Showing error:
`
./start_server_bepinex.sh: line 91: ./linux64:/home/ubuntu/Steam/doorstop_libs:: No such file or directory
ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
`

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Setup latest Valheim & Valheim+
2. run start_server_bepinex.sh

**Expected behavior**

Bepinex/Valheim+ should be loading

**Troubleshooting**

Reverting the following change fixed the problem for me:
https://github.com/valheimPlus/ValheimPlus/commit/66f3d837dcba6d2d036ae5c4e3a089b37c01d65b#diff-a99cd68aa61335a9b8dcb070b94a90e2b9801634931e1e3028fc7f3cd8876e18

I am aware this change may fix a problem for some, but it seems to be breaking for some others.

**Comment by X3ph1s** [comment]
Paste this back to line 91 of server_start_bepinex.sh 

LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH

This will revert it back to 9.5 version before the hotfix and it will run.

**Comment by Zxurian** [comment]
should be fixed with #378 path changes. Has already been merged and should be in next release.
