### ISSUE TITLE
OS: Windows Server

### ISSUE THREAD

**Issue by Tukarius** [valheimPlus/ValheimPlus#363]
- **OS:* Windows Server
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

When I start my game my character appearance is different, name is the same and server name is the same.

I get a red error on the console game will start and shake and not let me move giving red error over and over on console. Will see if I can attach screenshots here.

**To Reproduce**

Steps for the devs to reproduce the behavior:

**Expected behavior**

**Troubleshooting**

What steps have you taken to try to fix?

**Screenshots**
![c3EzihFs1j](https://user-images.githubusercontent.com/80606968/111054346-26897400-8429-11eb-8309-32a8e7254300.png)
![xEcjDtk8US](https://user-images.githubusercontent.com/80606968/111054349-30ab7280-8429-11eb-922d-14ca062bc994.png)

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by Mixone-FinallyHere** [comment]
Duplicate #361
