### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kilowaste** [valheimPlus/ValheimPlus#364]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [0.147.3]
- **V+ Mod Version:** [0.9.5.5.]

**Describe the bug**

A clear and concise description of what the bug is and how you found it.
Same bug after installing 0.9.5.5, new characters joingin server will bug, lose all starting armor. I believe it is the info bird spawning too close to the character when loading in. Causes this same character glitch

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Go to 'make a new character'
2. Click on 'join server'
3. Spawn into game

**Comment by EASYUK-DarrenWhite** [comment]
nxPublic commented 15 hours ago
We uploaded a new version for 0.9.5.5, redownload. It should be fixed now. Sorry about the inconveniences.

**Comment by kilowaste** [comment]
I am running 0.9.5.5 and still getting the issue
