### ISSUE TITLE
[FEATURE REQUEST] Time of day

### ISSUE THREAD

**Issue by Lizzardd** [valheimPlus/ValheimPlus#365]
Would be great to have a time of day clock displayed on the hud.
This one exists, but either doesn't work or isn't compatible with V+
https://www.nexusmods.com/valheim/mods/85

**Comment by ShammyLevva** [comment]
That Clock mod works fine on my install, maybe you didn't install the pre-requisites? Agreed though it would be nice to see that rolled into Plus.

**Comment by VikingStocky** [comment]
I agree. V+ has everything I need, except an in game clock.

I'd prefer not to download other Mods at this time.

I'll wait for V+ to add it. I'm sure they will eventually.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Hud as "In-game Clock".
