### ISSUE TITLE
[FEATURE REQUEST] Chat Options

### ISSUE THREAD

**Issue by sharkzu** [valheimPlus/ValheimPlus#366]
It would be nice to have the option for multiple chat rooms, such as Global Chat, Region-Based Chats, Area Chats, etc. Even Trade or LFG Chats!

**Configuration File Examples (sort of!)**
EnableGlobalChat=true
EnableAreaChat=true
EnableTradeChat=true
EnableLFGChat=true
EnableRPChat=true
EnableRegionChat=true
- Plains=true
- Meadows=true
- BlackForest=true
- Mountains=true
- Ashlands=true
- Mistlands=true
- DeepNorth=true
- Swamp=true

**Additional Stuff**
The chat commands could be something like:
/g <-- Global
/lfg <-- Looking for Group
/trade <-- Trade
/a <-- Area
/sw <-- Swamp
/mt <-- Mountains
/p <-- Plains
/bf <-- Black Forest
/dn <-- Deep North
/ml <-- Mistlands
/al <-- Ashlands
/m <-- Meadows

**Comment by nxPublic** [comment]
We added something similar with 0.9.9.6, we might extend upon what we added but this goes beyond the scope of V+ focus on quality of life.
