### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Orohal** [valheimPlus/ValheimPlus#367]
- **OS:** Windows Client and Linux Server]

- **V+ Mod Version:** 0.9.5.5, hotfix
**Describe the bug**

After updating Linux Server and Client, i become the Message 
Incompatible version

All Files are uptodate.

BeepinEx say´s:

[Info   : Unity Log] Version generator started.
[Info   : Unity Log] Version generated with enforced mod : 0.147.3@0.9.5.5
[Info   : Unity Log] 03/14/2021 09:30:07: Got connectoin error msg ErrorVersion

[Info   : Unity Log] 03/14/2021 09:30:07: Lost connection to server:ErrorVersion
witch side is worng? server or client?

**Comment by EASYUK-DarrenWhite** [comment]
update both server and client using the correct files

**Comment by Orohal** [comment]
> update both server and client using the correct files
its look like Bug #370
all files are uptodate. 
useless hint.

**Comment by EASYUK-DarrenWhite** [comment]
A complete lack of information and an attitude like that will get you far.  Good luck fixing it on your own.

**Comment by Mixone-FinallyHere** [comment]
#378
