### ISSUE TITLE
CONTRIBUTING.md unclear

### ISSUE THREAD

**Issue by Kattoor** [valheimPlus/ValheimPlus#368]
I just checked out the project via git and read the CONTRIBUTING.md file to get started.
It seems the environment setup steps don't cover everything.

Quite a few assemblies were missing from the project.
After taking a look at ValheimPlus.csproj, I noticed the missing DLLs were expected to be in Valheim/valheim_Data/Managed, but they were in Valheim/unstripped_corlib.

Copying the DLLs from Valheim/unstripped_corlib to Valheim/valheim_Data/Managed did the trick.

However, step two mentions loading the assemblies from Valheim/unstripped_corlib into dnSpy.
This makes me think I didn't have to move the missing assemblies from Valheim/unstripped_corlib to Valheim/valheim_Data/Managed, but instead I should have linked my IDE to Valheim/unstripped_corlib for the missing assemblies?

**Comment by ahnguyen09** [comment]
Yeah, I have not successfully built the latest project yet. I have no experience with modding so I also require more in-depth help to building the project.

Here are something I did to remove the missing assembly references.

- Have you tried using NuGet to update your packages? When I did this a bunch of the references showed up correctly.
- Only the Unity assembly was left. Something about Unity.Accessibility and much more. I download Unity 2020 for the latest set of assembly. (well I also tried 2018, and 2019). Unity 2018 is missing something with DSL graph.
- I search the unity install and drag the missing assemblies into the references
- My project still cannot find the definition for Input.GetKeyUp. Then I gave up again.

If you get it to build, please share.

**Comment by Kattoor** [comment]
Input.GetKeyUp was indeed one of the missing references.

To be able to build the project, you'll have to copy the DLLs from Valheim/unstripped_corlib to Valheim/valheim_Data/Managed.

**Comment by ahnguyen09** [comment]
@Kattoor Thanks! I'll try it again.

**Comment by ahnguyen09** [comment]
@Kattoor Thanks again!! it builds!!
I did a fresh load from github.

- I copied files from unstripped core lib to valhiem data manage.
- Updated my NuGet in VS  
- Successfully builds.

**Comment by Kattoor** [comment]
Happy I could help! As I'm not used to this tech stack, I had to do some digging earlier today :p
I'm not sure whether this is the way to go, or the other solution I described in my issue at the top.

**Comment by Dfluke** [comment]
I haven't gotten around to setting up an environment myself yet either. Good find, I'm sure you've saved me some time!

> However, step two mentions loading the assemblies from Valheim/unstripped_corlib into dnSpy.
This makes me think I didn't have to move the missing assemblies from Valheim/unstripped_corlib to Valheim/valheim_Data/Managed, but instead I should have linked my IDE to Valheim/unstripped_corlib for the missing assemblies?

The dnSpy steps are a recent addition... I wonder, how anyone was able to build the project who was onboarding, with these steps being a fairly new addition. I looked thru the CONTRIBUTING.md file history, and there were no instructions related to Valheim/unstripped_corlib in the past.

Perhaps, there is more here than re-arranging instructions, or stating that the dnSpy setup steps explicitly are required before building?

**Comment by ahnguyen09** [comment]
Yeah I just recently figured out how to use dnSpy. 

- File Close All to reset all of the assemblies based on the just unzipping.
- Follow the dnSpy step from ValhiemPlus Github up until debug and just select exe.
- By default the debug engine is .NET framework, HOWEVER, I changed it to Unity then the breakpoint worked.
    - Make sure steam is running or you get an error Valhiem just closes

**Comment by npenney** [comment]
I believe the missing DLLs were removed in the last patch for Valheim. They appear to be in the managed folder for the older version, but do not exist if you do a fresh install. I messaged nx about it a few days ago but he hasn't gotten back to me about it yet.

**Comment by nxPublic** [comment]
I will update the CONTRIBUTING.md tomorrow with all required changes.

Sorry for the inconveniences!

**Comment by nxPublic** [comment]
Updated.
