### ISSUE TITLE
[BUG] After upgrading from 0.95 to 0.9.5.5, server not reporting correct version

### ISSUE THREAD

**Issue by Zxurian** [valheimPlus/ValheimPlus#370]
- **OS:** Ubuntu LTS 20.04 / Windows 10
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

Previously had `0.9.5` installed as of earlier today and was working. Saw the `0.9.5.5` hotfix was pushed out. After installing, clients are now getting kicked for "Incompatible Version".

Within the console log file from the connection attempt, I can see this
```
03/14/2021 09:35:49: Peer 76561197983774333 has incompatible version, mine:0.147.3 remote 0.147.3@0.9.5.5
```

That tells me that the server isn't reporting the correct version. There have been multiple issues raised regarding incorrect versions already, and I have gone through everything I can think of twice to make sure that everything is the same.
* Verified that only `UnixServer.zip` file was downloaded from from https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.5.5
* new `UnixServer.zip` has been unzipped and overlayed onto existing server files
* verified that within config `[Server] enabled=true` and `[Server] enforceMod=true`
* verified that `WindowsClient.zip` was downloaded to my W10 machine
* server is being started with the `start_server_bepinex.sh`
* server has `libc6-dev` installed and up-to-date

**To Reproduce**

1. Have Valheim `0.147.3` installed with working V+ `0.9.5`.
2. stop server
3. Unzip `UnixServer.zip` `0.9.5.5` in place
4. start server again

clients cannot connect due to incompatible server version, server log show server is reporting version as `0.147.3`

**Expected behavior**

server should report server version as `0.147.3@0.9.5.5`

**Troubleshooting**

* redownloaded UnixServer and overlayed
* verified dependencies are installed

**Screenshots**
n/a

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
Complete server log: https://pastebin.com/HxKnCjQ7 showing startup and attempted connection from my client

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
no other mods installed.
when I upgraded from `0.9.4` to `0.9.5` I did the same thing, stop server, overlay, update config with my changes, then start server, and didn't have any issues. When I did that same process now, the server is now reporting an incorrect verison.

**Comment by Aegesh** [comment]
Same issue here. I think the problem might be on the client-side though. After upgrading to 0.9.5.5 on my Windows client machine, no version number is displayed in the bottom right corner for Valheim Plus.

**Comment by RaulDel-Llano** [comment]
I'm also having the same issue as listed above

**Comment by micahz13** [comment]
Same issue here.

> Same issue here. I think the problem might be on the client-side though. After upgrading to 0.9.5.5 on my Windows client machine, no version number is displayed in the bottom right corner for Valheim Plus. The version info looks as follows on the Windows client machine:
> 
> version 0.147.3
> ValheimPlus
> 
> When rolling back to 0.9.5, the version info looks as follows:
> 
> version 0.147.3
> ValheimPlus **0.9.5**

**Comment by EASYUK-DarrenWhite** [comment]
@Zxurian Looks like the server doesn't have the mod installed as the server list should show server version 0.147.3@0.9.5.5 and the console should show: VERSION check their:0.147.3@0.9.5.5 mine 0.147.3@0.9.5.5.  Also you will need to replace the valheim_plus.cfg file with a backup of your configuration after a server reset

**Comment by Zxurian** [comment]
> @Zxurian Looks like the server doesn't have the mod installed as the server list should show server version 0.147.3@0.9.5.5 and the console should show: VERSION check their:0.147.3@0.9.5.5 mine 0.147.3@0.9.5.5 when someone joins. Also you will need to replace the valheim_plus.cfg file with a backup of your configuration after a server reset

server has been verified as having the mod files unzipped into the correct location, and started with the correct `.sh` file. If running via the `.sh` file isn't actually running Valheim with the mod (resulting in the version without the V+ number), then that would explain it. Do you know how to verify within the logs whether V+ is/isn't running on server start?

> Same issue here. I think the problem might be on the client-side though. After upgrading to 0.9.5.5 on my Windows client machine, no version number is displayed in the bottom right corner for Valheim Plus. The version info looks as follows on the Windows client machine:
> 
> version 0.147.3
> ValheimPlus
> 
> When rolling back to 0.9.5, the version info looks as follows:
> 
> version 0.147.3
> ValheimPlus **0.9.5**

Didn't notice it previously, but can confirm same thing for me. Perhaps the issue where version isn't being reported is affecting both client and server, but on W10 client it still passes the actual version even though it's not reporting it on main menu?

**Comment by cblack-f3** [comment]
Same problem here, I just set up a brand new server 10 minutes ago with latest Server files, and latest client.  No go...

**Comment by thialfi17** [comment]
I ran into the same issue and managed to fix it by rolling back the start_server_bepinex.sh script to the one from 0.9.4. Something about the changes to the LD_LIBRARY_PATH environment variable seems to stop valheim plus from loading correctly.

**Comment by cblack-f3** [comment]
> I ran into the same issue and managed to fix it by rolling back the start_server_bepinex.sh script to the one from 0.9.4. Something about the changes to the LD_LIBRARY_PATH environment variable seems to stop valheim plus from loading correctly.

Old:
```
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
```
0.9.5.5:
```
LD_LIBRARY_PATH=`./linux64:$LD_LIBRARY_PATH` && export LD_LIBRARY_PATH || export LD_LIBRARY_PATH=./linux64:"$LD_LIBRARY_PATH"
```

this difference?

**Comment by Zxurian** [comment]
> > I ran into the same issue and managed to fix it by rolling back the start_server_bepinex.sh script to the one from 0.9.4. Something about the changes to the LD_LIBRARY_PATH environment variable seems to stop valheim plus from loading correctly.
> 
> Old:
> 
> ```
> export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
> ```
> 
> 0.9.5.5:
> 
> ```
> LD_LIBRARY_PATH=`./linux64:$LD_LIBRARY_PATH` && export LD_LIBRARY_PATH || export LD_LIBRARY_PATH=./linux64:"$LD_LIBRARY_PATH"
> ```
> 
> this difference?

can confirm updating this has fixed the server now reporting the correct version. Server asn't actually loading V+ previously (now I know what to look for in the console log to make sure it's running)

I've created a pull request at https://github.com/valheimPlus/ValheimPlus/pull/378 that updates the the `start_server_bepinex.sh` file for fix going forward. If anyone wants to manually download, should work as a drop in replacement for the existing `start_server_bepinex.sh` file.

**Comment by Orohal** [comment]
i can confirm Server rollback to the 0.9.4  start_server_bepinex.sh fix the problem

**Comment by Zxurian** [comment]
#378 has been merged and will fix this bug, so closing this Issue.
