### ISSUE TITLE
[FEATURE REQUEST] Current level of skill with experienceGainedNotifications

### ISSUE THREAD

**Issue by ahnguyen09** [valheimPlus/ValheimPlus#374]
It would nice to have the current level show with the experience gain notification. This helps you check your current skill level quickly.
![image](https://user-images.githubusercontent.com/9020992/111074333-dd810080-84b8-11eb-8a37-3856f6305878.png)

This is just a simple code change in GameClasses Skill.cs:

`
		/// <summary>
		/// Experience gained notifications
		/// Outputs: Level <skill Level> <skill name> [<accumulated experience value>] (<percent to next level>)
		/// </summary>
		private static void Postfix(Skills __instance, Skills.SkillType skillType, float factor = 1f)
		{
			if (Configuration.Current.Hud.IsEnabled && Configuration.Current.Hud.experienceGainedNotifications)
			{
				Skills.Skill skill = __instance.GetSkill(skillType);
				float percent = skill.m_accumulator / (skill.GetNextLevelRequirement() / 100);
				int currentLevel = (int)skill.m_level;
				__instance.m_player.Message(MessageHud.MessageType.TopLeft, "Level " + currentLevel + " " + skill.m_info.m_skill 
					+ " [" + Helper.tFloat(skill.m_accumulator, 2) + "/" + Helper.tFloat(skill.GetNextLevelRequirement(), 2) + "]" 
					+ " (" + Helper.tFloat(percent, 0) + "%)", 0, skill.m_info.m_icon);
			}
		}
`

I am flexible with the formatting but having the current level is the main improvement.

**Comment by nxPublic** [comment]
This has been added since 0.9.6
