### ISSUE TITLE
Sleep Twice

### ISSUE THREAD

**Issue by VikingStocky** [valheimPlus/ValheimPlus#375]
Windows Client 9.5 with Hotfix
GPortal Server

Since 9.5, when I sleep, it sleeps twice. I don't even have to touch a button. Just click on bed, and you can watch 2 days pass by.

Anyone else getting this?

It started yesterday when 9.5 came out.

**Comment by AnExiledDev** [comment]
I'm not able to reproduce on a fresh install, can you put your configuration file (valheim_plus.cfg) on https://pastebin.com/ so I can try to reproduce with the same configuration?

**Comment by VikingStocky** [comment]
It hasn't happened in 2 days, so let's ignore this for now.

Thanks though.
