### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iam-odyssey** [valheimPlus/ValheimPlus#380]
- **OS:** [Windows 10]
- **Valheim Game Version:** [0.147.3]
- **V+ Mod Version:** [9.5.5]

**Describe the bug**

Furnace ore/coal changes aren't applying and are staying at base default values. 

**To Reproduce**

Make furnace changes on the dedicated server to coal/ore limit and see it not apply.

**Expected behavior**

Furnaces go Brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Troubleshooting**
I've tried resetting the config file and rebooting the server before making the changes again and reapplying. Still won't update for me or any of my players. I disabled auto deposit as I thought it might be interfering, no dice.

**Additional context**

Most of my players have rememberip damnit and better UI installed client side.

**Comment by nxPublic** [comment]
Please post your config file, http://pastbin.com

**Comment by Marcinthecloud** [comment]
I am having the same issue as described above - same version as well.

Pastebin link: https://pastebin.com/8WiFeArv

I can see in the log that it does load the config when joining my server: https://pastebin.com/6pzZmjcv - no errors or exceptions in stdout

Note, blastfurnace does inherit these properties but the regular furnace does not. 

We've tried:

- resetting the mod
- toggling the config on/off
- changing the config value

Thanks!

**Comment by healiha** [comment]
@Marcinthecloud 
When 0.9.5 introduced the separation of the configuration relative Smelter and Furnace.

Looking at your config file, the `[Smelter]` section which change the way the regular furnace works isn't enabled and/or configured.

@iam-odyssey it might be the same for you.

Let us know how it goes!

**Comment by Marcinthecloud** [comment]
That's it! Wow I feel silly now. Thank you for your help!
