### ISSUE TITLE
[FEATURE REQUEST] Turning off Event Map Pings

### ISSUE THREAD

**Issue by Dankbudbaker** [valheimPlus/ValheimPlus#381]
So running a 25 player pvp server it would be nice to be able to turn off the raid event map pings. that way it ensures base locations from being leaked and raided. if somehow you get a hud notification but others wont see the red circle from the raid.

**Comment by nxPublic** [comment]
We are working on several PVP specific features in a separate core mod addition for Valheim Plus. This one is on the list.
