### ISSUE TITLE
[FEATURE REQUEST] Shared progress for Co-op playthrough

### ISSUE THREAD

**Issue by meredithdoto** [valheimPlus/ValheimPlus#383]
**Is your feature request related to a problem? If so, please describe.**
When you playing with friend(s) you have to spend time exchanging items before you unlock new recipes from these items. 
You would have to drop new item to your friend(s) or they have to go through all chests, find new items and manually pick them up when they do something else.

**Describe the solution you'd like**
When anybody picks up new item he gets popup message and unlock new recipes and at the same time other players unlock new recipes too and when they get to crafting station they can see new items and their recipes. 

**Additional context**
Player who picks up item
![image](https://user-images.githubusercontent.com/24488182/111152159-ba298480-8590-11eb-9fc2-1efca28b412e.png)
Player who gets shared progress 
![image](https://user-images.githubusercontent.com/24488182/111153425-396b8800-8592-11eb-93fa-c947c5277365.png)

**Comment by nxPublic** [comment]
This is quite the extensive change in terms of required networking to make it work. The amount of work in comparison of the gain is not realistic for us to invest time into.
