### ISSUE TITLE
Workbench prevent spawning

### ISSUE THREAD

**Issue by ChobitsCrazy** [valheimPlus/ValheimPlus#384]
Would like to request to have the option to prevent spawning of Enemies/Creatures and debris/foliage within the workbench range.

I see a lot of deer and necks that spawn within the base as well as wood and flint etc. Would be nice to not have these things spawn within the range of the workbench to help prevent them from starting inside the base walls without having to go through the trouble of building everywhere. (having open dirt/grass fields.

This would aim to include:
Deer and other wildlife
Enemies including Graydwarves
Wood branches, flint, stone
Dandelions and mushrooms

Thank you for creating this mod! and great work so far!

**Comment by ChobitsCrazy** [comment]
Just thought about the last two and may interfere with Planting Plus, not sure of the interaction plans.

**Comment by babodad** [comment]
I think workbenches do already prevent spawning of Enemies/Creatures in vanilla. Does anybody know more details about this mechanism?

**Comment by nxPublic** [comment]
This is already implemented and working in V+ 0.9.5+
