### ISSUE TITLE
[FEATURE REQUEST] Allow repair of all items at base workbench

### ISSUE THREAD

**Issue by greenskye** [valheimPlus/ValheimPlus#385]
Would be nice to have an option to skip/bypass checks for repair eligibility. I.E. repair metal equipment at workbench instead of forge and repair higher level equipment at a level 1 workbench

This would expand on the current auto-repair functionality in V+. Similar feature implemented by this (slightly buggy) mod: https://www.nexusmods.com/valheim/mods/26

**Comment by nxPublic** [comment]
This has been implemented in 0.9.5.

**Comment by ZashIn** [comment]
Only the auto repair of reparable items (for current crafting station) seem to be implemented, but not the option to repair everything at a level 1 workbench!
This would be a great QoL addition to not run to each crafting station (workbench, forge, ...) to repair all items.
Please reopen!

**Comment by AzumattDev** [comment]
Just download [Repair Station](https://thunderstore.io/c/valheim/p/Azumatt/RepairStation/) if you want that immediately.
