### ISSUE TITLE
better default keys for [ABM and AEM]

### ISSUE THREAD

**Issue by SiniestroO** [valheimPlus/ValheimPlus#386]
hi there, i have a better set of default keys for the ABM and AEM modes, this was because i don't have a full key keyboard i have a 60% so... i use these keys and it works perfectly fine, i play with friends that have notebooks and they think that its good too.

[AdvancedBuildingMode]

; Copy the object rotation of the currently selected object in ABM
copyObjectRotation=Home

; Apply the copied object rotation to the currently selected object in ABM
pasteObjectRotation=End

[AdvancedEditingMode]

; Enter the advanced editing mode with this key
enterAdvancedEditingMode=F6

; Reset the object to its original position and rotation
resetAdvancedEditingMode=F7

; Exit the advanced editing mode with this key and reset the object
abortAndExitAdvancedEditingMode=F8

; Confirm the placement of the object and place it
confirmPlacementOfAdvancedEditingMode=Insert

; Copy the object rotation of the currently selected object in AEM
copyObjectRotation=Home

; Apply the copied object rotation to the currently selected object in AEM
pasteObjectRotation=End

thanks.

**Comment by nxPublic** [comment]
I can understand your frustration with the default keys being wonky. When I first introduced these modes I just put my own debug hotkeys as defaults. We are working on a system to no longer sync the defined hotkeys from the server configuration to the client and also on a system to auto update your configuration on updating your V+ version, those things should solve the issue explained here.

**Comment by mdcohen** [comment]
Take it easy, dude.
