### ISSUE TITLE
Advanced Building/Editing Mode Rotation Speed: Translation Inconsistency

### ISSUE THREAD

**Issue by Samsterious** [valheimPlus/ValheimPlus#39]
**Version:** ValheimPlus v0.7C

The rotation speed adjustments appear to affect the translation speeds as well, which is useful but appears to not work consistently in this context. This bug does not appear to affect object rotation. Translating an object in Advanced Building or Editing Mode results in an incorrect offset distance. Moving an object back and forth seems to demonstrate a random offset-error which causes the object to move inconsistently and become misaligned.

There is some modulo-like behavior, which suggests that the internal offset does not match the rendered and final placement offset. This is evidenced by the fact that moving an object back and forth will eventually yield a greater than one-whole-step error; the object will no longer alternate between the initial position and first step, instead alternating between the first and a second step.

This example was performed with a rotation speed of 71.
![test](https://user-images.githubusercontent.com/20689511/108457664-e9660380-7227-11eb-806b-9a8e339109a0.gif)

**Comment by nxPublic** [comment]
Interesting, I will investigate this issue.

**Comment by nxPublic** [comment]
I have found the issue. This will be resolved in a future version.
