### ISSUE TITLE
baseMegingjordBuff=150  issue, 

### ISSUE THREAD

**Issue by jonelbolanos** [valheimPlus/ValheimPlus#390]
baseMegingjordBuff=150 was supposed to add 150 , but it increase 300 instead .. now my base weight is 600 instead of 450,  please confirm thanks

see screenshot

![mejingordge](https://user-images.githubusercontent.com/23066603/111442755-a5412280-8743-11eb-8382-5edc6f48a7a6.PNG)
![image](https://user-images.githubusercontent.com/23066603/111442802-b427d500-8743-11eb-8c96-ed9ab2ddb60d.png)

**Comment by Madnessx9** [comment]
Can confirm, I don't recall enabling this module but I found in game after installing 9.5.5 that we had a carry weight of 600 with the belt upon looking in the config it is set to 150.

**Comment by nxPublic** [comment]
We are aware of this issue.

**Comment by EASYUK-DarrenWhite** [comment]
Personally I don't think it's a bug if you read the wording correctly.  I too assumed it meant how much will the added belt increase your load capacity, but actually it says how much will be ADDED to your belt capacity, which is already at 150.  The only thing that points towards the value being added to your base capacity is in the variable 'baseMegingjordBuff'.  Either way, good point and pleased to see the guys are on it.. Keep up the good work 👯

**Comment by nxPublic** [comment]
This issue has been addressed for 0.9.6
