### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Carly98** [valheimPlus/ValheimPlus#391]
- **OS:** Windows Client (Windows 10), Server (through G-portal)
- **Valheim Game Version:** Unity v2019.4.20.7197120
- **CLR runtime version:** 4.0.30319.42000
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

Server through G-Portal.  I *assume* they keep theirs up to date, but I can not find on it where you can change the buff duration from Boss's, so maybe not (I noticed there is an option for that as of 0.9.5.5. I changed that in the Valheim_Plus.CFG file, and it is working correctly. That was the ONLY thing I changed (different to previous). We have had the chests changed to 8 columns since first activating Valheim_Plus (about 2 weeks ago).  I do not have the old CFG (or install) files.  I just replace every time.

Anyway, bug: All Chests are now at 5 Columns.  Yet in both CFG file (and hubby's) and Server, all chests are set to 8 columns. Hubby lost a lot of materials and isn't happy.  Wants to stop using Valheim_Plus.  :( We both love the options though, it makes the game so much more convenient.

I have checked and re-done both CFG file and Server, and still only 5 Columns will show in the game.  It was fine before I updated to the 0.9.5.5.

**To Reproduce** - I assume just try to change column size, and update to 0.9.5.5., but I have no way to check, as both of us updated our Windows Client side to 0.9.5.5.

Steps for the devs to reproduce the behavior:

**Expected behavior** 

Your chest columns will only stay at 5.

**Troubleshooting**

I have tried to change the server-side settings.  I have restarted computer, and server.  I tried changing server side both with server running and again with server stopped.  I have "saved" the new settings on the server.

**Screenshots**

![image](https://user-images.githubusercontent.com/80799590/111491465-e3b9eb80-8709-11eb-897d-a38f52aabfb6.png)
![image](https://user-images.githubusercontent.com/80799590/111492398-a144de80-870a-11eb-98df-24199b4d320b.png)
![image](https://user-images.githubusercontent.com/80799590/111492873-0c8eb080-870b-11eb-83d3-d767143af9b7.png)

All chests are set to these settings. 8 Columns, 4 Rows.  The rows are correct (in-game).  And the Player Inventory 8 Rows is still correct in-game.  No idea why it won't now let the Columns be 8.

I do not have a picture of the 8 columns.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

I have WeMod installed.  Hubby does not.  Both of us are experiencing this problem, so I would think it couldn't be it.  Plus it only activates cheats for my character.

**Comment by Carly98** [comment]
Changed rows to 5 (on CFG and Server) (previously set to 4), left columns at 8, and it seems to have worked.
![image](https://user-images.githubusercontent.com/80799590/111495608-8e7fd900-870d-11eb-8e34-b1534d016e44.png)

Still, you might want to be aware of this bug.

**Comment by rr222cy** [comment]
Hi!
I can't reproduce this on any of my servers, perhaps it's a GPortal issue and they solved it as you were updating the rows? Also since no cfg-file is provided in your report I can't check for any values being wrong, like for example the enforceMod parameter.
