### ISSUE TITLE
[BUG] Stutter when experienceGainedNotifications notify 

### ISSUE THREAD

**Issue by jonelbolanos** [valheimPlus/ValheimPlus#393]
- **OS:Windows Client, server: gportal** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:0.147.3** [e.g. 0.4.11, etc]
- **V+ Mod Version:0.9.5.5** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**
im reporting on behalf of my friend's issue , he's experiencing Stutter while the "experienceGainedNotifications " notify his progress(just like when you play offline and the auto save of valheim kickoff) not sure if its his computer/laptop problem or theres a known issue like this. 

his pc/laptop spec :
8gb ram
i7 6th gen
GTX 960m
windows 10

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Use any weapons or tools that gains exp 

**Expected behavior**

Stutters when exp notifs appeared 

**Troubleshooting**

we disabled it to fix the issue , 

**Screenshots**

i will try to upload the video he sent to me
https://user-images.githubusercontent.com/23066603/111553465-6b156680-87bf-11eb-8a45-7e99fb47ff96.mp4

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

it was on gportal

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

on my side(my computer) I didnt experience the stutter he mentioned, but we disabled "experienceGainedNotifications " anyway so he can play the game smoothly

**Comment by rr222cy** [comment]
Hi!

I cannot reproduce this issue, do you know if your friend is using any other mods like e.g. BetterUI that also shows experience gained notifications?

**Comment by Mixone-FinallyHere** [comment]
THis is an issue with their computer/graphics card, not a bug of this mod
