### ISSUE TITLE
[BUG] Incompatible Version error after updating to 0.9.5.5 Hotfix

### ISSUE THREAD

**Issue by cassidymichael** [valheimPlus/ValheimPlus#400]
- **OS:** Linux Server, Windows Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

Was using 0.9.4, working fine. Updated to 0.9.5.5. I couldn't find any update instructions so I just:

1. Stopped server
2. Extracted and copied over existing server files (replacing existing). Re-edited config file from scratch and saved.
3. Extracted and copied over existing client files (replacing existing).
4. Started server
5. On login, I got "Incompatible Version" error.

I re-checked my client and server files multiple times to ensure I was using correct ones.

**To Reproduce**

See above.

**Expected behavior**

No version error.

**Troubleshooting**

I was able to resolve this issue by replacing the 0.9.5.5 start_server_bepinex.sh file with the one found here:
https://raw.githubusercontent.com/valheimPlus/ValheimPlus/development/resources/unix/start_server_bepinex.sh

I saw this recommended in the V+ discord.

**Additional context**

I'm using LGSM for Valheim install, stop/start. My vhserver.cfg file has this line added: `executable="./start_server_bepinex.sh"`

**Comment by petermh87** [comment]
Use this start-BepInEx start script instead while they are fixing it

https://raw.githubusercontent.com/valheimPlus/ValheimPlus/development/resources/unix/start_server_bepinex.sh

should work
