### ISSUE TITLE
virus software reports virus in files after download[BUG]

### ISSUE THREAD

**Issue by alninsc** [valheimPlus/ValheimPlus#401]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**

A clear and concise description of what the bug is and how you found it.

**To Reproduce**

Steps for the devs to reproduce the behavior:

**Expected behavior**

**Troubleshooting**

What steps have you taken to try to fix?

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by rr222cy** [comment]
You're not providing any information whatsoever here, which OS, V+ version, AV-software causing this etc. The bug template is there to be used.

**Comment by Mixone-FinallyHere** [comment]
Virus detection software has a tendency to detect mods that use reflection as threats because the same technique used by mod to work, are the ones that hacks can use. This is out of our hands, you can send an email and report it as not a virus, but this is no Bug
