### ISSUE TITLE
[FEATURE REQUEST]  Add option to kiln to burn unwanted items 

### ISSUE THREAD

**Issue by ShammyLevva** [valheimPlus/ValheimPlus#404]
**Is your feature request related to a problem? If so, please describe.**
I'm always frustrated when there are a large number of unwanted objects lying around.

**Describe the solution you'd like**
I'd like a variation on the kiln input that could take items (or a stack of items) from inventory. Then chuck them out as coal - deconstructing things and giving an at least semi useful resource. It would be in line with the realism that many aspects of the game go for, without risking the game breaking aspects people are concerned about, the concern being deconstructing option gives back resources as way of cheating getting ore through portal.

ie: give the kiln a single slot interface (a 1x1 chest if you like, by default perhaps configurable), perhaps accessible by a different keybind, that you drag (ctrl click) an item or stack of items into, it burns them up (could take variable time dependant on item) and chucks out coal (amount of coal could vary on item) at a determined rate per item. So cheapo items could burn at same rate as wood, more complex items could take longer - net effect item is destroyed and you get coal.

**Comment by DogBeatr** [comment]
Great idea!  Conan Exiles has a dismantling station specifically for doing this.  I'm sure Odin is getting tired of me chucking junk into the ocean all the time...lol

**Comment by nxPublic** [comment]
There is enough alternatives for item removal out there now.
