### ISSUE TITLE
Auto Deposit is not depositing into closest chest.

### ISSUE THREAD

**Issue by dpcleve** [valheimPlus/ValheimPlus#405]
- **OS:** Windows Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

Auto deposit from Smelter / Furnace / Beehives does not deposit into the closest chest.  Two bugs:

1. Smelter.cs **spawn** function.  Function does not use the _autoDepositRange_ parameter.  Instead it is hard-coded to use Beehive range.
2. Helper.cs **GetNearbyChests** function.  Function creates, but does not use the _orderedColliders_ variable.  Fix by having foreach statement iterate over _orderedColliders_ instead of _hitColliders_, resulting in the containers being properly sorted by distance.

**Comment by DogBeatr** [comment]
Same here for me.

**Comment by healiha** [comment]
This has been fixed with #388 and will be fixed with next release.
