### ISSUE TITLE
[FEATURE REQUEST] Reset the advancement of enemies when bosses are beaten.

### ISSUE THREAD

**Issue by Nage3000** [valheimPlus/ValheimPlus#407]
**Is your feature request related to a problem? If so, please describe.**
Every time the server completes a boss, the enemies in the Meadows get more difficult. As of now, our server has beaten the 5th boss and Fulings spawn in the Meadows at night. This makes it very difficult for a new and growing server, such as ours, to introduce new players to our server without them bringing in end-game gear. 

**Describe the solution you'd like**
[Enemy Difficulty in Meadows]
Enabled=True
;Pick a level from 0-5 based on the types of enemies and raids you'll be exposed to, regardless of the boss you've beaten.
EnemyLevel=1

**Additional context**
The 0 would represent no bosses beaten, and 5 would represent Yagluth beaten and Fulings spawning in the Meadows. We would still like to maintain the bosses beaten so we have access to their powers, that's why this solution is better than simply a reset on bosses solution. This enemy difficulty feature and solution is the only way an end-game server is viable for new players to that server. Thanks V+ team!

**Comment by nxPublic** [comment]
This is better placed towards Creature Level and Loot Control.
