### ISSUE TITLE
[FEATURE REQUEST] Expanded trader

### ISSUE THREAD

**Issue by Nage3000** [valheimPlus/ValheimPlus#410]
**Is your feature request related to a problem? If so, please describe.**
As an expanded server, we would like to introduce some sort of trader marketplace function. Players could come to Haldor the Merchant, and sell their resources to him at a fluctuating gold price, and others could buy those resources in response. It will be the only way to create a true economy within a server.

**Describe the solution you'd like**
Be able to access Haldor to buy or sell any resource at either a set price created in the config file, or more complexly a fluid gold price in direct relation to how much of a resource is sold or bought (i.e. Age of Empires market building)

**Additional context**
[Better Trader](https://www.nexusmods.com/valheim/mods/433) is currently the only mod on Nexus dealing with this marketplace function. Unfortunately, it seems like the mod is incomplete and slightly buggy.

**Comment by nxPublic** [comment]
#252 Related.

This is a planned feature.
