### ISSUE TITLE
[BUG] Data Rate Max

### ISSUE THREAD

**Issue by RichiCoder1** [valheimPlus/ValheimPlus#411]
- **OS:** Windows Client, Linux Server
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

When increasing the Data Rate, it seems to max out at 128kbps no matter how much higher you set it. I think this is a valheim bug and not a Valheim+ bug, but figured I'd mention it here.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Set `dataRate` to something higher than 128(-ish)
2. Go to an area with area with high data transmission
3. Press F2 and see that dataRate is maxing at 128kbps

**Expected behavior**

Data rate goes up to either server max or internet local max.

**Comment by nxPublic** [comment]
How many people do do you play with ?

**Comment by RichiCoder1** [comment]
Currently around 5, all with the mod installed (enforced & config synced). 90% of the time, the data rate is fine. There are some city and combat situations where we'll sit at that data rate cap for a while though, and updates will get sent many seconds after the action was taken.

**Comment by nxPublic** [comment]
So in any circumstance you encounter the data rate never goes above 128, no matter what you declared in your config file on the server?

**Comment by RichiCoder1** [comment]
Correct. Both Send and Receive will be capped at 128.# no matter how much high the limit is placed. I'm not sure if it's related, but `Failed to send data k_EResultLimitExceeded` tends to occur around the same time which is related to Valheim's data buffering?

**Comment by nxPublic** [comment]
Its related to the steam API and its server behavior and maximum packet size.

If there is a limit now, all of the sudden that caps at 128 kb's. We could potentially find out why and how this is applied and circumvent the restrictions unless they are server side. However, if there is such a hidden restriction, the developers of valheim are responsible for it and we would not feel comfortable going against their decision in this case. I am sure they are working hard on reworking the networking structure already.

**Comment by RichiCoder1** [comment]
That was my though too. I'm hoping they'll improve it such that a higher cap will be unnecessary but I'm wondering if there's a simple artificial fix in the meantime.

**Comment by gnouts** [comment]
It seems Steam patch their API and Valheim took advantage of it in the latest patch from today : 
https://store.steampowered.com/news/app/892970/view/3047221359547604552

Maybe this requires a new test, and hope it's fixed :)

**Comment by nxPublic** [comment]
For now this feature is retired.
