### ISSUE TITLE
[FEATURE REQUEST] Add Cht lang to config file

### ISSUE THREAD

**Issue by ethanjhuang** [valheimPlus/ValheimPlus#412]
Is possible add chinses language to config file?
i can give and help the translation file.

**Comment by nxPublic** [comment]
If you can, it would be great if you can message me on discord or via e-mail contact@valheim.plus so we can arrange everything you need to create translations.

**Comment by nxPublic** [comment]
I am in contact with the person and will try establish and provide a translation to Chinese with his help.
