### ISSUE TITLE
[FEATURE REQUEST] Disable rain/weather

### ISSUE THREAD

**Issue by joklbash** [valheimPlus/ValheimPlus#414]
**Is your feature request related to a problem? If so, please describe.**
Weather in this game can be a real downer. It's dark enough at times that venturing out is a pain. When it rains, I generally log off for a while rather than deal with it. It's cool the first couple times you see it and even when you're out to sea. After 100+ hours of play, it is just a pain to deal with when you're trying to build or just explore around.

**Describe the solution you'd like**
I'd like an option on dedicated server to disable rain or maybe reduce how often it can occur. For me, I'd like to just disable rain and maybe even fog altogether. Others might rather have something like rain not occurring more often than every 7 days or something.

**Additional context**
Single player appears to support changing the weather.

**Comment by DogBeatr** [comment]
This would be the best quality of life addition.  The rain storms for us are fine, it's the fog that is really annoying.  It lasts WAAAAAY too long and happens way too often.

**Comment by nxPublic** [comment]
Messing around in the EnvMan class is a really bad idea, specially for a mod used as much as ours.

We simply cannot fiddle around in that system, its to complex and results in to many issues for other mods.
