### ISSUE TITLE
[BUG] ./start_server_bepinex.sh: 1: ./linux64:/home/server/.steam/steam/steamapps/common/Valheim: not found

### ISSUE THREAD

**Issue by RoyvanEmpel** [valheimPlus/ValheimPlus#419]
- Ubuntu 20.10
- Latest
- Latest (9.5.5.1)

**Describe the bug**
I can't seem to get the valheim plus working in my unix server.

**To Reproduce**
Download unix valheim server, insert the mod, config and start.

**Troubleshooting**
I saw the other bug report with the same error but using that 'fix' only created more errors.

https://pastebin.com/raw/xjf7MBE6

**Comment by nxPublic** [comment]
Try using these files instead of the shipped 0.9.5.5 .sh files for unix.

https://github.com/valheimPlus/ValheimPlus/tree/development/resources/unix

**Comment by RoyvanEmpel** [comment]
Great the error is gone but now it is giving a LOT `could not load` warning/errors. Is this support to happen xD haha?
https://pastebin.com/raw/HhpZwxNm

**Comment by havedill** [comment]
Im not sure if they're _supposed_ to happen, however they've always occured for me and never been an issue.

**Comment by Zxurian** [comment]
@RoyvanEmpel looking at the log, it looks like there's a bad/corrupted path. Can you run `ls -l` from the `/home/server/.steam/debian-installation/steamapps/common/Valheim dedicated server/Mono` directory and post the output?

**Comment by RoyvanEmpel** [comment]
There is no Mono folder there is a MonoBleedingEdge is that what you meant?

```
server@server:~/.steam/debian-installation/steamapps/common/Valheim dedicated server/valheim_server_Data$ ll
total 916748
drwxrwxr-x 6 server server      4096 mrt 22 18:32 ./
drwxrwxr-x 7 server server      4096 mrt 22 19:21 ../
-rwxrwxr-x 1 server server        16 mrt 22 18:32 app.info*
-rwxrwxr-x 1 server server        92 mrt 22 18:32 boot.config*
-rwxrwxr-x 1 server server     83220 mrt 22 18:32 globalgamemanagers*
-rwxrwxr-x 1 server server    154552 mrt 22 18:32 globalgamemanagers.assets*
-rwxrwxr-x 1 server server   6291456 mrt 22 18:32 globalgamemanagers.assets.resS*
-rwxrwxr-x 1 server server      7736 mrt 22 18:32 level0*
-rwxrwxr-x 1 server server    131232 mrt 22 18:32 level0.resS*
-rwxrwxr-x 1 server server  11823280 mrt 22 18:32 level1*
-rwxrwxr-x 1 server server    504616 mrt 22 18:32 level2*
-rwxrwxr-x 1 server server  87138404 mrt 22 18:32 level3*
-rwxrwxr-x 1 server server  28345052 mrt 22 18:32 level4*
-rwxrwxr-x 1 server server    131232 mrt 22 18:32 level4.resS*
drwxrwxr-x 2 server server      4096 mrt 22 18:32 Managed/
drwxrwxr-x 4 server server      4096 mrt 22 18:32 MonoBleedingEdge/
drwxrwxr-x 2 server server      4096 mrt 22 18:32 Plugins/
drwxrwxr-x 2 server server      4096 mrt 22 18:32 Resources/
-rwxrwxr-x 1 server server   7439600 mrt 22 18:32 resources.assets*
-rwxrwxr-x 1 server server  17930240 mrt 22 18:32 resources.assets.resS*
-rwxrwxr-x 1 server server    224380 mrt 22 18:32 sharedassets0.assets*
-rwxrwxr-x 1 server server  47363816 mrt 22 18:32 sharedassets0.assets.resS*
-rwxrwxr-x 1 server server 147477224 mrt 22 18:32 sharedassets1.assets*
-rwxrwxr-x 1 server server  50432680 mrt 22 18:32 sharedassets1.assets.resS*
-rwxrwxr-x 1 server server 522355616 mrt 22 18:32 sharedassets1.resource*
-rwxrwxr-x 1 server server    965544 mrt 22 18:32 sharedassets2.assets*
-rwxrwxr-x 1 server server   6765200 mrt 22 18:32 sharedassets3.assets*
-rwxrwxr-x 1 server server   1918572 mrt 22 18:32 sharedassets3.assets.resS*
-rwxrwxr-x 1 server server    594080 mrt 22 18:32 sharedassets3.resource*
-rwxrwxr-x 1 server server    584500 mrt 22 18:32 sharedassets4.assets*
server@server:~/.steam/debian-installation/steamapps/common/Valheim dedicated server/valheim_server_Data$ cd MonoBleedingEdge/
server@server:~/.steam/debian-installation/steamapps/common/Valheim dedicated server/valheim_server_Data/MonoBleedingEdge$ ll
total 16
drwxrwxr-x 4 server server 4096 mrt 22 18:32 ./
drwxrwxr-x 6 server server 4096 mrt 22 18:32 ../
drwxrwxr-x 3 server server 4096 mrt 22 18:32 etc/
drwxrwxr-x 2 server server 4096 mrt 22 18:32 x86_64/
```

**Comment by Zxurian** [comment]
@RoyvanEmpel okay, looks pretty standard. One thing I noticed is that you're running it out of `~/.steam/steam/steamapps/common/Valheim dedicated server/`, but the script is finding the path `/home/server/.steam/debian-installation/steamapps/common/Valheim dedicated server/`

if you type `pwd` from `~/.steam/steam/` and again from `~/.steam/debian-installation/` what are the outputs?

**Comment by RoyvanEmpel** [comment]
```
server@server:~/.steam/debian-installation/steamapps/common/Valheim dedicated server$ pwd
/home/server/.steam/debian-installation/steamapps/common/Valheim dedicated server
server@server:~/.steam/debian-installation/steamapps/common/Valheim dedicated server$ cd /home/server/.steam/debian-installation/steamapps/common/Valheim\ dedicated\ server/
server@server:~/.steam/debian-installation/steamapps/common/Valheim dedicated server$ pwd
/home/server/.steam/debian-installation/steamapps/common/Valheim dedicated server
```

Its the same directory.

**Comment by RoyvanEmpel** [comment]
```
server@server:~/.steam/steam$ pwd
/home/server/.steam/steam
server@server:~/.steam/steam$ cd ~/.steam/debian-installation/
server@server:~/.steam/debian-installation$ pwd
/home/server/.steam/debian-installation
```

**Comment by Zxurian** [comment]
that's odd, in the log you posted, it shows you running the `./start_server_bepinex.sh` file out of the `~/.steam/steam/steamapps/common/Valheim dedicated server/` directory, which doesn't include `debian-installation`.

At first pass, it looks like a corrupted path issue in some of the files, since it's got the non-standard characters in the output log, especially after finding the the right files. I'll try replicating the path on my system tonight just to check.

One thing you can try for the sake of argument is just re-downloading and installing the Valheim server into `~/testme/` as a standalone test
1) `steamcmd +login anonymous +force_install_dir /home/server/testme/ +app_update 896660 validate +exit`
2) download Unix Server from https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.5.5 and unzip it into `/home/server/testme/` (overlay into same directory Valheim+ is installed into
3) Grab updated resource files linked above and overwrite the existing ones in `/home/server/testme/`
4) `chmod +x ./start_server_bepinex.sh`
5) Try running `~/start_server_bepinex.sh` and see what happens

**Comment by RoyvanEmpel** [comment]
the .steam/steam folder is a link to .steam/debian-installation i guess.

```
server@server:~/.steam$ ll
total 24
drwxrwxr-x  3 server server 4096 mrt 22 19:52 ./
drwxr-xr-x 25 server server 4096 mrt 22 17:45 ../
lrwxrwxrwx  1 server server   25 mrt 22 15:45 bin -> /home/server/.steam/bin32/
lrwxrwxrwx  1 server server   51 mrt 22 15:45 bin32 -> /home/server/.steam/debian-installation/ubuntu12_32/
lrwxrwxrwx  1 server server   51 mrt 22 15:45 bin64 -> /home/server/.steam/debian-installation/ubuntu12_64/
drwxrwxr-x 28 server server 4096 mrt 22 15:46 debian-installation/
-rwxrwxr-x  1 server server  740 mrt 22 19:52 registry.vdf*
lrwxrwxrwx  1 server server   39 mrt 22 15:45 root -> /home/server/.steam/debian-installation/
lrwxrwxrwx  1 server server   47 mrt 22 15:45 sdk32 -> /home/server/.steam/debian-installation/linux32/
lrwxrwxrwx  1 server server   47 mrt 22 15:45 sdk64 -> /home/server/.steam/debian-installation/linux64/
lrwxrwxrwx  1 server server   39 mrt 22 15:45 steam -> /home/server/.steam/debian-installation/
-rw-rw-r--  1 server server    6 mrt 22 15:46 steam.pid
prw-------  1 server server    0 mrt 17 19:34 steam.pipe|
-r--------  1 server server   16 mrt 22 15:46 steam.token
```

**Comment by Zxurian** [comment]
@RoyvanEmpel popping in to say I'm still testing. I'm getting the same spam related to `Fallback handler could not load library` so trying to isolate whether it's the `start_server_bepin.sh` or something else.

**Comment by RoyvanEmpel** [comment]
Oke, the server is working but it would be nice if the error problem was to be fixed. Running it from the steam folder makes it so I can update it thru the steam client.
