### ISSUE TITLE
[BUG] Crafting from chests - Cooking station

### ISSUE THREAD

**Issue by operinko** [valheimPlus/ValheimPlus#424]
- **OS:** Windows Client, Linux Server
- **Valheim Game Version:** 0.148.6
- **V+ Mod Version:** 0.9.6

**Describe the bug**

With craft from chests enabled, spam-clicking on a cooking station constantly removes uncooked food items from chests even when cooking station is already full and cooking something.
The removed items get deleted.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Build a cooking station over a fire.
2. Build a chest next to it.
3. Put raw food (raw meat, tails, etc) into chest
4. Spam-click the cooking station a few times and check that the chest has emptied.

**Expected behavior**

Raw food shouldn't be taken from the chest when it can't be put on the cooking station.

**Comment by healiha** [comment]
I'm on it!
