### ISSUE TITLE
[BUG] Config merger strips multi-comment lines out

### ISSUE THREAD

**Issue by Zxurian** [valheimPlus/ValheimPlus#427]
When using the new config handling web app at https://valheim-plus-config.web.app/
The web app is stripping out multi-line comments (appears to only keep the last line before the actual configuration value).

Original entry in .cfg
```
; If set to true, torch-type fire sources will stay at max fuel level once filled.
; Applies to: wood torches, iron torches, green torches, sconces and brazier
; default: false
torches=false
```

How this appears within the web app
![image](https://user-images.githubusercontent.com/573371/112156456-a4354880-8bbc-11eb-85eb-fe5f77cd9699.png)

How it's exported in the resuting merged cfg
```
[FireSource]

; default: false
enabled=true

; default: false
torches=false
```

Also, it appears that the webapp is changing what is displayed slightly, since webapp shows `default: false (torches)` as the entry name, but I can't find a 1:1 text match in either old or new config file. Is the source for the web app public? if so, I'll take a look for it.

Old config: https://pastebin.com/ECXtAV8G

**Comment by Brydom** [comment]
👋🏼 Thanks for reporting this. There isn't a public repo at the moment for the config manager so we'll be managing issues through here for now.

I'll be pushing out an update later today to fix this!

**Comment by DiskImage** [comment]
Related, the multi-line comments could stand to switch to using the `#` character over `;` so they are recognized as info lines rather than Header/Title type ones in config editor/displays like Thunderstore's. This is the only plugin I've tried (out of a few dozen) that has used the `;` character. IMO, both of these are display issues on the same feature.

**Comment by nxPublic** [comment]
We are not in charge of the website you mentioned.

We also have a update system that works automatically for new releases since 0.9.7
