### ISSUE TITLE
[BUG] Console Option Gone

### ISSUE THREAD

**Issue by Baelek** [valheimPlus/ValheimPlus#428]
- **OS:** Windows 10 and also 
- **Valheim Game Version:** 0.148.6
- **V+ Mod Version:** 0.9.6

**Describe the bug**
When pressing F5 to force a save on the world as I play on a hosted server and am an admin, the console never pops up. 

**To Reproduce**
Steps for the devs to reproduce the behavior:
1. Press F5
2. ....

**Expected behavior**
When pressing F5, the console menu should come up.

**Troubleshooting**
I have done a clean install of Valheim, entered the world in a local game, and the console menu comes up when pressing F5. When installing a clean copy of V+ 0.9.6, the console no longer comes up when pressing F5 when entering a local game. The same holds true when I connect to my hosted server.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
The config file is the default config file that comes with 0.9.6.

**Comment by acolitex** [comment]
The new Valheim updated removed it being enabled by default you have to add -console to the command line to enable now

**Comment by acolitex** [comment]
It looks like there is an addon to enable it by default also

https://www.nexusmods.com/valheim/mods/669

**Comment by Baelek** [comment]
I'm perplexed as to why without V+ and when using a fresh download (as of 10 minutes ago for 0.148.6), I can pull up the console with no issue, but as soon as I install V+, they have it disabled. Where is the command line at specifically to add in -console, as I do not want to keep downloading mods?

**Comment by healiha** [comment]
This has nothing to do with V+, it has been changed by the game developers, not us.
https://store.steampowered.com/news/app/892970/view/3047221359547604552
