### ISSUE TITLE
The latest game patch seems to have broken this mod

### ISSUE THREAD

**Issue by SirFrostingham** [valheimPlus/ValheimPlus#434]
- **OS:** Windows Client, Windows Server
- **Valheim Game Version:** 0.148.6
- **V+ Mod Version:** Stable 0.9.6

Valheim release news: https://store.steampowered.com/news/app/892970/view/3047221359547604552

The game loads without Valheim Plus logo or any features.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Install mod
2. Start game
3. Valheim Plus mod does not work

**Expected behavior**

Mod should load

**Troubleshooting**

Removed all other mods, but Valheim Plus mod.

**Comment by Voarexxx** [comment]
I am having a similar issue and have posted detailed notes on my ticket created, if it is similar then we both have the same issue.

**Comment by SirFrostingham** [comment]
I think shrapnel of another mod messed this up. The mod works with the latest game patch.

**Comment by Voarexxx** [comment]
I hope to have a resolution to mine soon. Lmk if you are able to assist, my server is only running the Valheim Plus mod and should work just fine. *shrug*

**Comment by SirFrostingham** [comment]
Will do. I downloaded the mod, unzipped it and simply copy/pasted the files over the game directory. After that, the game worked loaded and showed the Plus mod logo.

**Comment by Voarexxx** [comment]
I have the logo and everything which is why it's so strange. Everything shows as up to date for me but for WHATEVER reason the game keeps saying Incompatible Version. So I'm honestly stumped.

**Comment by SirFrostingham** [comment]
Oh! That happened to me too. Maybe it is screwed up. I will reopen my issue. If I can fix it, I will post here.

**Comment by SirFrostingham** [comment]
I fixed my issue. The client-side mod config updated from 19kb to 22kb. An old copy of the mod must have been loading.
