### ISSUE TITLE
[BUG] Incompatible Version

### ISSUE THREAD

**Issue by Voarexxx** [valheimPlus/ValheimPlus#435]
- **Linux Server**
- **Valheim Game Version:** [0.148.6]
- **V+ Mod Version:** [0.9.6]

**Incompatible Version**

I've recently updated to the latest versions on the client and the server and it is saying my friends and I have an Incompatible Version. I use a PowerShell script to update locally that is coded to automatically pull your latest version and has been working fine until the recent update.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Update Valheim Plus using the server menu. 
2. Go to 'https://github.com/Voarexxx/valheim_plus_client_update_tool'
3. Click on 'Download Zip'
4. Open file to go through the PowerShell notes if you wish prior to running the script. 
5. After reviewing those files, you can open file location and run the script in PowerShell, though you probably won't need it if you are just wanting to read the script.
6. Incompatible Version upon logging into the Valheim Plus server.

**Expected behavior**

My Valheim server with Valheim Plus mod enabled says version 0.9.6 but when I go to the game and login to the server it says "Incompatible Version". 

**Troubleshooting**

 I ran the updates again using the Valheim Plus menu just to verify, and am still getting same issue. All the version are accurate, 0.9.6 and I've updated local files and even uninstalled and reinstalled. I legit have no clue why my server is incompatible, but it's completely up to date. 

**Screenshots**

Unsure if applicable

**Link to [Github](https://github.com/Voarexxx/valheim_settings) containing .cfg configuration if applicable:**

**Additional context**

I've done everything I can think of. I have updated and installed and disabled and re-enabled Valheim Plus mods on the server. I've updated the values. All the server information shows as 0.9.6. I even updated the server files with git add files for the new files for logs. *shrug* Please help.

**Comment by nxPublic** [comment]
We cannot help you if you do not post server / client logs and your used configuration file.

**Comment by 082Mitch** [comment]
I am having the same error and have updated both client and server files several times. My server is hosted on NodeCraft. Linux. Here are the config files. 
Server-->https://pastebin.com/PzJsNGAm
Client--> https://pastebin.com/nTigYbRj

**Comment by Voarexxx** [comment]
> We cannot help you if you do not post server / client logs and your used configuration files.

Link to Valheim Server cfg files. - https://github.com/Voarexxx/valheim_settings
Link to Client_Update_Tool - https://github.com/Voarexxx/valheim_plus_client_update_tool
Not sure what else you need?

**Comment by 082Mitch** [comment]
I may have found the issue in the server console at NodeCraft at least.
 VERSION check their:0.148.6@0.9.6 mine:0.147.3@0.9.6[2021-03-24 07:02:11]: VERSION check their:0.148.6@0.9.6 mine:0.147.3@0.9.6
From that, I would say that they ( NodeCraft) updated the ValheimPlus Mod on their servers, but the game client is behind. But that is just a guess.

**Comment by healiha** [comment]
It is exactly as you suspect 🙂. Server reports using v0.147.3 of the game.

**Comment by Voarexxx** [comment]
How do I fix this?

**Comment by nxPublic** [comment]
Update your server.

**Comment by Voarexxx** [comment]
> Update your server.

Welp, my PowerShell script worked just fine and now all of a sudden I'm getting massive errors? I'll have to look at this code later, kind of tedious when the script was just fine prior to 0.9.6. For now, I will manually update to 0.9.6 Valheim Plus, and fix the .sh later. Hopefully by manually updating Valheim Plus on my personal PC, I can play again. :< I'll close this ticket if it works. Thank you for all your help!

**Comment by healiha** [comment]
@Voarexxx  It's not about your PS script but Valheim Dedicated Server not bein updated with latest version. Check through Steam to update it.

**Comment by Voarexxx** [comment]
> @Voarexxx It's not about your PS script but Valheim Dedicated Server not bein updated with latest version. Check through Steam to update it.

My PS script is what updates me to the latest version of their Valheim Plus Server. It was working fine updating me all the way through to 0.9.5 and even updated me to 0.9.6 but as said on the original bug statement it was still Incompatible. nxPublic advised to update again and when I ran the .sh again, it has many errors all of a sudden and should work. Missing the patchers folder, which generally is empty anyway, but a bunch of other things that I'm just like, off. This worked fine so idk what happened... :/ I'll just update it to whatever files are updated and move on, will just have to be after work. The whole point of the .sh was to make it super fast by grabbing Valheim Plus latest version from this github and then doing the things. lol

**Comment by healiha** [comment]
I repeat once again: it's NOT Valheim Plus but **the Valheim Dedicated Server**, the one you installed through **Steam** that need to be updated from your steam client.

**Comment by Voarexxx** [comment]
I'm not using Valheim Dedicated Server, I am using Digital Ocean.

**Comment by healiha** [comment]
The it's the version running there of the game server who needs to be updated imho.

**Comment by Voarexxx** [comment]
I have updated it. That's the thing. My actual Valheim game files are not updating to Valehim Plus using my .sh script which takes the version of Valheim Plus from here and does all the magic for me so I don't have to. So, I'm going to try to do the manual extraction into my local steam files and see if that works. If it works, awesome. If not, I'll let you know.

**Comment by Voarexxx** [comment]
I think I found my issue, when I uninstalled and reinstalled the game it went from my C: to my D: ... heh. oops.

**Comment by Voarexxx** [comment]
This is still unresolved. I have disregarded the .sh altogether and have updated my valheim server to the latest 0.9.6, I am using the Njord's menu for Valheim Plus located at https://github.com/Nimdy/Dedicated_Valheim_Server_Script - so maybe that is where my issue lies? Unless you guys are co-ordinated, unlikely though. My Steam says Valheim Plus  0.9.6 and my server menu and server says 0.9.6 :( If this isn't you guys sorry for the pain and hassle. I'll post the bug on theirs as well.

**Comment by healiha** [comment]
Could you provide your Player.log file located in `C:\Users\....\AppData\LocalLow\IronGate\Valheim` after trying to connect to your server?
Do @me on discord if you want, we'll update this once we've found where it comes from.

**Comment by Voarexxx** [comment]
> Could you provide your Player.log file located in `C:\Users\....\AppData\LocalLow\IronGate\Valheim` after trying to connect to your server?
> Do dm me on discord if you want, we'll update this once we've found where it comes from.

I apologize I am working, I will dm you on discord :)

**Comment by Voarexxx** [comment]
This issue has since been resolved. Re-updated the server, re-updated the local files, re-booted the server, and now automagically it works!

**Comment by Voarexxx** [comment]
Upon closing this ticket I realized that the Valheim Plus was not working on my server and was just a Valheim Server. So I am still having an incompatibility issue and I've updated everything. I've changed all the files manually, I've looked at comparisons between the BepInEx files and the Valheim Plus config files all of it... at a complete and utter loss and I want to pull my hair out. lol.

**Comment by Voarexxx** [comment]
[Player.log](https://github.com/valheimPlus/ValheimPlus/files/6202030/Player.log)

<img width="1496" alt="vplus" src="https://user-images.githubusercontent.com/80941695/112418647-83214480-8cef-11eb-87cd-017a04c01737.png">

<img width="301" alt="vplus2" src="https://user-images.githubusercontent.com/80941695/112418852-e317eb00-8cef-11eb-8c6d-deb8c34f612e.png">

**Comment by Voarexxx** [comment]
[Player.github.log](https://github.com/valheimPlus/ValheimPlus/files/6202067/Player.github.log)


<img width="1496" alt="vplus" src="https://user-images.githubusercontent.com/80941695/112418975-270af000-8cf0-11eb-97e8-352f78becdce.png">

<img width="301" alt="vplus2" src="https://user-images.githubusercontent.com/80941695/112418984-2bcfa400-8cf0-11eb-9148-c5dc9b9b6b7b.png">

**Comment by Voarexxx** [comment]
Was very helpful found the root cause of the issue was an error due to recent updates from Valheim Plus made permissions need to be the `steam` user for all files. Whereas, it used to allow as `root` or `otheruser`.

The solution is to make sure permission are set to steam user on all files in the `home/steam/` directory 

You may want to try the following code in your linux server:
```shell
chown steam:steam -Rf /home/steam/*
chmod +x start_server_bepinex.sh
```
