### ISSUE TITLE
[BUG] Torch autofill not working since 0.9.6

### ISSUE THREAD

**Issue by Sloth-on-meth** [valheimPlus/ValheimPlus#436]
- **OS:**N/A but ubuntu DS and windows client 
- **Valheim Game Version:** 0.148.6
- **V+ Mod Version:** 0.9.6
**Describe the bug**

Torch autofill does not work since latest update

**To Reproduce**

speaks for itself

**Expected behavior**

torch autofill

**Troubleshooting**

re-did config file with new config

**Screenshots**

N/A

**Comment by rr222cy** [comment]
Please provide your server and client CFG-file, the bug template is there for a reason, so that we can check if it's a V+ problem or a local user issue.

**Comment by Sloth-on-meth** [comment]
```
[FireSource]

; Change false to true to enable this section
; default: false
enabled=true

; If set to true, torch-type fire sources will stay at max fuel level once filled.
; Applies to: wood torches, iron torches, green torches, sconces and brazier
; default: false
torches=true

; If set to true, non torch-type fire sources will stay at max fuel level once filled.
; default: false
fires=true

; Look for fuel inside nearby chests.
; default: false
autoFuel=false

; Ignore private area check.
; default: true
ignorePrivateAreaCheck=true

; The range of the chest detection for the auto fuel features.
; default: 10
; min: 1
; max: 50
autoRange=10```



identical on both server and client

**Comment by healiha** [comment]
Thanks for the report!

While there is an issue here, it's not realted to the `autoFuel` feature but to "keep at max fuel and don't use any".

I believe I know what's causing this and it's not a new issue introduced with last release since it was already being reported with the previous versions.

I'll keep you informed once I'm done debugging/testing 🙂

**Comment by Sloth-on-meth** [comment]
ah, okay, that's a shame. it worked very well previously, in 0.9.4
i am looking to refill torches and fires without having fuel in chests, like it did in 0.9.4

**Comment by healiha** [comment]
This will be fixed with next release!

**Comment by Sloth-on-meth** [comment]
@healiha  dont wanna nag, but does that apply to torches too?

**Comment by healiha** [comment]
@Sloth-on-meth, it does for both torches and fires.

**Comment by Sloth-on-meth** [comment]
when will this come out? my entire world is dark :<

**Comment by Sloth-on-meth** [comment]
@healiha i just installed 0.9.7 on both server and client, confirmed the section is loaded, but still not auto refilling torches

**Comment by Sloth-on-meth** [comment]
NEVERMIND! it works!
