### ISSUE TITLE
noMysticalForcesPreventPlacementRestriction doesn't allow destroying

### ISSUE THREAD

**Issue by Madanor** [valheimPlus/ValheimPlus#437]
* Valheim Game Version: 0.148.6
* V+ Mod Version: 0.9.6
* ZAP-Hosting Valheim Plus server
* Windows 10 client

`noMysticalForcesPreventPlacementRestriction=true` does allow building in mystical force area, but not destroying with the hammer. The default message from the game appears. I tried it in the game start area.
AdvancedEditingMode is also not activating for objects in the area. But I don't know if that is supposed to work. It would make sense, though.

**Comment by nxPublic** [comment]
What restricted zone did you test this with ?
Vendor or Spawn ?

**Comment by Grewfisk** [comment]
I am also experiencing this trying to build within the spawn circle. I can place, hoe, etc but I can't use the hammer to destroy stone walls and torches I placed.

- Valheim Game Version: 0.148.6
- V+ Mod Version: 0.9.6
- DigitalOcean Ubuntu 20.04
- Windows 10 client

**Comment by Madanor** [comment]
I experience the bug in the start area, the runestone circle, where you place the boss trophies.

**Comment by DogBeatr** [comment]
Same with me.  I have a workbench within the starting spawn point range and still can't dismantle it even with the option turned on in the VPlus settings.

**Comment by Valethar** [comment]
> I experience the bug in the start area, the runestone circle, where you place the boss trophies.

Same here.  I placed a few of the palisade spikes along the fenceline of my original 'base', and now I cannot remove them. Any attempt to do so results in the standard error message about mystical forces.

**Comment by Madanor** [comment]
Can I provide you with additional information? Config file, savegame?

**Comment by healiha** [comment]
This has been adressed with af1ca9e, it'll be fixed with next release!

**Comment by Madanor** [comment]
You are heroes. :metal:

**Comment by nxPublic** [comment]
This should hav ebeen fixed with 0.9.7~0.9.8
