### ISSUE TITLE
Building / Editing Modes not working

### ISSUE THREAD

**Issue by Newyears1978** [valheimPlus/ValheimPlus#44]
All other mods seem to be working but neither of the building modes are working.

**Comment by Samsterious** [comment]
Both modes appear to work as intended in v0.8 on my configuration.

Maybe one of these could be causing this problem for you?
* The configuration file seems to have both of these features disabled by default. (See the `[AdvancedBuildingMode]` and `[AdvancedEditingMode]` sections. They both contain an `enabled` flag.)

* Advanced Building Mode requires you have an object selected for placement before being activated. Advanced Editing Mode requires the opposite, that you not have the hammer equipped at all.

**Comment by Newyears1978** [comment]
I was dumb I missed the two settings (Discord helped me)

They are in a bit of a wonky order so I saw the first build setting but not the other two further down.

Thanks!
