### ISSUE TITLE
[Feature Request] Allow selecting which crafting stations are affected by CraftFromChest

### ISSUE THREAD

**Issue by jtronicus** [valheimPlus/ValheimPlus#440]
**Is your feature request related to a problem? If so, please describe.**
I really enjoy the CraftFromChest feature.  However, I would prefer the ability to disable this feature for certain crafting stations (such as the Cooking Station or Smelter).  Since a user cannot control which items are inserted when pressing 'E', this can result in the wrong item being cooked or smelted.

**Describe the solution you'd like**
Add config options to disable CraftFromChest for specific stations
```
[CraftFromChest]

; Change false to true to enable this section
enabled=false

; Change false to true to disable this feature for specific Crafting Stations
smelter=false
cookingStation=false


; If in a workbench area, uses it as reference point when scanning for chests
checkFromWorkbench=true

; Ignore private area check.
ignorePrivateAreaCheck=true

; The range of the chest detection (min: 1, max: 50)
; default: 20
range=20

; Interval in seconds between each nearby chests discovery (min: 1, max: 10)
; default: 3
lookupInterval=3
```

**Comment by healiha** [comment]
I'll take a look at that later.

Not sure if we'll go with this approach but I'll keep your proposal in mind.

**Comment by healiha** [comment]
For now I've added the possibility to disable this feature when using a Cooking Station.

I don't really see the point in doing so for the smelters and the code would just get messy as all Kiln, Smelter, Furnace, Windmill and Spinning Wheels are all implemented as `Smelter` type in the game.

See #470
