### ISSUE TITLE
[FEATURE REQUEST] Hotkey connect to server with password

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [valheimPlus/ValheimPlus#442]
I would like a feature added that allows us to connect to a specific server with password with a hotkey (or a menu on start screen) for faster connects.

**Comment by BrutalCSEjziponken** [comment]
Found this for anyone looking for something similar: https://www.nexusmods.com/valheim/mods/160

Its not exactly what I requested, but its a timesaver.

**Comment by devorbitus** [comment]
we use the QuickConnect mod to accomplish this quite well as it enters the connection info AND the password https://www.nexusmods.com/valheim/mods/193

**Comment by BrutalCSEjziponken** [comment]
> we use the QuickConnect mod to accomplish this quite well as it enters the connection info AND the password https://www.nexusmods.com/valheim/mods/193

Thanks, that even better than what I had. :)

**Comment by bembleton** [comment]
I was working on a V+ patch to remember the last used password but having a server list in the QuickConnect mod is really nice and I might start using that. I would prefer that the password wasn't plaintext, though. The game uses a password hash, so my update hooked into that and saves the hash in PlayerPrefs.

**Comment by Mixone-FinallyHere** [comment]
Resolved in a separate mod, we wont be adding this feature currently
