### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by dpcleve** [valheimPlus/ValheimPlus#444]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Is your feature request related to a problem? If so, please describe.**
AutoFuel feature - I don't like how the kiln will eat all the fuel and turn it into coal when I don't need more.

**Describe the solution you'd like**
Please detect how much coal I have in nearby boxes, and if already at a configured threshold (i.e. MaxCoal setting or something like that), then stop feeding the kiln.

**Additional context**

**Comment by nxPublic** [comment]
This has been added with #454
