### ISSUE TITLE
[FEATURE REQUEST] More configurable [Workbench] section

### ISSUE THREAD

**Issue by vhreq** [valheimPlus/ValheimPlus#445]
I really like a huge crafting radius but do not like that it affects enemies spawning within that huge radius.

[This issue](https://github.com/valheimPlus/ValheimPlus/issues/118) and [this PR](https://github.com/valheimPlus/ValheimPlus/pull/306) suggest that enemy spawning is linked to workbench radius. I would like to have them separately configurable within the [Workbench] section.

I'm not sure if item de-spawning is linked to the workbench radius as well, but if it is, it would be nice to have the option to configure that as well. In fact it would probably be good to have configurations knobs for everything the workbench affects.

**Comment by JourneyOver** [comment]
Yes please, I like having a pretty big crafting radius as well but hate the fact that it pretty much blocks enemy spawns inside that radius, also making the events that pop up every so often moot as nothing spawns from said event so there is just a big warning at your base with nothing to attack.

**Comment by nxPublic** [comment]
Already implemented.
