### ISSUE TITLE
[FEATURE REQUEST] Hotkey to disable shield auto-equip with one handed tools/weapons

### ISSUE THREAD

**Issue by FoxyLight** [valheimPlus/ValheimPlus#450]
The new feature to auto-equip your shield with any one handed weapon is great. One issue I've come across though is you cannot equip a torch and a tool/weapon since a torch will always equip the shield. I thought it might be useful if there was a hotkey you could hold while equipping your one handed item that would keep the shield from equipping. Thanks for you work.

**Comment by BrutalCSEjziponken** [comment]
And maybe even add a config setting to make it not equip shield if its an TOOL. I dont really want a big shield up while cutting wood for example.

**Comment by FoxyLight** [comment]
To be honest, I do like that it does it on axe and pickaxe too in case I get attacked out of nowhere and can't switch fast enough, but that's just a personal preference and I definitely see what you mean.
