### ISSUE TITLE
[BUG] Massive FPS Drop w/ 'CraftFromChest' Enabled on G-Portal Server

### ISSUE THREAD

**Issue by Montauknightsky** [valheimPlus/ValheimPlus#451]
- **OS:** Windows Server / G-Portal.Com US East
- **Valheim Game Version:** 0.148.6
- **V+ Mod Version:** 0.9.6

**Describe the bug**

FPS drops from ~70 to ~10 when BUILDING (hammer) is opened and _an item to place is selected_. Had enabled the new "CraftFromChest' setting (which appears to be functional) and then ran into the issue - disabling the setting resolved the issue.

Looking at the console, repeated errors in red text mentioning "CraftFromChest" setting, "unable to pull resources" (Sorry I didn't save a copy of the actual error message :[ )

No other mods enabled. 

Steam & GEFORCE Overlays enabled.

Build: 
AMD Ryzen 7 3700x
Zotac RTX 2060
MSI B450 Tomahawk
EVGA 1kW PSU
64GB 3000Mhz RAM

**Comment by healiha** [comment]
Already addressed by #432 and will fixed be with v0.9.7.
