### ISSUE TITLE
[FEATURE REQUEST] Command line in launcher

### ISSUE THREAD

**Issue by AetherealGlow** [valheimPlus/ValheimPlus#456]
Valheim Plus launcher doesn't seem to have a configurable command line function for starting the game so I can't enter "-console" to enable the console.

**Comment by healiha** [comment]
We're adding an option in the config file to force enable/disable the console in the next version.

I'll keep this issue open until it has been released.

**Comment by nxPublic** [comment]
There is now a option under [Game] to force enable and disable the console.
