### ISSUE TITLE
[FEATURE REQUEST] Ability to automatically pin near each death location

### ISSUE THREAD

**Issue by devorbitus** [valheimPlus/ValheimPlus#465]
If you die multiple times each death would have a pin added automatically so that the original death spot could always be found

**Comment by greenskye** [comment]
An enhancement to this request would be to just allow multiple death markers and also make death markers manually removable

**Comment by devorbitus** [comment]
and as long as we are making requests having a timestamp as a hover text for each death marker would be awesome!
