### ISSUE TITLE
[FEATURE REQUEST] Refactor `GameClasses/Container.cs`

### ISSUE THREAD

**Issue by Igmat** [valheimPlus/ValheimPlus#478]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**
No similar problems found

**Is your feature request related to a problem? If so, please describe.**
I'm a developer of the [mod](https://www.nexusmods.com/valheim/mods/653?tab=description) that adds other containers (one for now). And I want these new pieces to be balanced with other containers in the game. I've started from some balanced constants for sizes of added prefabs but later switched to [the calculation based on existing containers](https://github.com/Igmat/ChestReloadedPlugin/blob/master/Plugin/Pieces/SignedLocker.cs#L62). It works great with vanilla containers, so whenever Iron Gated decides to change container sizes, my pieces will adapt to new values.
But it doesn't work with configuration from ValheimPlus, since you [update chest sizes on `Container.Awake`](https://github.com/valheimPlus/ValheimPlus/blob/development/ValheimPlus/GameClasses/Container.cs).

**Describe the solution you'd like**
Could you, please, update prefabs on `ObjectDB` instead of  `Container.Awake`?

**Additional context**
Obviously, I can try to find some other solution inside my mod, but it's very likely that such a solution will be really fragile and might heavily depend on load order and other stuff that can't be controlled by mod itself.

**Comment by nxPublic** [comment]
I made a note about this issue, I agree we should pursue more compatibility. Please get in touch with me on Discord nx#8830 so we can make sure we can make that happen!

Thanks for letting us know!
