### ISSUE TITLE
[FEATURE REQUEST] Hotkey separate config

### ISSUE THREAD

**Issue by Zerville** [valheimPlus/ValheimPlus#479]
A separate hotkey config file will make it far easier finding and setting the personal hotkey settings in valheim+, especially as we see most peoples using server side settings nowadays and we now have the nice feature to use personal hotkeys.
Perhaps we will see more client side only settings soon? then the proper config name might be something like personalsettings valheim+?

Thanks in advance

**Comment by nxPublic** [comment]
People are already confused, unlikely we will make it more complicated.
