### ISSUE TITLE
[BUG] serverSyncHotkeys not working as intended

### ISSUE THREAD

**Issue by baconparticles** [valheimPlus/ValheimPlus#485]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
Windows 10

- **Valheim Game Version:** [e.g. 0.4.11, etc]
0.148.6

- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]
0.9.6

**Describe the bug**

Playing on Helscape (which has serverSyncHotkeys=false) I am unable to change my roll hotkeys

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Go to 'valheim_plus.cfg'
2. Verify that serverSyncHotkeys=false after seeing that serverSyncsConfig=true
3. Set rollForwards=F10
4. Set rollBackwards=F11
5. Start valheim and connect to server
6. F9 still rolls forwards

1. run local client world
2. F11 rolls backwards

**Expected behavior**

F10 rolls forwards on server
F11 rolls backwards on server

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/r4UEYpe1

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
![image](https://user-images.githubusercontent.com/81045679/112771774-85d7ae80-8ffb-11eb-88f2-523c91778947.png)

**Comment by healiha** [comment]
Thanks for the report!

We'll look through this and get back to you as soon as we can.

**Comment by nxPublic** [comment]
This has been addressed with https://github.com/valheimPlus/ValheimPlus/commit/99e8c72186d6ee5bdc4015f5621357b0d45946d6
