### ISSUE TITLE
[BUG] When using auto-equip shield with a long shield, Long shield stays equipped after weapon is put away

### ISSUE THREAD

**Issue by sbtoonz** [valheimPlus/ValheimPlus#499]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**

A clear and concise description of what the bug is and how you found it.

**To Reproduce**

Steps for the devs to reproduce the behavior:

**Expected behavior**

When Auto-Equip shield with weapon = true in config I expect shield to auto-equip and unequip with weapon 

Round shields exhibit this behavior

**Troubleshooting**

there isnt really any toggles i can make to troubleshoot this aspect other than watch the logs and try to ascertain if long shield works differently

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

CustomTextrues
OdinPlus
BetterContinents
JotunnLib
MasterChef
HitboxFix
MapTeleport
Equipment and quickslots
Vchat
Simple Recycling
Lightning Arrows
Custom Loading Screen

**Comment by nxPublic** [comment]
I was not able to reproduce this.
