### ISSUE TITLE
[Feature Request] Shared Map Markers

### ISSUE THREAD

**Issue by maci0** [valheimPlus/ValheimPlus#50]
Would like to be able to share markers.

**Comment by nxPublic** [comment]
We are working on a network wrapper that would enable us to do that.

**Comment by radmint** [comment]
For progress reference: https://trello.com/c/7u4p81J9/35-shared-map-markers

**Comment by Gabb1995** [comment]
Cool, waiting for this to be merged before installing the other server side map mod to avoid conflicts. Thanks for your hard work.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Map as "Map Marker Sync System".
