### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by J-Pster** [valheimPlus/ValheimPlus#500]
- **OS:** Windows Server
- **Valheim Game Version:** 0.148.7
- **V+ Mod Version:** 0.9.6

**Describe the bug**

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
VBrasil.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <8a3782a2fd504319b65ac28c93f2968b>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Create a new map
2. Run to anywhere
3. See Server Console

**Expected behavior**

No errors.

**Troubleshooting**

Perhaps the problem is that the plugin is trying to increase the size of the chests before they have actually been created.

**Comment by nxPublic** [comment]
> VBrasil

So it's not valheim plus.

This error is fixed in 0.9.7 in addition.
