### ISSUE TITLE
HUD showRequiredItems doesn't take into account what's in chests when also using CraftFromChest

### ISSUE THREAD

**Issue by ssteward54** [valheimPlus/ValheimPlus#503]
When enabling the CraftFromChest feature, the HUD > showRequiredItems feature doesn't account for all the items in nearby chests, so it looks like you don't have enough resources to craft the items but you do if it's in a nearby chest. The other mod "Craft Build Smelt Cook Fuel Pull From Containers" does support this so could this be added to the Valheim+ version? Thanks!

**Comment by pavlvs327** [comment]
Works fine for me...

**Comment by nxPublic** [comment]
Can confirm this setting works entirely fine.

**Comment by ssteward54** [comment]
Sorry about this - found out it was a problem with the Multi Craft plugin not working properly.
