### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DjEMAudio** [valheimPlus/ValheimPlus#504]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**

The game runs at a solid 5 FPS for my friend and I.  We tried uninstalling and reinstalling but the problem hasn't been resolved.

**Comment by nxPublic** [comment]
We had a few people over the course of using BepInEx. 

We can recommend a fresh install of valheim and v+, we arent aware of the causes but its most likely nothing from Valheim Plus but from BepInEx.
