### ISSUE TITLE
[BUG] Skill gain display when skill type is unspecified

### ISSUE THREAD

**Issue by TorannD** [valheimPlus/ValheimPlus#508]
**V+ Mod Version:** 0.9.6

**Describe the bug**

When display skill gain is enabled, it can generate an error if the skill is unspecified or lacks field info. This bug also appears to cause a fault with the skill whenever it is access following the error, ie skill menu, or attempting to log out and save player profiles.

**To Reproduce**
Example: Mod creates a projectile, assigns projectile to player, but the projectile is missing m_skill info

**Request**

Suggestion is to add null checks to your skill display patch to prevent attempting to reference and display skill info that does not exist:

[HarmonyPatch(typeof(Skills), "RaiseSkill")]
public static class AddExpGainedDisplay
{	
	private static void Postfix(Skills __instance, Skills.SkillType skillType, float factor = 1f)
	{
		if (Configuration.Current.Hud.IsEnabled && Configuration.Current.Hud.experienceGainedNotifications)
		{
			Skills.Skill skill = __instance.GetSkill(skillType);
			float value = skill.m_accumulator / (skill.GetNextLevelRequirement() / 100f);
			__instance.m_player.Message(MessageHud.MessageType.TopLeft, "Level " + skill.m_level.tFloat(0).ToString() + " " + skill.m_info.m_skill.ToString() + " [" + skill.m_accumulator.tFloat(2).ToString() + "/" + skill.GetNextLevelRequirement().tFloat(2).ToString() + "] (" + value.tFloat(0).ToString() + "%)", 0, skill.m_info.m_icon);
		}
	}
}

Error Log:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
ValheimPlus.GameClasses.AddExpGainedDisplay.Postfix (Skills __instance, Skills+SkillType skillType, System.Single factor) (at <4e7137681808493383c9134cfb741930>:0)
(wrapper dynamic-method) Skills.DMD<Skills::RaiseSkill>(Skills,Skills/SkillType,single)
Player.RaiseSkill (Skills+SkillType skill, System.Single value) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
Projectile.OnHit (UnityEngine.Collider collider, UnityEngine.Vector3 hitPoint, System.Boolean water) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
Projectile.FixedUpdate () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)

**Comment by nxPublic** [comment]
Has been addressed with 0.9.8
