### ISSUE TITLE
[BUG] Since update to 0.9.7; incompatible version blocks logging in to server

### ISSUE THREAD

**Issue by TruckerHer** [valheimPlus/ValheimPlus#509]
- **OS:** Windows Client & Unix Server
- **Valheim Game Version:** 0.148.7
- **V+ Mod Version:** 0.9.7

**Describe the bug**

Running a dedicated server with the docker image from lloesche (https://hub.docker.com/r/lloesche/valheim-server)
It automatically updates V+. As well as Valheim game itself. 

When it just updated the V+ version; connecting has been impossible. We keep getting the Incompatible Version popup.
Windows Client has also been (manually) updated to 0.9.7.

Also tried disabling the enforcement of V+ version in the configuration. This had no effect.

stdout from the server shows the following: 

`Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Got status changed msg k_ESteamNetworkingConnectionState_Connecting
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: New connection
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Accepting connection k_EResultOK
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Connecting to Steamworks.SteamNetworkingIdentity
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Got status changed msg k_ESteamNetworkingConnectionState_Connected
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Connected
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Got connection SteamID <STEAMIDHERE>
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Got handshake from client <STEAMIDHERE>
Apr  5 18:58:26 /supervisord: valheim-server Version generator started.
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: VERSION check their:0.148.7@0.9.7  mine:0.148.7
Apr  5 18:58:26 /supervisord: valheim-server Version generator started.
Apr  5 18:58:26 /supervisord: valheim-server Version generator started.
Apr  5 18:58:26 /supervisord: valheim-server 04/05/2021 18:58:26: Peer <STEAMIDHERE> has incompatible version, mine:0.148.7 remote 0.148.7@0.9.7
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: RPC_Disconnect
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: Disposing socket
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: Closing socket <STEAMIDHERE>
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28:   send queue size:0
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: Disposing socket
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: Got status changed msg 
k_ESteamNetworkingConnectionState_ClosedByPeer
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: Socket closed by peer Steamworks.SteamNetConnectionStatusChangedCallback_t
Apr  5 18:58:28 /supervisord: valheim-server 04/05/2021 18:58:28: Got status changed msg k_ESteamNetworkingConnectionState_None`

**To Reproduce**

Steps for the devs to reproduce the behavior:
- Install server side version of V+ 0.9.7
- Install client side version of V+ 0.9.7
- Connect.

**Expected behavior**

Being able to enter the game

**Troubleshooting**

Completely rebuilt the docker image - which gets new Valheim server files, new V+ install files and re-installs everything. Only the config files and the world data has remained the same. 
Problem in stdout looks like it's not reading the Valheim Plus data server-side: `has incompatible version, mine:0.148.7 remote 0.148.7@0.9.7`

By the looks of the server start, it does actually load the correct valheim plus version:

`Apr  5 18:57:26 /supervisord: valheim-server [Message:   BepInEx] BepInEx 5.4.9.0 - valheim_server
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] Running under Unity vUnknown (post-2017)
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] Supports SRE: True
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] System platform: Bits64, Linux
Apr  5 18:57:26 /supervisord: valheim-server [Message:   BepInEx] Preloader started
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] 1 patcher plugin loaded
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
Apr  5 18:57:26 /supervisord: valheim-server [Message:   BepInEx] Preloader finished
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] Detected Unity version: v2019.4.20f1
Apr  5 18:57:26 /supervisord: valheim-server [Message:   BepInEx] Chainloader ready
Apr  5 18:57:26 /supervisord: valheim-server [Message:   BepInEx] Chainloader started
Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] 1 plugins to load
**Apr  5 18:57:26 /supervisord: valheim-server [Info   :   BepInEx] Loading [Valheim Plus 0.9.7]**
Apr  5 18:57:26 /supervisord: valheim-server [Info   :Valheim Plus] Trying to load the configuration file`

**Comment by nxPublic** [comment]
Your server is not running Valheim Plus.

You might be missing the BepInEx\plugins\valheimplus.dll.

**Comment by DogBeatr** [comment]
Same issue for me.  I have a server through GPortal and I'm getting the Incompatible Version message as well.  Could just be GPortal hasn't updated yet.  I did a couple of server restarts and still the same.  Just figured I would chime in here as well.

**Comment by nxPublic** [comment]
G-Portal most likely hasnt updated yet or has a faulty zip file of the Unix files.

Upload the new valheimplus.dll yourself, no need to update anything else really. Should work afterwards @DogBeatr

**Comment by DogBeatr** [comment]
I may wait then...I've never uploaded anything manually to my G-Portal servers before...lol

**Comment by TruckerHer** [comment]
For now I've installed the data from UnixServer.tar.gz with a version tag of: _0.9.6_.
Windows Client is 0.9.7; and replaced the _Server Side_ version of the ValheimPlus.dll to version _0.9.7_

Thanks to nx for the help, in Discord. Leaving this here as a little extra info and for those who want to 'quick fix' their server.

**Comment by Darkcreeper92** [comment]
We use G-Portal for our server and we were having the incompatible issue after 0.9.7. We have never update the server side for this manually. I asked my friend to check the valheimplus.dll file in the "BepInEx\plugins" folder on the server side and it was missing. We did a back up of our information and disable the config files put the .dll in the folder and then enable the configs and refresh the server. That corrected the "incompatible issue and server is back online again.

**Comment by branlan** [comment]
+1 for this issue, it seems like V+ is not being loaded by the server. 

I tried @TruckerHer 's solution, that did not help. 

Tried replaced ValheimPlus.dll on 0.9.6 UnixServer.zip with direct 0.9.7 ValheimPlus.dll , when a client connects it says:


`04/05/2021 16:57:24: Peer xxxxxxxxxxxxxxxxxxx has incompatible version, mine:0.148.7 remote 0.148.7@0.9.7`

rolling back to full V+ 0.9.6 solves the problem, but I'm a version behind.

**Comment by Carly98** [comment]
I'm having the same error, also with G-Portal.  My hubby didn't update his, and he can still access the server just fine. :(

**Comment by nxPublic** [comment]
Please contact your respective hosting companies, we are not at fault for these issues.

**Comment by branlan** [comment]
> Please contact your respective hosting companies, we are not at fault for these issues.

I am my hosting provider, and while not an issue with V+ itself, to get this update working, I had to wipe my entire 0.9.6 install and reinstall 0.9.7 from a fresh Valheim dedicated server to get it working. Would assume it's preferable that updating from a previous version of V+ would actually work in the future.

**Comment by pingupdatebrian** [comment]
Another fix on this is to simply download the plus config from the server and use it on your desktop, there seems to be some issue if you have a modified desktop config vs the server that causes this error also. We've solved countless issues of this error this way without having to touch any dll files.

**Comment by stubbfel** [comment]
its looks like that  config serialization  is broken. After i updated my server to 0.9.7 see following exception in my logs :
```
MissingFieldException: Field 'ValheimPlus.Configurations.BaseConfig`1<ValheimPlus.Configurations.Sections.ValheimPlusConfiguration>.IsEnabled' not found.
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```
and the current release files (tar.gz) didn't contains  any `valheim_plus.cfg` :(

**Comment by Mixone-FinallyHere** [comment]
@stubbfel do you still experience this issue?

**Comment by stubbfel** [comment]
@Mixone-FinallyHere since valheim 0.153.2 and a fresh install its working.

But the MissFiekdException still occurs during server start.

**Comment by Mixone-FinallyHere** [comment]
sounds like a lib issue on your end or your hosting platform end, if this were a reproducible error not a single configuration would work as isEnabled would not work
since they do I can only assume there is some issue with the libraries in use as if you inspect the compiled dll or the source code you can immediately see that the field does exist

can you please check with hosting provider?

**Comment by stubbfel** [comment]
i hosting the server by myself. I use SteamCMD to install/update the valheim server.

About which library we are talking about?

**Comment by Mixone-FinallyHere** [comment]
I would guess it is one of the harmony or bepinex libs as it seems to not be reading the dll properly maybe?
