### ISSUE TITLE
[Feature Request] Use V+ without overriding files in the game folder

### ISSUE THREAD

**Issue by maci0** [valheimPlus/ValheimPlus#51]
Would be nice if one could use V+ without overriding files the game ships with.
Raft Mod Loader does this too, it's also a unity engine based game.

**Comment by Qwertronix** [comment]
A version packaged for thunderstore.io / r2modman would solve this nicely (https://valheim.thunderstore.io/). I already use this to be able to play vanilla with one group while playing V+ with another group, though it required some jury-rigging to get it working on my end.

**Comment by ewoudje** [comment]
I am not sure if i should send it here but i quickly made r2modman mod zip of ValheimPlus, so i thougth sharing it here.
[ValheimPlus.zip](https://github.com/valheimPlus/ValheimPlus/files/6028296/ValheimPlus.zip)

**Comment by bbeenn1** [comment]
see issue #89 as well...

**Comment by bbeenn1** [comment]
There is one issue with the manifest.json file in that zip: it needs to declare a dependency: 
`    "Dependencies": [
		"denikson-BepInExPack_Valheim-5.4.600"
	]
`

**Comment by nxPublic** [comment]
We are considering it at the moment. We are working on it and am in contact with them.

Please do not share mod packages publicly without our approval.
