### ISSUE TITLE
[BUG] Personal chest show it as empty with no spots to put anything

### ISSUE THREAD

**Issue by stolenvw** [valheimPlus/ValheimPlus#515]
- **OS:** Windows Client, Linux Server
- **Valheim Game Version:** 0.148.7
- **V+ Mod Version:** 0.9.7

**Describe the bug**

When joining server trying to open a Personal chest show it as empty with no spots to put anything and gives this error 

`[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
InventoryGrid.UpdateGui (Player player, ItemDrop+ItemData dragItem) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
InventoryGui.UpdateContainer (Player player) (at <6fd2223d69c147d18c77057ce0dedd7b>:0)
InventoryGui.Update () (at <6fd2223d69c147d18c77057ce0dedd7b>:0)`

After opening a Chest, opening a Personal chest works fine.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. login
2. open personal chest without opening any other kind of chest

https://pastebin.com/DWX6b6N2

**Comment by stolenvw** [comment]
![Capture](https://user-images.githubusercontent.com/51084246/113791424-95e54180-9711-11eb-8867-a5ca0da8c45d.PNG)

**Comment by jtbg** [comment]
relevant PRs: #646 and #649 

The fix for this issue is staged for the next release. Thanks for the detailed report, @stolenvw !

**Comment by nxPublic** [comment]
This is fixed now! Thanks @jtbg ❤️
