### ISSUE TITLE
[BUG] Free Rotation tool default keybind clashes

### ISSUE THREAD

**Issue by oeed** [valheimPlus/ValheimPlus#516]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** latest
- **V+ Mod Version:** 0.9.7

**Describe the bug**
The free rotation mode is really great and fills some of the gaps the other building modes had.

However, I feel the default keybinds need to be tweaked.

The keybind to copy rotation is 'F', which is the default bind for Eikthyr, etc. and so I frequently find myself activating/wasting it.

The keybind to rotate on the X axis is holding C, but this also toggles some kind of slower walking speed (not sure if that from the mod or vanilla).

**Expected behavior**

Separate default keybinds that don't also trigger other actions.

**Comment by Mixone-FinallyHere** [comment]
This is not a bug

Our default keybinds are meant to be edited as we expect users to not blindly enable settings that have keybinds, you are more than welcome to submit a PR with suggested keybinds though
