### ISSUE TITLE
Metal Duplication [BUG]

### ISSUE THREAD

**Issue by bdngeorge** [valheimPlus/ValheimPlus#520]
- **OS:** [Windows Client]
- **Valheim Game Version:** [latest]
- **V+ Mod Version:** [0.9.7]

**Describe the bug**

I was smelting some iron and took some out of the chest that it was auto depositing into, and when it added another piece from the furnace the number of iron in there went back to the number that was in there before. In numbers terms, I took a stack of 32 iron out of the chest, another 1 got added, a stack of 32 iron appeared out of nowhere. I was able to reproduce this a couple of times with smaller stacks so I didn't feel as if I was cheating too much but I took a stack of 3 out, 1 went in and appeared a stack of 3 again. 

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Go to chest that is linked to a furnace
2. Open it while items are smelting
3. Right before a metal is added from the furnace take out a stack that is in there
         a. Make sure there are no other stacks the piece of metal can go into
         b. The stack you take out might have to be not a full stack
4. Watch as when the new metal is put in, it remakes the stack you took out, duplicating the metal.

**Expected behavior**

The 1 piece to go into the furnace, not a whole new stack showing up.

**Troubleshooting**

I don't own the server so I cannot troubleshoot it.

**Screenshots**

I didn't think to record it, I just found out there is a bug report

**Additional context**
No other mods.
*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by nxPublic** [comment]
If your server has severe lag or you computer does. There is nothing we can do about this with the server networking structure of valheim at the present moment.
