### ISSUE TITLE
[BUG] ABM/AEM key rebinds reverting to default keys in 0.9.7 update

### ISSUE THREAD

**Issue by analogfrog** [valheimPlus/ValheimPlus#521]
- **OS:** Server: Windows 10 Pro 20H2, Clients: Windows 10, various editions (tested on Win10 Pro 20H2)
- **Valheim Game Version:** 0.148.7
- **V+ Mod Version:** 0.9.7

**Describe the bug**

In order to accommodate players with various keyboard layouts, such as lack of numpads, I have the AEM keys re-bound in the server config. Upon updating to V+ 0.9.7, the keys for ABM and AEM revert back to their defaults, despite remaining customized in the config. No errors appear in the console output.

**To Reproduce**

Attempt to activate AEM or ABM with re-bound keys. AEM will still only activate with Num0, despite it being set to Delete. Tested ABM with F8 and it still activates with F1.

**Expected behavior**

AEM and ABM should activate with the proper keys set in the config file.

**Troubleshooting**

-Generated fresh config file and re-applied all values
-Wiped and reinstalled V+ on both client and server
-Changed keybind values client-side to make sure server config was being forced
-Removed spaces in config file (they get re-added upon server launch when it checks the config)
-Restarted server

**Screenshots**

```
[AdvancedEditingMode]

; https://docs.unity3d.com/ScriptReference/KeyCode.html <- a list of keycodes
; Change false to true to enable this section, if you set this to false the mode will not be accessible. https://valheim.plus/documentation/list#AdvancedEditingMode
enabled = true

; Enter the advanced editing mode with this key
enterAdvancedEditingMode = Delete

; Reset the object to its original position and rotation
resetAdvancedEditingMode = F7

; Exit the advanced editing mode with this key and reset the object
abortAndExitAdvancedEditingMode = F8

; Confirm the placement of the object and place it
confirmPlacementOfAdvancedEditingMode = Insert
```

**Additional context**

No other mods are installed.

**Comment by Gargoyle112** [comment]
In the server section, are BOTH settings on true?

`; Changes whether the server will force it's config on clients that connect. Only affects servers.
; WE HEAVLY RECOMMEND TO NEVER DISABLE THIS!
serverSyncsConfig = true

; If false allows you to keep your own defined hotkeys instead of synchronising the ones declared for the server.
; Sections need to be enabled in your local configuration to load hotkeys.
; This is a client side setting and not affected by server settings.
serverSyncHotkeys = true`

**Comment by nxPublic** [comment]
Not reproduceable.
