### ISSUE TITLE
[BUG] 0.7.5 Small bug

### ISSUE THREAD

**Issue by HeberPcL** [valheimPlus/ValheimPlus#525]
- **OS:** Windows
- **Valheim Game Version:** Last Release
- **V+ Mod Version:** 0.9.7

**Describe the bug**
![image](https://user-images.githubusercontent.com/715547/114053897-bcb48c80-9865-11eb-99f0-1a6054ee22de.png)

**Comment by Mixone-FinallyHere** [comment]
@HeberPcL  that is EpicLoot mod, please report EpicLoot bugs in the EpicLoot github: https://github.com/RandyKnapp/ValheimMods/issues
