### ISSUE TITLE
[BUG] Kiln Not Auto Depositing or Auto Fueling

### ISSUE THREAD

**Issue by DogBeatr** [valheimPlus/ValheimPlus#529]
- Windows Client
- **Valheim Game Version:** Current Version
- **V+ Mod Version:** 0.9.7

**Describe the bug**

The kiln is not auto depositing into chests or auto fueling from chests.  I tried setting the distance to 1 and placing chests right next to it and it still isn't working.

**Expected behavior**

Kiln to auto fuel from nearby chest and auto deposit to nearby chest.

**Troubleshooting**

Changed the settings in the config file to different ranges, including a range of 1 and placing a storage chest right next to the kiln hole.

**Comment by ncjsvr** [comment]
@DogBeatr can you please upload your valheim_plus.cfg and also LogOutput.log from Steam\steamapps\common\Valheim\BepInEx?

**Comment by DogBeatr** [comment]
[LogOutput.log](https://github.com/valheimPlus/ValheimPlus/files/6288490/LogOutput.log)

[Config Text.txt](https://github.com/valheimPlus/ValheimPlus/files/6288505/Config.Text.txt)

**Comment by healiha** [comment]
@DogBeatr change the `autoRange` value to 3 or 5.
The distance between objects is calculated from the center between each of them. 1 is still inside the kiln.

**Comment by DogBeatr** [comment]
Thanks @healiha I'll do that!

**Comment by DogBeatr** [comment]
Works perfect now.  Didn't realize it was calculated from the center.  Thank you again!

**Comment by baruchvlz** [comment]
Might be a good idea to add that as a comment in the configuration file.

**Comment by Mixone-FinallyHere** [comment]
Closing since it is resolved, we will try to add a note on this
