### ISSUE TITLE
[feature] Inventory logic & sorting

### ISSUE THREAD

**Issue by LordMike** [valheimPlus/ValheimPlus#53]
It seems to me that if I open a chest, or a tombstone, and "take all" items - they're not stacked with what I already have. This sucks, as I'll have to do inventory management afterwards in order to optimize it.

Things I think could be beneficial to have:

* Like above, when "taking all", find existing stacks and fill those first
* Add a button, or hotkey, that sorts the inventory I already have. Maybe don't sort the first row (the toolbar)
* A "put all", that moves my inventory to the chest I'm looking at.. It should either a) fill existing stacks only or b) fill existing stacks + make new stacks of existing items

#### Example for the "put all"
I have a chest with 1 stack of `wood` in it. The put all could be used to maximize this stack from my inventory, or to entirely fill the chest with just wood (making new stacks). If the chest had more items (wood & core wood), both those items could be moved when filling the chest.

Sidenote: Larger chests / more slots :O

**Comment by astranberg** [comment]
This would be a big QOL change. To expand upon it:

- Single-tap "taking all" would find existing stacks and fill those to the max, but not creatine new stacks in your inventory.
- Double-tap "taking all" would also create new stacks in your inventory if existing stacks are full.
- I'm probably dreaming, but if you could *pin* an item to your inventory, then pressing take all would fill that slot even if you currently have 88 of that item (e.g. arrows are all gone, you single press "take all" and it puts up to 12 arrows in your inventory, toping you off).

**Comment by maci0** [comment]
Similar as in 7days to die would be cool.

**Comment by maci0** [comment]
For reference: https://valheim.thunderstore.io/package/MaGic/Quick_Deposit/
https://valheim.thunderstore.io/package/end360/InventorySorting/

**Comment by shilliash** [comment]
I would actually consider to allow players enter quantity by typing slider is a little bit annoying (for some).

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Map as "Inventory Organization Buttons".
