### ISSUE TITLE
[FEATURE REQUEST] Allow multiple players to access chest at once

### ISSUE THREAD

**Issue by thedeany** [valheimPlus/ValheimPlus#535]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Is your feature request related to a problem? If so, please describe.**
Currently only one player can access a given chest at a time.

**Describe the solution you'd like**
Allow multiple players to access a given chest at a time.

**Comment by nxPublic** [comment]
Not really possible with the current networking of the game.

It would open up to many options to dupe items.

**Comment by EldRoos** [comment]
Only first person should have write access, the others read only.
