### ISSUE TITLE
[BUG] [CraftFromChest] disableCookingStation

### ISSUE THREAD

**Issue by marvinej** [valheimPlus/ValheimPlus#538]
- **OS:** Windows Client
- **Valheim Game Version:** 0.148.7
- **V+ Mod Version:** 0.9.7

**Describe the bug**

; Change false to true to disable this feature when using a Cooking Station.
disableCookingStation = true

The reverse is actually how it works. Setting it to false stops the cooking station from grabbing from chests and setting it to true allows it to grab from chests.

**Comment by nxPublic** [comment]
This has been addressed in 0.9.8
