### ISSUE TITLE
[BUG] Cant open the console

### ISSUE THREAD

**Issue by Luxa88** [valheimPlus/ValheimPlus#541]
- **OS:** Windows 10 Pro
- **Valheim Game Version:** 0.148.7
- **V+ Mod Version:** 0.9.7

**Describe the bug**
Hello, I have a own dedicated server and was trying to open the console but its not working.
When i delete the ValheimPlus.dll on server- and clientside its working. 

**To Reproduce**

Steps for the devs to reproduce the behavior:
1.  Login into Steam and go to View > Server
2. Join Server
3. Select Char
4. When Im in the game, pressing F5 has no effect

**Expected behavior**

Console Popup

**Troubleshooting**

I have entered in the startoptions "-console".
I have checked if any keybind is on F5 in the config file of valheim+.

**Screenshots**

![image](https://user-images.githubusercontent.com/82514317/114707196-39de7680-9d2a-11eb-8283-ba5c1ddfe460.png)

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/Qq8LiaBh

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by stolenvw** [comment]
your config file has console disabled got to the `[Game]` section and set `forceConsole=false` to `forceConsole=true`

**Comment by nxPublic** [comment]
```ini
[Game]
 
; Change false to true to enable this section. https://valheim.plus/documentation/list#Game
enabled = true
 
; The games damage multiplier per person nearby in difficultyScaleRange(m) radius.
; Default is 0.04, 4% monster damage increase per player in radius.
gameDifficultyDamageScale = 0.04
 
; The games health multiplier per person nearby in difficultyScaleRange(m) radius.
; Default is 0.40%, 40% monster health increase per player in radius.
gameDifficultyHealthScale = 0.3
 
; Adds additional players to the difficulty calculation in multiplayer unrelated to the actual amount.
; This option is disabled if its set to 0.
extraPlayerCountNearby = 0
 
; Sets the nearby player count always to this value + extraPlayerCountNearby.
; This option is disabled if its set to 0.
setFixedPlayerCountTo = 0
 
; The range in meters at which other players count towards nearby players for the difficulty scale.
difficultyScaleRange = 175
 
; If you set this to true, all portals will be disabled.
disablePortals = false
 
; If you set this to true the console will be force enabled in-game, false will force disable it.
forceConsole = false
 
;If you set this to true, portal names will be displayed in big text in center of screen.
bigPortalNames = false
```

You have `forceConsole = false`. That force disables the console.
Set that value to true, to enable the console.
