### ISSUE TITLE
Config override file for hosting providers

### ISSUE THREAD

**Issue by pingupdatebrian** [valheimPlus/ValheimPlus#547]
We'd like to give clients access to upload their own plus configs but cannot due to the ability to bypass player slot limits (and possibly other hosting provider impact settings). If we could get an override config file we can use to lock in specific settings that will ignore the same settings in the normal plus config that would resolve this issue and improve player experience.

**Comment by Mixone-FinallyHere** [comment]
Our mod's config sync goal is to give server owners the freedom to set their configuration values. We will not actively create a system that explicitly blocks our users via disabling certain aspects as per the wishes of the underlying infrastructure.

Many channels are available to hosting platforms to do this such as using filesystem locks or attaching their own code to achieve this intended goal.

It is neither the view, nor the goal, of Valheim Plus to be locked down. We develop the mod to 'unlock' the standard Valheim features and add quality of life changes. You are free to block your users from doing things, but this is not, nor will it be, a thing our mod does.
