### ISSUE TITLE
[BUG] Sync issue between server config file and local config file

### ISSUE THREAD

**Issue by 10thTARDIS** [valheimPlus/ValheimPlus#550]
- **OS:** Windows clients using r2modman, Linux server running AMP
- **Valheim Game Version:** 0.150.3
- **V+ Mod Version:** 0.9.7

**Describe the bug**

Configuration synchronization when using r2modman appears to be broken.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Launch ValheimPlus using r2modman
2. Connect to dedicated server
3. Check to see if the local configuration file has updated to match the server's config file, and notice that it has not updated.

**Expected behavior**

When connecting to dedicated server, the server configuration file should be synced to the client.

**Troubleshooting**

Server configuration has been updated, and the server console shows that clients are being sent the updated configuration when they connect, but the local config file is not updating.  Manually changing the local file continues to work, so this appears to be an issue with the config file not syncing.

Issue appears to have begun after the latest Valheim update, but I'm unable to test whether that's the result of the update, or just when we first noticed it happening.

This issue is occurring with the three clients that regularly connect to my server.  I've attached my server config for reference; I've verified that server sync is turned on.  I've also attached the BepInEx console output showing that it *should* have synced the configuration file.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
- Server configuration: https://pastebin.com/6gCn9SK1
- BepInEx console output: https://pastebin.com/mp5A8wSn

**Additional context**

Other mods installed: BepInEx Pack_Valheim, Clock, HoldAttack, and WeylandMod.  All of these mods have been installed together for about a month without issues.

**Comment by healiha** [comment]
This is not the way V+ config sync works.

When a client connect to the server, the configuration which's retained in memory is synced to the one from the server.

V+ do not directly update the _client configuration file_ and it didn't in the previous versions either.

**Comment by 10thTARDIS** [comment]
Okay, I must have misinterpreted what the config sync does, then.  My bad, sorry for the confusion.
