### ISSUE TITLE
[FEATURE REQUEST] Lux Reproduction

### ISSUE THREAD

**Issue by marvinej** [valheimPlus/ValheimPlus#555]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Is your feature request related to a problem? If so, please describe.**
It doesn't make any sense that you can tame a lux but they can't reproduce.

**Describe the solution you'd like**
Allow Lux Reproduction as a configurable option

**Comment by Mixone-FinallyHere** [comment]
This requires custom models and comparatively big changes

It is not a matter of simply pressing on or off

Need to create:
- A baby Lox model
- Give it all the appropriate code of Growup
- Create vfx and sfx for birth and love of Lox
- Add Procreation script to Lox with correct signatures
- Ensure it all is persistent

As the changes required would render the scripts breakable if the config option to be turned off this is not something that we consider could appropriately be a part of the core V+ experience.

If one of our team members creates such a mod we will ensure compatibility, but at this point this will not be a core aspect of v+ as it requires too many additions that could easily break things.

**Comment by Mixone-FinallyHere** [comment]
It is also worth mentioning, that this does sounds like something that the core game will introduce via updates at some point, which would render a humongous amount of work on our part essentially useless.
