### ISSUE TITLE
[BUG] Blast Furnace with "allowAllOres = true" can't smelt scrap iron

### ISSUE THREAD

**Issue by Immeline** [valheimPlus/ValheimPlus#557]
- **OS:** Linux Server + Windows Client
- **Valheim Game Version:** 0.150.3
- **V+ Mod Version:** 0.9.7

**Describe the bug**

WIth "allowAllOres = true" under [Furnace] on my linux server, the blast furnace can smelt everything EXCEPT scrap iron.

**To Reproduce**

Just try to smelt scrap iron in a blast furnace with "allowAllOres = true" on, it will say you have no processable items.

**Expected behavior**

I assume it should be able to smelt scrap iron like a smelter could.

**Troubleshooting**

I tried every other ore (Silver and Below) and it works just fine.

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/i0tmzmxA

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

I only have the "Use Equipment in Water" mod found here: https://www.nexusmods.com/valheim/mods/121

**Comment by nxPublic** [comment]
This has been resolved already.

#523
