### ISSUE TITLE
[BUG] error in description of [Armor] in cfg file

### ISSUE THREAD

**Issue by ljm42** [valheimPlus/ValheimPlus#560]
- **OS:** All
- **Valheim Game Version:** N/A
- **V+ Mod Version:** 0.9.7

**Describe the bug**

There is an error in the description of [Armor] in the cfg file:

https://github.com/valheimPlus/ValheimPlus/blob/fb367f9c7e48febf6810a447efcb23a90a0529a4/valheim_plus.cfg#L493

I believe `durability` in this comment should be `armor`:

; The value 50 will increase the armor from 14 to 21. The value -50 will reduce the `durability` from 14 to 7.

**Comment by nxPublic** [comment]
Fixed for 0.9.8
