### ISSUE TITLE
[FEATURE REQUEST] Wagon/Cart Ownership

### ISSUE THREAD

**Issue by marvinej** [valheimPlus/ValheimPlus#563]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Is your feature request related to a problem? If so, please describe.**
When setting player-built things to invincible it makes it so you cant disassemble and move your cart thru a portal or take it with you easier.

**Describe the solution you'd like**
Setup a Cart-Ownership so only the owner of the cart can destroy it, or if that's not possible add a separate configuration for cart invincibility similar to boats.

**Comment by nxPublic** [comment]
#715
