### ISSUE TITLE
[FEATURE REQUEST] Craft multiple Items at once

### ISSUE THREAD

**Issue by SecretUnicorn** [valheimPlus/ValheimPlus#565]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Describe the solution you'd like**
Add a number field next to the craft button which will consume x times the resources but will craft x items

**Additional context**
There is an mod out there which kinda does the same but wont work together with v+ so it is not an option ;)

**Comment by nxPublic** [comment]
Results in too much UI manipulation that would most likely break any other mod working with it remotely.
