### ISSUE TITLE
[BUG] Valheim Crash after updated (0.153.2)

### ISSUE THREAD

**Issue by bailboy91** [valheimPlus/ValheimPlus#567]
PopOS 21.04 / Windows 10 
Game Version : 0.153.2
- **V+ Mod Version:** 0.9.7

**Describe the bug**

During start up of valheim  / valheim plus after the Lions Gate logo the game immediately crashes. 

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Update game from steam
2. Luanch game
3. Crash

**Expected behavior**
Game to launch, valheim plus to load and mods to load. 

**Troubleshooting**

Tested in both windows and linux. 
Updated graphics drivers. 
Reinstalled valheim plus.  
Removed additional mods and tested
started game with out any mods or v+ and it loaded fine. 

**Screenshots**

Pastebin link of crash from error.log from linux. 
[V+ Crash Log](https://pastebin.com/Bunn5uND)

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
Quickconnect
Unrestricted portals
betterUI

**Comment by ncjsvr** [comment]
This is an issue with the unstripped dll files. It has been fixed already, please download the latest release again and replace existing files (except your config).

**Comment by bailboy91** [comment]
That was it. Thank you @ncjsvr !
