### ISSUE TITLE
[BUG] Valheim not running after Update to 0.153.2

### ISSUE THREAD

**Issue by MagisterSiltar** [valheimPlus/ValheimPlus#568]
- **OS:** Windows Client
- **Valheim Game Version:** 0.153.2
- **V+ Mod Version:** 0.9.7

**Describe the bug**

An exception occurs when Valheim is started.
`[Error: Unity Log] Unable to find method SendPrewWillRenderCanvas in [UnityEngine.UIModule.d11] UnityEngine.Class`

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Start Valheim

**Expected behavior**

Playable Valheim

**Troubleshooting**

Non

**Additional context**

ValheimPlus is the only mod I have installed.

**Comment by nxPublic** [comment]
Already had been fixed.

Read the release note for 0.9.7.

The files on the 0.9.7 release have already been updated.

**Comment by anthony-hull** [comment]
I found this confusing as there wasn't a new release and was waiting to see that appear in the github release artefacts page.

Possibly increment and make a new tag for a new minor version number when you update dependencies?
