### ISSUE TITLE
[BUG] Unable to find method SendPreWillRenderCanvases

### ISSUE THREAD

**Issue by SuperBartimus** [valheimPlus/ValheimPlus#569]
Win10 Pro 20H2
Valheim 0.153.2
BepInEx 4.5.11.0
V+ Mod Version: 0.9.7,

- **Describe the bug**
Steam updated game client
started game client ... before the initial Valheim screen, the game client crashes.
This occurs on two separate PCs running the same game client version and same BepInEx / V+ version.  OSes: Win10Pro on both devices, but different builds

Viewing BepInEx\LogOutput.log, error produced is:
[Error  : Unity Log] Unable to find method SendPreWillRenderCanvases in [UnityEngine.UIModule.dll]UnityEngine.Canvas

**To Reproduce**
Steps for the devs to reproduce the behavior:
repeat 'description of the problem'
 with same versions

**Expected behavior**
Should be at the welcome screen

**Troubleshooting**
Tried reapplying BepInEx and V+ mods 

**Screenshots**
none available

**Additional context**
no other mods installed

[LogOutput.log](https://github.com/valheimPlus/ValheimPlus/files/6469850/LogOutput.log)

**Comment by nxPublic** [comment]
Duplicate. Read #568
