### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adahlmanpinterest** [valheimPlus/ValheimPlus#570]
- **OS:** [Windows Server]
- **Valheim Game Version:** [153]
- **V+ Mod Version:** [0.97]

**Describe the bug**

Updated Valheim Plus to the latest version, using the windows server.zip provided, dragged and dropped the updates into my c:\valheim folder. Updated the game via the steamcmd and verified the files. Starting the server I get a crash report that Valheim wont start.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Update Valheim via steam "force_install_dir C:\valheim app_update 896660 validate"
2. Remove files from windowsserver.zip and place them in c:\valheim
3a. Run start_server.sh 
3b.`:start
c:\steamcmd\steamcmd +login anonymous +force_install_dir c:\valheim +app_update 896660 validate +exit
:juststart
@echo off
set SteamAppId=892970

valheim_server -nographics -batchmode -name "Foo" -port 2456 -world "Foobar" -password "bar"`
4. Crash

**Expected behavior**

Validate the files and start the server

**Troubleshooting**
Removed all files in valheim_data\managed. Removed all valheim plus files. Validated install and reinstalled. 

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
[Error Log](https://pastebin.com/y7x6MvJ0)

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by Mixone-FinallyHere** [comment]
This is not a plus crash
