### ISSUE TITLE
[BUG] Incompatibility with Serverside Simulations

### ISSUE THREAD

**Issue by jsza** [valheimPlus/ValheimPlus#573]
- **OS:** Windows + Linux Server
- **Valheim Game Version:** 0.153.2
- **V+ Mod Version:** 0.9.7

With [Serverside Simulations](https://www.nexusmods.com/valheim/mods/863) installed on a dedicated server, VP's auto-fuel feature doesn't function. This is because Serverside Simulations creates and owns `Smelter`s on the dedicated server, where `Player.m_localPlayer` is `null`.

AFAICT, removing the `!Player.m_localPlayer` check [here](https://github.com/valheimPlus/ValheimPlus/blob/development/ValheimPlus/GameClasses/Smelter.cs#L151) should be sufficient to solve this in particular, and there's another potential problem with `ItemDrop.TimedDestruction` [here](https://github.com/valheimPlus/ValheimPlus/blob/799a52a225487cc52e01a3cd77b37aa0e50be048/ValheimPlus/GameClasses/ItemDrop.cs#L71).

**Comment by Mixone-FinallyHere** [comment]
If we remove that check there then it will cause bugs when NOT using Serverside simulations

**Comment by jsza** [comment]
Thanks for the reply! To keep everyone up to date, I mentioned to @nxPublic on Discord we'd be adding compatibility from our end. (this wasn't nearly as straightforward issue as I'd thought, looking at the ward access checks and such)

Might be worth revisiting at a later date if it's worth changing in VP, once we have our compat patch worked out? I'll keep you posted.
