### ISSUE TITLE
[FEATURE REQUEST] When a new BepInEx is released, instead of updating assets, please make a new release

### ISSUE THREAD

**Issue by adaliszk** [valheimPlus/ValheimPlus#574]
**Is your feature request related to a problem? If so, please describe.**
Automated systems don't pick up an update on asset changes in the releases, manual trigger is required to rebuild images.

**Describe the solution you'd like**
When you guys need to update the assets, just create a new release just like you did on Nexus, you can tag the old version's commit when you create it, it should be fairly simple.

**Additional context**
I know it might be a bit of extra chore, but this would be really helpful for automation.

**Comment by BrainStone** [comment]
If possible please do that for the current 0.9.7(.1) release (and revert back the files for 0.9.7)

**Comment by adaliszk** [comment]
The only issue I can see with a commit right now that you would need to rebase the history to put one in right after the already tagged one. Though most of the time this is solved by having a "release" branch where only commits with a release are there and any updates are stored on a develop one.

**Comment by BrainStone** [comment]
Or create a new commit based on the tag and then merge it back into the main branch if you need to. The commit could also just be left there. Nothing says that it needs to be merged back.

**Comment by nxPublic** [comment]
We will be publishing new releases for future BepInEx versions.
