### ISSUE TITLE
[BUG] - Carry Weight / Stack sizes not applying on multiplayer games 

### ISSUE THREAD

**Issue by sbtoonz** [valheimPlus/ValheimPlus#580]
- **OS:** Windows client Linux Server
- **Valheim Game Version:** 0.153.2
- **V+ Mod Version:**  0.9.8

**Describe the bug**

I set the toggles for inventory stack and weight = true
adjusted as I pleased

Settings apply on local play 

I uploaded config to server
rebooted server
log into server

Stack settings and carry weight do not apply 

**To Reproduce**

Steps for the devs to reproduce the behavior:
1 install v+ 0.9.8 client and server
2 set server config to adjust carry and stack 
3 login with character 
4 experience failure 

**Expected behavior**

When I set itemstack and carry weight edits = true I expect them to effect my player 

**Troubleshooting**

Other than local vs server and ensuring cfg on server is 1:1 with local not much lse 

**Additional context**
Supposedly CLLC updated to change a bug that impacts carry weight but i didnt suffer this issue on V+ 0.9.7 with my modlist

**Comment by nxPublic** [comment]
We are in contact with the developer of CLLC.

You have to either use our stack size changes or theirs.

**Comment by sbtoonz** [comment]
Confirmed 
disabling ItemControl.yml in CLLC solves this bug
