### ISSUE TITLE
[BUG] Arrow Information

### ISSUE THREAD

**Issue by KillFacePT** [valheimPlus/ValheimPlus#583]
- **OS:** [Linux Server]
- **Valheim Game Version:** [0.153.2]
- **V+ Mod Version:** [0.9.8]

**Describe the bug**

Arrow information disappears when gather something

**To Reproduce**

1.Gather something from the floor
2.Notification will show and arrow information will desappear

**Expected behavior**

When the notification disappears the arrow information should appear again

**Troubleshooting**

Probably it's a coding issue and i don't code =X

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

https://pastebin.com/BpAybV9s

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
 no additional mods only v+

**Comment by KillFacePT** [comment]
https://youtu.be/HpUqYLPHv-Y

**Comment by KillFacePT** [comment]
Seems to be when a item enters into the shortcut bar

**Comment by KillFacePT** [comment]
Some more testing done and when you take the bow of the bar and put it back on, the count shows up again. Also noticed that when you move something to the bar it still shows but when you have the chest open and you move something to the bar it dissapears(the arrow count).

**Comment by GeneCupstid** [comment]
May require a new issue, but somewhat related:

It looks like the numerator is being drawn on both sides of the `/`, i.e., `x/x` instead of `x/y`.

![image](https://user-images.githubusercontent.com/56445225/119214801-28a62980-ba8f-11eb-9953-118cef9e50d9.png)

**Comment by KillFacePT** [comment]
> May require a new issue, but somewhat related:
> 
> It looks like the numerator is being drawn on both sides of the `/`, i.e., `x/x` instead of `x/y`.
> 
> ![image](https://user-images.githubusercontent.com/56445225/119214801-28a62980-ba8f-11eb-9953-118cef9e50d9.png)

Mine shows x/y 
x= current arrow y=total arrows

Make sure that you have 2 types of arrows

**Comment by GeneCupstid** [comment]
Ok, I thought it was supposed to show how many out of a stack remains.  But if all arrows stack to 100, that wouldn't be super helpful anyway.  It could just show the one number if only one kind of arrow, or maybe a `-`, but I'm not trying to nitpick.  You guys have done an amazing job here, and I know that edge cases / "just one more `if`", is a pain in the ass.  :)

**Comment by KillFacePT** [comment]
For example: you have 78 fire arrows, 10 frost, 12 needles, 120 wood, and you selected the frost it will show: frost 10/220

**Comment by GeneCupstid** [comment]
Ya, I'm thick... I get it now.  

I guess I just never carry around more than one stack of arrows, otherwise that would be more obvious for me.  Precious inventory space and all that...  anyway, thanks for that info, and a splendid application you guys have created here.  

I'll be subscribing to the Patreon as long as I'm actively playing the game.  And that doesn't look to be stopping any time soon. 
 :revolving_hearts:

**Comment by nxPublic** [comment]
Thank you guys for delving this deep into the bug! I really appreciate it!

Thanks for your support ❤️

**Comment by nxPublic** [comment]
Addressed by #626
