### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by H4NN4H24** [valheimPlus/ValheimPlus#585]
- **OS:**Windows Server (ZAP Hosted)
- **Valheim Game Version:** [6663905
- **V+ Mod Version:** [e.g. 0.9.81

Cannot mark map

After the new update, all players on the server cannot make marks on their map. 

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Go to 'Map
2. Click on '.any icon
3. Try to mark map

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here
No other mods installed .

**Comment by Mixone-FinallyHere** [comment]
This is being fixed since yesterday

Up to date info on progress can be found in our discord

**Comment by nxPublic** [comment]
This should be resolved with 0.9.8.1, please open a new report if the issue continues.
