### ISSUE TITLE
source location of run_bepinex.sh

### ISSUE THREAD

**Issue by lloesche** [valheimPlus/ValheimPlus#59]
I'm looking for the sources of `run_bepinex.sh` from `UnixServer.zip` release bundle. I can't seem to find it in this repo.
I'd like to submit a PR that makes the hard coded line
```
"${PWD}/${executable_name}" -name "servername" -password "serverpassword" -nographics -batchmode -port 2456 -world "world"
```
use dynamic arguments.

**Comment by nxPublic** [comment]
Version 0.8.5 contains a new unix version of BepInEx
