### ISSUE TITLE
Release naming inconsistency for Github and other sources

### ISSUE THREAD

**Issue by scaytrase** [valheimPlus/ValheimPlus#590]
Some time ago 0.9.8 was released and published on [nexusmods](https://www.nexusmods.com/valheim/mods/4?tab=files)
There is no stability markers there on the versions, but on GH release - we have [STABLE] markers.

So when installing mods using nexusmod or [valheim.plus](https://valheim.plus/installation) site - we download latest version possible (because of no markers there and direct download also points to latest release. But on GH for some reason releases are marked as `[STABLE]` manually, which is (unfortunately?) used by [some automation tools](https://github.com/dyoung522/valheim-plus-installer/blob/main/src/helpers/release_info.ts#L13)

So my question is whether these stability markers are really used? or should we stick to `latest` version always (excluding `pre-prelease` GH feature)

**Comment by nxPublic** [comment]
Oh, sorry! That was lost with me having to reupload the tag to fix issues with the configuration file we published.

I will change this immediately, this was unintentional.

**Comment by scaytrase** [comment]
Thanks a lot!
