### ISSUE TITLE
[FEATURE REQUEST] Fastswitch between custom hotbar menus

### ISSUE THREAD

**Issue by rzwahr** [valheimPlus/ValheimPlus#593]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Is your feature request related to a problem? If so, please describe.**
No

**Describe the solution you'd like**
It would be useful to have the ability to switch between multiple hotbar menus (items 1-8).  For example I use totally different items when building, adventuring, terraforming, etc.  Rather than having to drag and drop items 1-8 depending on the tasks I am performing, having a control or hotkey to quickly cycle through custom taskbars would be awesome.  I don't know if this can be done through the V+ mod or if this would be a feature the game devs would have to add.  If so please advise and I will submit this request to them directly.

**Comment by nxPublic** [comment]
This is a nightmare to program in practice with what we have available to us.
