### ISSUE TITLE
[BUG] Missing mono-2.0-bdwgc.dll

### ISSUE THREAD

**Issue by f1ames0ff** [valheimPlus/ValheimPlus#594]
CONTRIBUTING.md says:

`Copy .\libraries\Debug\mono-2.0-bdwgc.dll from this repo to <Valheim>\MonoBleedingEdge\EmbedRuntime and overwrite the existing file.`

But there's no such file.

Please fix the description or add the file.

**Comment by nxPublic** [comment]
![image](https://user-images.githubusercontent.com/39051287/119466525-8d64bc80-bcf9-11eb-8e74-fdc3e6fc5712.png)

**Comment by f1ames0ff** [comment]
@nxPublic 
![image](https://user-images.githubusercontent.com/5371279/119497567-09481e80-bd65-11eb-8407-8156057fe142.png)
