### ISSUE TITLE
[BUG] [FireSource] issue: Fire vs Torch-Type

### ISSUE THREAD

**Issue by GeneCupstid** [valheimPlus/ValheimPlus#596]
- **OS:** Windows Dedicated Server (dathost)
- **Valheim Game Version:**  0.153.2
- **V+ Mod Version:** 0.9.8.1

> Feel free to contact me on Discord, I'm in V+ server as `cupstudio`!

## [FireSource] issue: Fire vs Torch-Type

Even with `[FireSource]::fires` set to false - all fire sources, both torch-type and non-torch-type remain at 10 fuel continually, and are created at 10 fuel.  Server and client configuration files have always had `fires = false`.  The `torches` option has always been set to `true`.  I've attached a copy of the V+cfg running on the server, and included the server's `[FireSource]` section here for reference.

Both my client and server are using the exact same configuration file, though the server is set to override configuration anyway.

> *valheim_plus.cfg:*
```
[FireSource]

; Change false to true to enable this section. https://valheim.plus/documentation/list#FireSource
enabled = true

; If set to true, torch-type fire sources will stay at max fuel level once filled.
; Applies to: wood torches, iron torches, green torches, sconces and brazier.
torches = true

; If set to true, non torch-type fire sources will stay at max fuel level once filled.
fires = false

; Automatically pull wood from nearby chests to be placed inside the Fire as soon as its empty.
autoFuel = false

; This option prevents the Fire to pull items from warded areas if it isn't placed inside of it.
; For convenience, we recommend this to be set to true.
ignorePrivateAreaCheck = true

; The range of the chest detection for the auto fuel features.
; Maximum is 50
autoRange = 10
```

### To Reproduce
I can't guarantee this would happen on a fresh install, and I suspect it may have something to do with migrating from 0.9.7 to 0.9.8 (or .1), as this functionality worked properly a week ago or so.  I'll wipe the server if this turns out to be a difficult one to reproduce.

1. Edit config, `[FireSource]` section: 
    - `enabled = true`
    - `torches = true`
    - `fires = false`
    - all other options in this section remain at default.
    
2. Restart Server

3.  Connect Client

4.  Build campfire

5. Campfire starts out at 10 wood, even if you only had 2 wood in your inventory to build the fire.  It also never goes below 10 fuel.

### Expected behavior

Based on the configuration above, I'd expect fires, bonfires, etc to consume wood as normal, and torch-types to remain at full fuel permanently.

### Troubleshooting

- I've tried toggling the setting off and on again, disabling / enabling the section, restarting server between changes.  When the section is disabled, fires and torches both go back to default behavior (requiring fuel).  When re-enabled, the issue described here persists, regardless of whether or not the `fires` section is `true` or `false`. 

### Server Config + Log
- [valheim_plus.txt](https://github.com/valheimPlus/ValheimPlus/files/6543129/valheim_plus.txt)
[v_server.log](https://github.com/valheimPlus/ValheimPlus/files/6543257/v_server.log)

### Additional context

I know that this was working as intended a week ago, and no changes to the cfg file have been made other than accommodating updates from the `0.9.8`  and `0.9.8.1` update.

### Mods

I've only ever used 2 mods aside from V+, and having these enabled / disabled doesn't seem to make a difference to this issue:

1. CropReplant
2. FarmGrid

**Comment by megalobrainiac** [comment]
I would guess it is this commit https://github.com/valheimPlus/ValheimPlus/commit/f1818a42aed9b455fdc9b9c8a5559a45da160f87

Looks like the brazier is still **$piece_brazierceiling01** in Unity Explorer so not sure why it was changed to **$piece_fire** which I'm guessing is matching all fire sources

**Comment by healiha** [comment]
@megalobrainiac thanks for the report.

I'll take a look at it later today.

When I changed **$piece_brazierceiling01** to **$piece_fire** it was because it had been changed (maybe wrongly) by the devs. It might have been reverted, I didn't check since then.

I'll keep you updated!

**Comment by Rusty-Shackleford** [comment]
Thanks guys :D
