### ISSUE TITLE
[BUG] Client UI does not express inventory row count configured in the server (server has more)

### ISSUE THREAD

**Issue by hagfelsh** [valheimPlus/ValheimPlus#597]
- **OS:** Windows client + Linux server
- **Valheim Game Version:** 0.153.2 (build 6663900)
- **V+ Mod Version:** 0.9.8.1

**bug description**

The client inventory panel size expands to what should be 6 rows (as is configured on the server), but the 2 extra rows of inventory spaces themselves are missing.  Screenshot attached.

**To Reproduce**

1. Start client via steam
2. Pull lloesche's valheim server container and start it (https://hub.docker.com/r/lloesche/valheim-server)
3. Pick any character, log in
4. Open your inventory

**Expected behavior**

The server is configured for 6 rows, the Client should offer 6 rows.

**Troubleshooting**

I've tried on 4 different machines, each with different accounts.  
I've tried brand new character files, too.
I tried the previous version of V+ too (forgot the version number sorry!)

**Screenshots**

![20210526091542_1](https://user-images.githubusercontent.com/6445682/119683600-64335180-be09-11eb-9de9-a02259428667.jpg)

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
[valheim_plus.cfg](https://pastebin.com/Ga4xS2ke)

**Other Installed Mods**

- AnyPortal
- BetterArchery
- CookingStationTweaks
- CustomTextures
- MapSharingMadeEasy
- PaddlePower
- PlantingPlus
- QuickConnect
- ShowContainerContents
- SleepWithoutSpawn
- SmartContainers

**Comment by nxPublic** [comment]
I cannot reproduce this issue with 0.9.8.1 manually installed on my local server when connecting to it.

Are there any error logs?

**Comment by hagfelsh** [comment]
I'll look!  Is there a place they usually settle?  Or is there a config option to increase verbosity?

**Comment by nxPublic** [comment]
Just the console.

**Comment by Mixone-FinallyHere** [comment]
@hagfelsh this is a known issue of BetterArchery

The dev of BetterArchery adds two fake rows and removes them to use quiver if I remember correctly

If you remove BetterArchery or disable their quiver the rows should reappear

I have not seen activity on that mod in a month so I am not sure if it is being fixed or not, but there is nothing we can do on our side to prevent this as if we add any code to make those rows not move, betterarchery will encounter issue as well

**Comment by hagfelsh** [comment]
You nailed it.  Thanks everyone.  I had disabled the quiver on the server side, but never thought to do so on the client side.  I assumed that the server's configs would overrule the client's.  Nope! 

By the way--the quality of the workmanship in Valheim Plus is top notch.  You're doing great work and have set a very clear standard for what a quality mod should look like.  Thank you!
