### ISSUE TITLE
[BUG] noTeleportPrevention = false but can still teleport ores etc

### ISSUE THREAD

**Issue by Koproliet** [valheimPlus/ValheimPlus#599]
- **OS:** Linux server + linux client. Will ask someone with a windows client to also test, in case that helps. Sync for config settings is turned on from server -> clients.
- **Valheim Game Version:** 0.153.2
- **V+ Mod Version:** 0.9.8.1

**Describe the bug**

It seems it started since upgrade of Valheim to 0.153.2 + plus mod to 0.9.8. Persists with 0.9.8.1. 
As it says in the title. We use the Plus mod for some QoL things, torches keep on burning, workbench range,... but not for something that would seriously alter the game like being able to teleport ores. It has always worked ok but since these latest updates we can now teleport ores even with noTeleportPrevention = false. 

**To Reproduce**

Steps for the devs to reproduce the behavior:
I included the config file as we use it on the rented server below for reference via pastebin.
I also included the console output from the server where we run it. I could not find any errors/warnings that seemed relevant. 

**Expected behavior**

No possibility to teleport ores. 

**Troubleshooting**

What steps have you taken to try to fix?
Turned the section to true while leaving noTeleportPrevention to false. 
Stopped server, waited, turned noTeleportPrevention to true. Started server. Waited. Stopped server. Turned noTeleportPrevention to false again and started server again. All no effect. 

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
Config file:
https://pastebin.com/vj7GHavK    (modified, I pasted the default config file first, this is the correct one)
Console output:
https://pastebin.com/he76Sn3L

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by Mixone-FinallyHere** [comment]
I have gone over the code again but there is no instance in which this should occur:
```cs
if (Configuration.Current.Items.IsEnabled && Configuration.Current.Items.noTeleportPrevention)
{
    __instance.m_itemData.m_shared.m_teleportable = true;
}
```
and
```cs
    [HarmonyPatch(typeof(Inventory), "IsTeleportable")]
    public static class noItemTeleportPrevention
    {
        private static void Postfix(ref bool __result)
        {
            if (Configuration.Current.Items.IsEnabled)
            {
                if (Configuration.Current.Items.noTeleportPrevention)
                    __result = true;
            }
        }
    }
```

are the only places we modify teleportation

As you can see it is an absolute check, there is no calculations or logic, either it is on or off

Are you sure you are not using any other mod that would allow you to do this?

**Comment by Koproliet** [comment]
I did also look at the same code and the recent changes/commits in the meantime, and indeed nothing indicated anything there either. 
Also (unless I missed something in there) , the console output from the server seems indicate that it loads the related settings correctly, so I was at a loss. 

On the server side (hosted at Nitrado), the only mod that is supported/available is Valheim plus. On the client side, I only have Bepinex and bepinexpack_valheim. 
Other players on the same server are quite inactive until hearth and home comes out, but I asked them to also check if they have the same issue, before I start reinstalling it from scratch on my client's side. The other run windows on the client side instead of Linux also. Maybe it can give some next clue, I'll come back once I have feedback. 

Extra note, I checked the config file on my client, it is set to "false" there as well. And the logs on server and client seem to tell me that settings are successfully synced between server and client.

**Comment by Mixone-FinallyHere** [comment]
Do the items have the teleport prevention icon?

**Comment by Koproliet** [comment]
Yes they do. 

But digging further, and it might be PEBKAC after all:
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [UnrestrictedPortals 1.3.1.0]
[Info   :   BepInEx] Loading [Valheim Plus 0.9.8.1]

I did not change/add/... any mods except for updating them since, well, months. Not sure why the behaviour/effect changed more recently, does not make any sense. I'll check/remove and close this bug if that was effectively "it"...

**Comment by Mixone-FinallyHere** [comment]
No worries!
