### ISSUE TITLE
Sharable Pins not working

### ISSUE THREAD

**Issue by leghammer-git** [valheimPlus/ValheimPlus#602]
- **OS:** Linux (Arch) - Manjaro KDE
- **Valheim Game Version:** 0.153.2
- **V+ Mod Version:** 0.9.8.1

Pin sharing not working

Testing with a friend (Win10. Same game/mod versions). Could not get shared pins to work with or without shareAllPins enabled. Pins only appeared for the creator regardless if the 'Share This Pin' checkbox was ticked. Map section is anabled in the config and shareablePins is also enabled along with shareMapProgression and showCartsAndBoats. Problem persists on both hosted and dedicated games.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. V+ config: `[Map]
enabled=true
shareMapProgression=true
exploreRadius=100
preventPlayerFromTurningOffPublicPosition=false
shareablePins=true
shareAllPins=false
showCartsAndBoats=true`
2. Host game or use a configured dedicated server
3. 'M' to open map
4. Double-click to pin location
5. Enter pin name, choose to share pin, optionally set a pin indicator
6. Compare map pins with other connected players

**Expected behavior**

Expected a pin I create to appear for other currently connected players.

**Troubleshooting**

Tried hosting the game via Linux and Windows as well as Linux dedicated host. Tried with and without shareAllPins enabled.

**Additional context**

No other mods.

**Comment by Mixone-FinallyHere** [comment]
We are working on some issues we are seeing on this feature
Behaviour is a bit erratic and we are still pinpointing (no pun intended) what is in common with reported issues on this

We have enough reports of it working correctly that we know the issue is not a core issue, i.e. it does work, but we are seeing more than enough reports of it not working to be considering a code overhaul of this area

**Comment by leghammer-git** [comment]
Happy to share any logs or anything that might help.

**Comment by Mixone-FinallyHere** [comment]
Please do share the player logs of all users that were on server as well as server logs if possible

**Comment by prototype464** [comment]
Can confirm I am also having this issue on the latest version. Everyone on the server is using the same mods, in the same mod version.

I looked at my player.log, and it shows this:
```(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

08/09/2021 16:31:44: Sent map pin to all clients
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

08/09/2021 16:31:44: Sent map pin to all clients
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

08/09/2021 16:31:44: Sent map pin to all clients
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

08/09/2021 16:31:44: Sent map pin to all clients```
Yet no one on the server has my pins and vice versa

**Comment by frenkye** [comment]
Just testing mod with pin share, we had problem with always sharing like there is no sleep maybe in updating pins? When we start checking map 0 fps.

But with no force shared pins, all the pins checked are share no problem.

Just a thought.

**Comment by FlorpyDorpinator** [comment]
I also am having this same issue. Log in and there are no pins then when I double click to make a pin everything appears. If I do it within a minute of logging in the game drops FPS, then I log out, log back in, FPS is fine and pins/sharing works fine. If I wait longer the game will crash. 

My buddies on the server are having critical issues with this as well. Some have stopped opening the map altogether. I will attempt what Frenkye attempted and stop forced pin shares to see what happens.

**Comment by nxPublic** [comment]
#610 instead.
