### ISSUE TITLE
[BUG] Unable to use startup parameter with V+ (+connect host)

### ISSUE THREAD

**Issue by JakeDEvans** [valheimPlus/ValheimPlus#605]
- Win10 20H2
- 0.153.2
- 0.9.8.1

**Describe the bug**

unable to automatically connect to dedicated serves with steam startup commands after installing V+

**To Reproduce**

Steps for the devs to reproduce the behavior:
https://nodecraft.com/support/games/valheim/how-to-quickly-find-and-join-your-valheim-server 
1. Steam Library
2. Right-Click game, Properties
3. General Tab
4. Launch Options
5. ``` -connect 192.0.2.10```
6. start valheim

**Expected behavior**

Valheim prompts for selecting your character and then connects tot he server

**Troubleshooting**

**Comment by Mixone-FinallyHere** [comment]
Please provide more info
This bug report is lacking in details that would enable us to provide any type of support

**Comment by JakeDEvans** [comment]
Are you unable to reproduce the issue?

**Comment by Mixone-FinallyHere** [comment]
Without knowing parameters we are unable
Your IP, is public or private?
Are within vlan?
Firewall?
Can you connect without the command line arg?

All this info is required else the only thing we can try to reproduce is connecting automagically to any random ip which does not offer any relevant data

**Comment by JakeDEvans** [comment]
Connect to one of your servers? 
I've tried the public and private ip and it worked before installing V+

**Comment by Mixone-FinallyHere** [comment]
Does the server have v+ ?

**Comment by Mixone-FinallyHere** [comment]
Also the manual connect i meant with v+
Does manual connect with v+ work?

**Comment by JakeDEvans** [comment]
Yes the server has v+ and manually connecting works.

The issue is the startup parameter isn't working. Did it work for you? Are you able to reproduce?

**Comment by Mixone-FinallyHere** [comment]
Yes

Connecting via auto onto our dev server works

The IP you are using honestly looks not public, you should make sure your IP is properly accessible with something like: https://geekstrom.de/valheim/check/

And maybe use its public instead of private

**Comment by JakeDEvans** [comment]
The IP I provided is reserved for documentation,  neither public nor private.  If it works for you then close as unable to reproduce

**Comment by nxPublic** [comment]
I was also unable to reproduce your issue.
