### ISSUE TITLE
[FEATURE REQUEST] On PVE Death, Reset Just Skill Level progress

### ISSUE THREAD

**Issue by BMouser** [valheimPlus/ValheimPlus#609]
**Is your feature request related to a problem? If so, please describe.**
Currently in V+ you can control the multiplier used to determine how many levels are lost on death. This is done by scaling the builtin drain by a multiplier defined at `Player.deathPenaltyMultiplier`

**Describe the solution you'd like**
Myself and the people I play with would like to change the death penalty to simply reset the current level progress on death.
This doesn't appear possible since you cannot pass a factor of `0` into the base `player.LowerAllSkills`.

I'd like to see either 
1. A new configuration item that forces this behavior, this would mean that this value would supersede the multiplier setting if enabled.
2. Change the conditional logic at:
https://github.com/valheimPlus/ValheimPlus/blob/e7120106c02913047a3d5d513f9d626c201b2ef8/ValheimPlus/GameClasses/Skills.cs#L153
to be `>= -100.0f`.
This would require less change, but if users wanted to fully disable the skill penalty they'd have to change from `-100` in the config to something smaller, like `-101`.

**Comment by nxPublic** [comment]
This has nothing to do with the spirit of Valheim Plus which is quality of life.

**Comment by BMouser** [comment]
@nxPublic If the team isn't interested in adding feature that's OK, but to say 

> This has nothing to do with the spirit of Valheim Plus which is quality of life.

Seems little disingenuous since V+ already has the deathPenaltyMultiplier feature. I even linked the line of code related to the feature request.

Maybe the team regrets adding in support for deathPenaltyMultiplier back in May, but I respectfully disagree that this request is widely out of line with the existing functionality of the mod.
