### ISSUE TITLE
[BUG] Shared Pins wont work since today

### ISSUE THREAD

**Issue by mspoehrle** [valheimPlus/ValheimPlus#610]
-  Windows Client, Valheim Server : LLoesche Docker Server on Synology
-  0.154.1
-  0.9.8.2

**Describe the bug**

Since today we receive the following error messages in log file:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.GameClasses.MapPinEditor_Patches+Minimap_AddPin_Patch.Postfix (Minimap& __instance, Minimap+PinData& __result) (at <c87de6f72d524299b65a4e9dae6eb9c5>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::AddPin>(Minimap,UnityEngine.Vector3,Minimap/PinType,string,bool,bool)
Minimap.UpdateLocationPins (System.Single dt) (at <3d649eb5da984bc8a4d5b86d03245dc4>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::UpdateDynamicPins>(Minimap,single)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)

It repeats endlessly.

Within the Game when you open the map no Pin will be shown. Wether my own nor from other players.

After varios times the Pins appear on the map. But Framerates drop to zero. 

We tried a new Character without any own Pins on the map to check if our Characters may be the source of the problem. 
We reseted the Docker an reconfigured all
We reinstalled VH and VP

Other Mods

on Server-side: 
 only VP

on Client Side : 
 SimpleRecycling 0.0.13
 Epic Loot 0.7.10
 Extended Item Data Framework 1.0.1

**Comment by pwmcintyre** [comment]
same — in addition; the stones, bosses, and pings are all not working ... but only for some of the player in the game

**Comment by nxPublic** [comment]
We are aware of a few crucial issues related to the added Pin UI, they are not related to the new game update.

Next patch will have several changes to it.

**Comment by prototype464** [comment]
Also having this issue.

**Comment by FlorpyDorpinator** [comment]
I am also having this issue! I posted in the other instance of this bug. Happy to see that you guys know about it and will fix it...it's nearly ruining my server.

**Comment by nxPublic** [comment]
This should be fixed with 0.9.9.7, if not please re-open the issue or create a new one.
