### ISSUE TITLE
[BUG] Controller triggers reversed with V+ loaded

### ISSUE THREAD

**Issue by quickstophistory** [valheimPlus/ValheimPlus#612]
- **OS:** Windows Client
- **Valheim Game Version:** 0.155.7
- **V+ Mod Version:** 0.9.8.2

Starting game with V+ loaded (either manual installation or via Vortex) results in Xbox gamepad triggers (R+L, corresponds to attack+block) getting reversed. For some reason the gamepad profile doesn't get loaded correctly. Switching trigger order in Steam gamepad setup results in poor performance (slow response by triggers). Deactivating V+ solves issue. Occasionally, reloading the game resolves issue, but majority of game loads the triggers get reversed.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Load only most recent version of BepinX and V+ on a clean installation
2. Start game with Steam controller setup enabled
3. Attempt attacking/blocking with R+L triggers

**Expected behavior**

Attacking regularly with R trigger and blocking regularly with L trigger

**Troubleshooting**

What steps have you taken to try to fix?

Unloading/reloading V+ and selectively disabling mods, identified V+ as the culprit.

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

Just BepinEx. Tried other mods as well, issue only happens with V+. Issue might be with BepinEx??

_Thanks for a great mod!_

**Comment by quickstophistory** [comment]
Further experimentation shows that it's probably an issue with BepinEx...sorry!

**Comment by nxPublic** [comment]
Feel free to open a bug report to the [GitHub Repository of BepInEx](https://github.com/BepInEx/BepInEx) about it.
