### ISSUE TITLE
[BUG] Automation system is not working any more

### ISSUE THREAD

**Issue by krokarefr** [valheimPlus/ValheimPlus#615]
The automation system (objects being taken from chests and put into chests automatically) hasn't worked for some weeks now (since two Valheim updates ago). Tried everything, reinstalled and so on... still not working. This affects coal, wood, the smelter, the kettle, beehives and so on..,

**Comment by nxPublic** [comment]
Literally not true.

Join our discord to get to the bottom of your issues.
