### ISSUE TITLE
[BUG]Game crashes on log off - Nothing saved 

### ISSUE THREAD

**Issue by oanceamax** [valheimPlus/ValheimPlus#618]
- **OS: WINDOWS CLIENT
- **Valheim Game Version: 0.156.2
- **V+ Mod Version:**

**Describe the bug**

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Skills.Save (ZPackage pkg) (at <1b865f8b3455488592cdc401081112e3>:0)
Player.Save (ZPackage pkg) (at <1b865f8b3455488592cdc401081112e3>:0)
PlayerProfile.SavePlayerData (Player player) (at <1b865f8b3455488592cdc401081112e3>:0)
Game.SavePlayerProfile (System.Boolean setLogoutPoint) (at <1b865f8b3455488592cdc401081112e3>:0)
Game.Shutdown () (at <1b865f8b3455488592cdc401081112e3>:0)
Game.Logout () (at <1b865f8b3455488592cdc401081112e3>:0)
Menu.OnLogoutYes () (at <1b865f8b3455488592cdc401081112e3>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
UnityEngine.UI.Button.Press () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.EventSystem:Update()

A clear and concise description of what the bug is and how you found it.

It happens when I log off 

**To Reproduce**

when I exit game, nothing is saved  

**Expected behavior**

Save my progress! 

**Troubleshooting**

reinstall mod 
Reinstall Game 

**Screenshots**
CFG file
[valheim_plus1.txt](https://github.com/valheimPlus/ValheimPlus/files/6850264/valheim_plus1.txt)

**Comment by IFoundTheLight** [comment]
Downloaded configuration file, replaced mine with yours. 
Made a new server and a new character.
Copped down some trees.
Quit and Logout work normally issue, isn't being reproduced.

**Comment by oanceamax** [comment]
it was from a older version of mod/game solved it buy reinstall and driver
reinstall.

**Comment by spannerman79** [comment]
If indeed it was user sided error and not to do with V+ don't you think its best you close the issue @oanceamax ?

**Comment by oanceamax** [comment]
since i don't know what caused the problem in the first place, and it
happened multiple times that caused me hours of lost content i should let
you know, the issue. Glad you are on top of things!

**Comment by oanceamax** [comment]
Source of issue not found.

**Comment by spannerman79** [comment]
Well considering the following;

https://github.com/valheimPlus/ValheimPlus/issues/618#issuecomment-919580751 which replicated your setup and yet wasn't able to reproduce the issue, and then following you clearly state https://github.com/valheimPlus/ValheimPlus/issues/618#issuecomment-919880895 and I'll quote a snip

> it was from a older version of mod/game **solved it buy reinstall and driver
reinstall**.

To me, a system screw up, be it drivers or software other then V+ is **not** a V+ issue especially when you reinstall drivers etc.
