### ISSUE TITLE
[FEATURE REQUEST] Hugin Alerts the player to remote raids on the server.

### ISSUE THREAD

**Issue by Echoic1** [valheimPlus/ValheimPlus#619]
More detail:

I've been resetting my tutorial to get a heads up when someone else on the server is being raided.  This works beautifully in some ways. Like:

- Hugin pops up and delivers his message about raids.
- Then I know to check the map to see who is being raided and where.
- I emerge from a portal and save the day in heroic fashion.  Hooray!

The problem with this is that I have to dismiss Hugin a few dozen times every time I reset and Hugin's message is also triggered by local invasions. 

So ideally the mod would make Hugin appear and warn me every time there is a non local raid.  So that's the long and short of it.

Have a good one!

**Comment by nxPublic** [comment]
This has nothing to do with the spirit of Valheim Plus. Quality of Life.
