### ISSUE TITLE
[FEATURE REQUEST] Portals can only be built near boss sacrificial altars

### ISSUE THREAD

**Issue by adamcbuckley** [valheimPlus/ValheimPlus#621]
**Is your feature request related to a problem? If so, please describe.**
Portals are a blessing in the game, but they also remove some of the sense of danger, and they also dis-encourage players to build road networks.  Valheim Plus has the ability to disable portals altogether, but is there a middle ground?

**Describe the solution you'd like**
Portals can only be built in the vicinity of a rarely-occurring structure, for example a boss sacrificial altar.  Such a rule would influence where players choose to build their base.

An alternative would be that all altars are spawned when the map in generated. However, altars are initially disabled, and must be activated using e.g. surtling cores.

**Comment by nxPublic** [comment]
This has nothing to do with the spirit of Valheim Plus. Quality of Life.
