### ISSUE TITLE
[BUG] Map Pins not sharing (Vice-Versa)

### ISSUE THREAD

**Issue by prototype464** [valheimPlus/ValheimPlus#622]
- **OS:** Windows 10 Pro, locally-running server hosted via Steam
- **Valheim Game Version:** 0.156.2 (Latest)
- **V+ Mod Version:** 0.9.8.2 (Latest)

**Describe the bug:**
When I place map pins on the fullscreen map, my two buddies are not receiving them. But when one of them places a map pin, it shares between them, but not to me. I am hosting the world via Steam. We all have the same exact configurations as well, shared pins are enabled in the config on all 3 of our clients.

**To Reproduce:**
Place a map pin as host with everyone including host having shared pins enabled in their config, they will not receive it. Have 2 extra players in the server, have one place a pin. They both will see it, but you, as host, will not be able to.

**Expected behavior:**
For the feature to work lol

**Troubleshooting:**
Not much I can do to try and fix it other than the trial and error we did to find more info on the bug

**Link to PasteBin containing .cfg configuration if applicable:**
[ValheimPlus Config for all 3 players](https://pastebin.com/qNcg68x1)

**Mod configurations and player.log files for all 3 players:**
[ValheimModConfigs.zip](https://github.com/valheimPlus/ValheimPlus/files/6957403/ValheimModConfigs.zip)
[Player_Host.log](https://github.com/valheimPlus/ValheimPlus/files/6957402/Player_Host.log)
[Player_1.log](https://github.com/valheimPlus/ValheimPlus/files/6957406/Player_1.log)
[Player_2.log](https://github.com/valheimPlus/ValheimPlus/files/6957423/Player_2.log)

**Mods being used:**
_BepInEx_
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

_Valheim Performance Optimizations_
https://www.nexusmods.com/valheim/mods/1360?tab=files

_Valheim FPS Plus_
https://www.nexusmods.com/valheim/mods/1205?tab=files

_Custom Raids_
https://www.nexusmods.com/valheim/mods/278?tab=files

_Item Stacks_
https://www.nexusmods.com/valheim/mods/66?tab=files

_BetterAccuracy_
https://www.nexusmods.com/valheim/mods/404?tab=files

_No Bow Glow_
https://www.nexusmods.com/valheim/mods/1092

_Custom Textures (No Bow Glow dependency)_
https://www.nexusmods.com/valheim/mods/48?tab=files

_ValheimPlus_
https://www.nexusmods.com/valheim/mods/4?tab=files

**Comment by DiskImage** [comment]
I'm seeing this too, the map reveal shares but my friend didn't get the pins. When I open the sync dat file I just see a bunch of CSV numbers, nothing that looks like character encoding for the actual pin names I entered, though. Maybe that's just not saving? 🤔

**Comment by nxPublic** [comment]
Firewall,Anti Virus Firewall or Router issue.

This is due to the way the net code works in Valheim.

Nothing we can do about it.

**Comment by DiskImage** [comment]
Has this been escalated to the official Valheim bug tracker, then?
