### ISSUE TITLE
New ValheimPlus update?

### ISSUE THREAD

**Issue by cyberlimbo** [valheimPlus/ValheimPlus#628]
Hi

Valheim Plus stopped working..
Will you guys release a new update?

regards

**Comment by nxPublic** [comment]
We've already posted about this on our discord and our nexus page.

Guess i'll do it here too.

![image](https://user-images.githubusercontent.com/39051287/133623334-02373a7a-dc86-4d98-9e52-636a397cbc7a.png)

**Comment by nxPublic** [comment]
We have publish a working version accessible for everyone willing to take extra steps [in our discord server](https://discord.valheim.plus).

The changelog and other information can also be found there.

As soon as we are confident that there is no further major issues with the version, we will publish it to everyone as release.

**Comment by nxPublic** [comment]
Update has been released since several hours now.
