### ISSUE TITLE
[Feature Request] Anti-Cheat?

### ISSUE THREAD

**Issue by b3ck** [valheimPlus/ValheimPlus#63]
I know this isn't what the MOD is for, but thought I would ask anyways.. so here is the jist of it;

I decided to open a server up to the community without a password, just to see what people would do.. it's amazing how many people join just to cheat.. in a matter of minutes the server had all the bosses spawned and killed, several Mythic Rune Stones were spawned around the spawn point so new players couldn't leave the spawn area and two Bonemass Bosses were spawned inside of the spawn area that are un-killable, and they kill anyone that joins the server.

So is there anyway for Valheim Plus to just stop all spawning of objects and/or events unless admin?

Kind Regards,
-b3ck

**Comment by nxPublic** [comment]
Unrealistic in any long term timeframe we have available to us.

**Comment by b3ck** [comment]
Oh sorry I didn't know you had a "timeframe" set for this project.

Thanks for looking into it anyways.


Take Care,
-b3ck

**Comment by nxPublic** [comment]
Well timeframe in terms of foreseeable future of us being able to implement a entire anti cheat system that would be good enough to combat anything in a game where everything is client side.

**Comment by b3ck** [comment]
I guess basically I was just looking for a way for the server to automatically delete spawned objects from players that weren't on the admin list.
