### ISSUE TITLE
loading log error

### ISSUE THREAD

**Issue by releep** [valheimPlus/ValheimPlus#635]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Attack and name GetStaminaUsage and parameters
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void ValheimPlus.GameClasses.Attack_GetStaminaUsage_Patch::Postfix(Attack& __instance, Single& __result)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <116dd996dda44480a48a0fc9ee2308ed>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <116dd996dda44480a48a0fc9ee2308ed>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <116dd996dda44480a48a0fc9ee2308ed>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <116dd996dda44480a48a0fc9ee2308ed>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <116dd996dda44480a48a0fc9ee2308ed>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <116dd996dda44480a48a0fc9ee2308ed>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <116dd996dda44480a48a0fc9ee2308ed>:0)
HarmonyLib.Harmony.PatchAll () (at <116dd996dda44480a48a0fc9ee2308ed>:0)
ValheimPlus.ValheimPlusPlugin.Awake () (at <c87de6f72d524299b65a4e9dae6eb9c5>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

not sure how it will affect the game yet.

**Comment by stolenvw** [comment]
update V+

**Comment by nxPublic** [comment]
Install the newest version of valheim plus.
