### ISSUE TITLE
[BUG] Performance issues?

### ISSUE THREAD

**Issue by bennysp** [valheimPlus/ValheimPlus#638]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
Linux (Ubuntu 20.04)
- **Valheim Game Version:** [e.g. 0.4.11, etc]
0.202.19
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]
0.9.9

**Describe the bug**

I have been noticing issues when playing on a local server/lan with bad performance when my V+ settings are turned on. At first, i thought it was my computer, so I turned down all graphics to the lowest. Still laggy. Logged into local/non-V+ game and it was fine... in fact, great, even with all settings at highest.

I then bought a remote hosting game server and installed everything, including V+, but I did not copy over my V+ config yet. Loaded that up and with mostly everything set to false, my world performed great. I copied my V+ config over to the new host and restarted. Same laggy performance after doing that.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Load up Valheim w/ Plus on original "shipped" config with hosting of your choice (in the example above, it didn't seem to matter how it was hosted)
2. Make sure to pick a world that has some "busy spots" (ie fires, chests, craft, bees and etc) - **This is not necessary**, however, it is easy to see in those situations
3. Run around and see how the game performs and maybe use F2 to see FPS
4. Logout of the server and now load the config I have attached to the server
5. Log back in and now do the same test
6. You should see a significant performance hit

**Expected behavior**

None to little performance hit

**Troubleshooting**

- Different servers
- Increased VM to 8 vCPU and 16GB RAM
- Copied world and updated config for local setup on desktop and I get about 15 FPS, highest seen

**Screenshots**

_Default Config:_
![ValheimPerf_NoEnable](https://user-images.githubusercontent.com/4121872/135374299-237e38fe-c12f-445b-a110-d07504a64c45.jpg)

_Modified Config:_
![ValheimPerf_Enabled](https://user-images.githubusercontent.com/4121872/135374306-e345dc50-a213-4411-9b3d-75635afc9821.jpg)
**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

https://pastebin.com/DrhgwVZj

**Additional context**

Shell commands for docker startup: https://pastebin.com/LtCAUZN3

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

None

**Comment by bennysp** [comment]
I also just downloaded the world to my local PC and ran with the enabled and original file. Same behavior. With features enabled, I am around 9 FPS. With original config, it is at about 25 FPS (not great, but I will take it over 9 FPS).

**Comment by nxPublic** [comment]
If Valheim vanilla runs at 25 fps for you, there is nothing in my life or my power that I can do to help you with that.

V+ does nothing that is really CPU or GPU extensive. 

We have performance in mind and offer several CFG settings for look up intervals of features to reduce their processing load. 

There is nothing else we can do.

**Comment by bennysp** [comment]
Sorry, if it was unclear. Vanilla does NOT run at 25fps for me. What I meant is that in the heavily populated area with V+ installed it is 25fps and then turning on the flags, it is down to that 9 fps.

In vanilla, in normal running around and house, it is at 60 for lowest settings, 50 for medium and 40 for highest.

Understood that I don't have the highest specs, but I was using the "busy area scenario" to show the effect of enabled vs disabled.

I will look into some of the lookup intervals.

Thanks @nxPublic

**Comment by bennysp** [comment]
And actually... We may have found the culprit. A little embarrassing to say, but we have a boar breeding operation that filled up to who knows how many. Once we killed most of the boars in the pit, I am back to 50-60 fps. 

I have no idea why enabling the V+ features were affected by that, but I probably need to do some adjustments there too.
