### ISSUE TITLE
[Question] Incompatible changes to world/character databases?

### ISSUE THREAD

**Issue by Chris-D-Turk** [valheimPlus/ValheimPlus#640]
Does this mod make any incompatible changes to the world/character DBs (*.db, *.fwl, *.fch )? 
Will I experience any problems after switching back to vanilla Valheim?
The reason I'm asking: When there's a Valheim client/server update (with breaking changes) and you didn't update the mod yet, I would like to be able to play without the mod.

**Comment by nxPublic** [comment]
There is no permanent change to any game files, you can uninstall and install the mod at any point.
