### ISSUE TITLE
[FEATURE REQUEST] Change all semicolons in the config to hashtags in order to support r2modman/Thunderstore config editor

### ISSUE THREAD

**Issue by GregariousJB** [valheimPlus/ValheimPlus#642]
There's technically already an issue regarding this in their issue tracker: https://github.com/ebkr/r2modmanPlus/issues/626 , so I guess it's a matter of who goes first - either Thunderstore supports semicolons or you swap all semicolons to hashtags.

The way it works now, config files with hashtags are displayed nice and cleanly in the r2modman UI, like so:

![hashtags](https://i.imgur.com/8xpCCYM.png)

However, with V+ using semicolons, none of the description text shows up in the mod manager...

![semi](https://i.imgur.com/fywdaL0.png)

...meaning users need to browse to the config file itself if they want to get more information about how a certain setting works, or to click on the documentation links you've provided. And since I'm pretty sure hashtags won't negatively affect anything else, using them instead of semicolons seems optimum. 

The only thing I'm uncertain of is whether or not the documentation links you have in the config will be carried over to r2modman as well. It's possible they'll just be parsed as plain text. If this is the case, a possible solution is to have the descriptions in hashtags so it shows on r2modman, but put the links behind semicolons so they don't show up in r2modman but are still available in the config file should anyone want them.

Thank you.

**Comment by nxPublic** [comment]
We are already in contact with the developers of Thunderstore and its mod manager, we've talked about it already.

They are working on it.
