### ISSUE TITLE
[FEATURE REQUEST] craft from carts

### ISSUE THREAD

**Issue by bagelbyheart** [valheimPlus/ValheimPlus#644]
It would be nice if craft from containers included carts (I haven't tested boats yet, but that would be nice too if they don't already work).

**Additional context**
There's a [mod on nexus](https://www.nexusmods.com/valheim/mods/40?tab=files) that does it already, but for max compatibility with multiplayer it would be nice to have in mainline.

**Comment by Frikster** [comment]
This looks like it would be easy to do. Simply change [this if statement](https://github.com/valheimPlus/ValheimPlus/blob/d9edb3b7343db1958c2436fc33b5f30c3c17d08e/ValheimPlus/Utility/InventoryAssistant.cs#L34) and remove the requirement that it not be a wagon or ship to be added to the validContainer list?. This will have unintended side-effects or is that all?

**Comment by nxPublic** [comment]
I added 2 new options to the CraftFromChest section.

allowCraftingFromCarts, allowCraftingFromShips
