### ISSUE TITLE
Linux dedicated server cannot be shutdown with the mod installed

### ISSUE THREAD

**Issue by yobson1** [valheimPlus/ValheimPlus#65]
Attempting to use CTRL-C or the kill command to issue a SIGINT no longer shuts down the server after installing the mod and running it from the new shell script

**Comment by xanathos79** [comment]
Got the same issue here as well

**Comment by sirskunkalot** [comment]
BepInEx issue, unrelated to V+

**Comment by sirskunkalot** [comment]
PS: For the time being you can always kill -9 (SIGKILL) the process if you are stuck with it. But no guarantees given, that world data is not corrupted by that.

**Comment by xanathos79** [comment]
I'll create a ticket for BepInEx as well as doorstop and we'll see who takes the blame.

**Comment by nxPublic** [comment]
We are in contact with the BepInEx people now and will try to help resolve this as soon as we can.

**Comment by xanathos79** [comment]
Latest version fixed it, thanks Nx

**Comment by Gaboros** [comment]
It's not working again on ubuntu server with latest version 9.9.11
