### ISSUE TITLE
[FEATURE REQUEST] Disable map pin editor without disabling all of the map section

### ISSUE THREAD

**Issue by HabituallyIronic** [valheimPlus/ValheimPlus#651]
I'd like to be able to use the OG pin editor while still using other parts of the map section. The OG editor allows me to toggle pin visibility, and is faster to use. However, I rely heavily on the cart/boat icon. I'd like to be able to enable one without necessarily enabling the other.

**Comment by nxPublic** [comment]
We will be removing the custom pin editor and find a more suitable solution that is quicker and won't interrupt gameplay as much.

I will also see if I can put this into its own Category.

**Comment by nxPublic** [comment]
This should be fixed with 0.9.9.7
