### ISSUE TITLE
[BUG] Chests can't be found on a Raft from ValheimRAFT Mod

### ISSUE THREAD

**Issue by ewoudje** [valheimPlus/ValheimPlus#662]
- **OS:** Windows Client
- **Valheim Game Version:** 0.206.5
- **V+ Mod Version:** 0.9.9.5

**Describe the bug**
If you use the mod "ValheimRAFT" the chest detection for auto-fill and crafting doesn't work.

And euh I understand you wouldn't want to care about a bug from a other mod but just check the Troubleshooting part.

**To Reproduce**
Place a Furnace or Kiln on the Raft

**Expected behavior**
Kiln/Furnace uses chests

**Troubleshooting**

I have tested it and debugged it and it seems that it gets fixed by changing the line 16 in
InventoryAssistant.cs by changing localPostion to position.

I think this is caused by how the other mods interacts with localposition and the boat, but is there a reason why there was localPosition in the first place? (this is why I didn't make a pull request). Or can this just be changed?

**Additional context**

ValheimRAFT mod 1.3.0

**Comment by nxPublic** [comment]
We do care about compatibility issues!

The InventoryAssistant class was written months ago, I don't think that there was a particular reason why it was localPosition.

I changed line 16 to reflect the changes you suggested that are working for you.
