### ISSUE TITLE
Coal in a chest near the kiln makes it not autofill wood[BUG]

### ISSUE THREAD

**Issue by Amichalec** [valheimPlus/ValheimPlus#664]
- **OS:**Windows client, not sure what the server is
- **Valheim Game Version:** Latest
- **V+ Mod Version:** 0.9.9.5

**Describe the bug**

The autofuel/autodeposit in the kiln to make wood into coal makes it so wood isn't reloaded once coal goes into a nearby chest.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Turn autofuel/autodeposit on, deposit wood in a chest, let some coal appear, deposit more wood and see it not taken in by the kiln

**Expected behavior**

I expect the wood to be taken in no matter if coal is in the chest

**Troubleshooting**

removed chests, replaced them, removed kiln replaced it.

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
 N/A

**Comment by nxPublic** [comment]
I cannot reproduce this issue. It might take a few seconds but my kiln always pulled the wood from any chest no matter what contents where inside it.

Just build 2 chests, 1 for input and 1 for output.

**Comment by Amichalec** [comment]
https://drive.google.com/file/d/1Ima-YQAyLYxhaIQ4AtNVkaiE_ndpy86c/view?usp=sharing

https://drive.google.com/file/d/1WzCzY09sIXA2q-qmX0XMosFd9JShnB0l/view?usp=sharing

Tried both one chest and two to no success and attached videos this time for further help.  If there's nothing that can be done that's fine, it's only a minor annoyance.
