### ISSUE TITLE
[BUG] Inventory is not updating properly: Including Storages, Crafting Stations, Boats, Etc

### ISSUE THREAD

**Issue by Scavar** [valheimPlus/ValheimPlus#665]
- **OS:** [Windows Client]
- **Valheim Game Version:** [0.206.5]
- **V+ Mod Version:** [0.9.9.5]

**Describe the bug**

When you hit Tab to look at your inventory, open a chest, or another form of storage, or crafting station: the inventory is not updating. The crafting section does not update or incorrectly shows what items are needed to craft or that items are missing to craft. If you click on an item you see it MAY update everything. 

**To Reproduce**

I am unable to purposely reproduce. It appears to randomly occur. Played a solid hour never came up. Came up after 5 minutes, restarted the world, came up after 5 minutes. Restarted the world and it never came up. It's hard to say what actually causes the issue.

**Expected behavior**

When you open your inventory, storage, or crafting station the inventory should be displaying properly and updating.

**Troubleshooting**

The issue does not appear to occur on 0.9.9.
Removed all other mods and only have Valheim Plus and requirements installed, issue seems to still occur.
Epic Loot and Better Trader were also installed when the issue first appeared but clean installation with just the game and Plus 9.9.5 and issue still appears to occur.

**Screenshots**

I will attempt to collect screenshots as it occurs though I'm not sure they will help. Completely slipped my mind to take screens.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/GWLPrucv

**Additional context**
![weirdinventoryerror1](https://user-images.githubusercontent.com/24951521/151105531-f83fd11c-b3d2-4c18-aed1-7438aedca9a4.PNG)
![weirdinventoryerror2](https://user-images.githubusercontent.com/24951521/151105533-b6e8a6a9-6e45-4279-abe6-18ccb2abe14c.PNG)
![weirdinventoryerror3](https://user-images.githubusercontent.com/24951521/151105538-28bf8435-3fd2-4661-88fa-4416163be70b.PNG)

Epic Loot
Better Trader
Skyheim
Cackleheim Nomadic 
Jotunn The Valheim Library
BepInEx 5.4.1700
Config Manager
HookGenPatcher
Extended Item Data Framework

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by nxPublic** [comment]
Did you move any of your chests with AEM or ABM?

Sometimes due to the way we detect chests in your proximity they might not be accessible if they're colliding with terrain or other objects.

**Comment by Scavar** [comment]
> 

I do not believe so. I can't say for sure but AEM and ABM haven't been used too much. I'll attempt some further testing when I get the chance in a new map seed.

I did some further testing and I believe the fact that it happened to me with just Plus might have been a fluke, I think my uninstall of EpicLoot may have failed. I think what's happening might be linked to the increased size that I have inventories set to and EpicLoot items. I can't 100% verify it but the glitch with inventory does seem to only occur when EpicLoot is installed. I haven't had a second instance of it occurring with JUST Plus.
EpicLoot and its Requirement Extended Item Data Framework were both updated, but the issue occurred on both the 0.8.8 version and the prior 0.8.7 version. The only factor difference appears to be Plus 0.9.9.5

**Comment by nxPublic** [comment]
> I haven't had a second instance of it occurring with JUST Plus.

Please report your issue to the respective mod developers of Epic Loot and/or Extended Item Data Framework to take a look at.

I wouldn't know what I am supposed to do if the error is not caused by our code.
If there is something we can change to help them fix this issue, I will of course do so.
