### ISSUE TITLE
[BUG] guardianBuffCooldown no longer works

### ISSUE THREAD

**Issue by ezonius** [valheimPlus/ValheimPlus#666]
- **OS:** Windows Client
- **Valheim Game Version:** 0.206.5
- **V+ Mod Version:** 9.9.6

**Describe the bug**

Changing guardianBuffCooldown no longer does anything. Seems to have happened when with the new release of 9.9.6, worked fine in 9.9.5

**To Reproduce**

Steps for the devs to reproduce the behavior:
Change the guardianBuffCooldown settings to anything other than default, and notice that cooldown has not changed.

**Expected behavior**

Cooldown changed when using guardian buff

**Troubleshooting**

What steps have you taken to try to fix?
Using default config.

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**
https://pastebin.com/C7RAEhfh

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
ExtendedItemDataFramework
SkToolbox
MassFarming
ValheimPerformanceOptimizations
ValheimFPSPlus
QoLPins
Glutton
PlanBuild
Jotunn
HookGenPatcher
UseEquipmentInWater
Build_Camera
SimpleSort
BepInEx_ConfigurationManager
EquipmentAndQuickSlots
VeinMine
CustomSlotItemLib
QuickStack
MultiCraft
ValheimPlus
BepInExPack_Valheim

**Comment by ezonius** [comment]
Additionally it seems that guardianBuffDuration also does not work.

**Comment by nxPublic** [comment]
You are correct, the changes I made for 0.9.9.7 should fix the issue.
