### ISSUE TITLE
[BUG] Clock not working

### ISSUE THREAD

**Issue by LegendNoobz** [valheimPlus/ValheimPlus#676]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**
Iam not dev or IT guy, sorry for describe the bug so bad .First download valheim+ for my server, i just turn on Clock feature, it working perfect. Then i try to editing another feature, when i start the game, so many bug, like clock not working, etc.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Download my config.
2. Apply on your server.

This link for pastebin, https://pastebin.com/56LqwPeW

**Comment by nxPublic** [comment]
I don't know what I am supposed to get from this report.

I am aware that the Clock functionality is not up to my own personal expectations and is already noted on my list to be re-written.
