### ISSUE TITLE
[BUG] Disabling structural integrity not working

### ISSUE THREAD

**Issue by Zaflis** [valheimPlus/ValheimPlus#681]
- **OS:** Windows Client
- **Valheim Game Version:** 0.207.20 (always latest Steam version)
- **V+ Mod Version:** 9.9.8

**Describe the bug**

I changed valheim_plus.cfg these lines:
```
[StructuralIntegrity]
enabled = true
; Disables the entire structural integrity system and allows for placement in free air, does not prevent building damage.
disableStructuralIntegrity = true
```

**To Reproduce**
Ingame i place wooden walls, then wooden floor on top of it, remove wall and the floor above collapses.

**Expected behavior**

Expected floor to stay in air.

**Troubleshooting**

What steps have you taken to try to fix?
- Have double-checked that config file is correctly edited.

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.
- BetterUI
- Advize_PlantEverything
- BepinEx ConfigurationManager
- InstantMonsterDrops

**Comment by Zaflis** [comment]
It seems this is a special case when these 2 are the last remaining pieces of a connected structure. If i have 2 floor pieces and remove wall, they do stay in air. But if i remove 1 of the floors then the other also drops.

**Comment by nxPublic** [comment]
There are certainly limits to the changes we've undertook to the game code to take care of structural integrity.

In 0.9.9.11 it should work better than before.
