### ISSUE TITLE
Can't deposit into furnace or smelter

### ISSUE THREAD

**Issue by sar52245** [valheimPlus/ValheimPlus#682]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
- **Valheim Game Version:** [e.g. 0.4.11, etc]
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**

Simply can't put items into smelter or coalmaker.n

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Build a smelter
2. Have smeltable items in inventory 
3. Try to put the items in the smelter

**Expected behavior**

Cannot interact with the insert ores side of the furnace. (I also can't seem to switch weapons while looking at the interact able part. 

**Troubleshooting**

Tried rebinding interact button. Tried restarting game. This happened right after updating this mod, that is why I suspect it is a bug here, but it may not be. 

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by Automatiax** [comment]
This has also occurred to me, on a hosted server through CreeperHost. With only Valheim+ installed.

**Comment by nxPublic** [comment]
I cannot reproduce this issue in 0.9.9.11, please create a new report if its still occurring for you.
