### ISSUE TITLE
[BUG] Carts and Boats have no way of being dismantled

### ISSUE THREAD

**Issue by prototype464** [valheimPlus/ValheimPlus#684]
- **OS:** Windows 10, 64 bit
- **Valheim Game Version:** Latest
- **V+ Mod Version:** 0.9.9.8

**Describe the bug**
After turning on `disableDamageToPlayerBoats` in the config, there isn't a way for the _player_ to damage boats or carts. Valheim does not provide a way to deconstruct these with a hammer, so essentially these are placed permanently.

You can't hit it with a weapon purposely to dismantle it as usual, thus making quick relocation / inventory transport impossible.

**To Reproduce**
1. Set `disableDamageToPlayerBoats` and `disableDamageToPlayerStructures` to `true` in `valheim_plus.cfg`
2. Place a cart, raft, karve, or longship
3. Try to damage it

**Expected behavior**
The player should be able to either dismantle these with a hammer or be able to damage them. The alternate problem here is not being able to disable it specifically for enemies, although the real issue (again) is having no alternative way of destroying them.

**Pastebin with Valheim Plus config:**
https://pastebin.com/m4uuRzpv

**Other mods installed:**
*BepInEx*
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/
*Valheim Performance Optimizations*
https://www.nexusmods.com/valheim/mods/1360
*Valheim FPS Plus*
https://www.nexusmods.com/valheim/mods/1205
*Custom Raids*
https://www.nexusmods.com/valheim/mods/278
*No Bow Glow*
https://www.nexusmods.com/valheim/mods/1092
*Building Health Display*
https://www.nexusmods.com/valheim/mods/793
*MultiCraft*
https://www.nexusmods.com/valheim/mods/263

**Comment by increddibelly** [comment]
I'd say this works as intended 🤔 
sounds like a feature request to be able to dismantle boats with the hammer.

**Comment by increddibelly** [comment]
looking into this and #688 I noticed the [Deconstruct ](https://github.com/valheimPlus/ValheimPlus/blame/799a52a225487cc52e01a3cd77b37aa0e50be048/ValheimPlus/Deconstruct.cs#L12) class was commented out in 9.5 - that's probably intentional. Since it mentions and filters non destructable objects, resurrecting this class might enable a way of tearing down vehicles?

**Comment by nxPublic** [comment]
#715

**Comment by prototype464** [comment]
This issue is not fixed, we need to either be able to dismantle boats and carts with hammers or add a 3rd option to toggle whether players can deal damage to them instead of just all entities.

I want to be able to move them across my world via my inventory, but I also don't want random enemies destroying them while I'm not looking.

**Comment by prototype464** [comment]
Bump
