### ISSUE TITLE
[BUG] Carts are invincible...

### ISSUE THREAD

**Issue by prototype464** [valheimPlus/ValheimPlus#688]
- **OS:** Windows 10, 64 bit
- **Valheim Game Version:** Latest
- **V+ Mod Version:** 0.9.9.8

**Describe the bug**
Zero way of destroying placed carts.

**To Reproduce**
1. Set `disableDamageToPlayerStructures` to `true` in `valheim_plus.cfg`
2. Place a cart
3. Try to damage it

**Expected behavior**
Carts should have a separate configuration entry from structures... Why isn't this the case already?

**Troubleshooting**
When I realized carts weren't under the `disableDamageToPlayerBoats` option and were actually under `disableDamageToPlayerStructures`, this upset me because I've been going nuts trying to find out what's causing my carts to be invincible, preventing me from dismantling them and taking them through portals.

The only way to fix this would be to set `disableDamageToPlayerStructures` to `false`, which I shouldn't have to do, because I don't want enemies damaging my bases.

**Pastebin with Valheim Plus config:**
https://pastebin.com/m4uuRzpv

**Other mods installed:**
*BepInEx*
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/
*Valheim Performance Optimizations*
https://www.nexusmods.com/valheim/mods/1360
*Valheim FPS Plus*
https://www.nexusmods.com/valheim/mods/1205
*Custom Raids*
https://www.nexusmods.com/valheim/mods/278
*No Bow Glow*
https://www.nexusmods.com/valheim/mods/1092
*Building Health Display*
https://www.nexusmods.com/valheim/mods/793
*MultiCraft*
https://www.nexusmods.com/valheim/mods/263

**Comment by increddibelly** [comment]
sounds like a feature request to dismantle the cart with the hammer? there's a similar issue around as well #684

**Comment by nxPublic** [comment]
#715

**Comment by prototype464** [comment]
This issue is not fixed, we need to either be able to dismantle boats and carts with hammers or add a 3rd option to toggle whether players can deal damage to them instead of just all entities.

I want to be able to move them across my world via my inventory, but I also don't want random enemies destroying them while I'm not looking.

**Comment by prototype464** [comment]
Bump
