### ISSUE TITLE
Menu issues

### ISSUE THREAD

**Issue by Rulenine** [valheimPlus/ValheimPlus#692]
I haven't played for a while, but recently came back and have a menu error. It appears to be related to Valheim Plus. I tried redownloading Valheim Plus but same issue. Does anyone have a fix? 

When I go to the start game menu, which now displays as $Menu_Start Game (all menu items look like this), I can't click any further (so game is unplayable). Server also won't start.

Appears to be related to HarmonyX. Any help would be greatly appreciated. Sample of the very long error output below that I got from the logs after trying to launch game.

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.UpdateCursor () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Update>(FejdStartup)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZInput.IsGamepadActive () (at <e2ad8b24c5224f5a8365347f64597ff3>:0)
UIGroupHandler.Update () (at <5ff8e8381e5049d4926d72f9dd2218ac>:0)

[Info   : Unity Log] 03/25/2022 19:32:29: Steam manager on destroy

[Warning:  HarmonyX] UnpatchAll has been called - This will remove ALL HARMONY PATCHES.
[Warning:  HarmonyX] UnpatchAll has been called - This will remove ALL HARMONY PATCHES.`

**Comment by snips86x** [comment]
The error you're seeing isn't a v+ issue but one relating to a mod you have installed causing the issue. Mods like sdk, jvl, monster/creature comfort/loot or another mod. Suspect whatever mod it is, hasn't been updated recently or you haven't installed the most recent. Beat to swing by the v+ discord if you still have issues but suggest removing all mods, updating v+ then downloading the mods you want to use, ensuring they're updated for the recent patch.

**Comment by SSimp258** [comment]
Highly recommend joining the discord getting help in real time.
