### ISSUE TITLE
[BUG] 0.9.9.8 missing from latest releases

### ISSUE THREAD

**Issue by SlightlyOffSync** [valheimPlus/ValheimPlus#701]
- **OS:** Linux Server
**Describe the bug**

[latest release](https://github.com/valheimPlus/ValheimPlus/releases/latest) is pointing to 0.9.9.7 instead of 0.9.9.8. This is breaking [valheim docker](https://github.com/lloesche/valheim-server-docker/) and possible other scripts that rely on the latest release endpoint

**To Reproduce**

`curl -sfSL https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest`

**Expected behavior**

Expect 0.9.9.8

**Comment by TrueOsiris** [comment]
It seems the release 0.9.9.8 has disappeared. 0.9.9.8 only remains as a tag.

**Comment by pieterhouwen** [comment]
You can find it at: https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.9.8 

Looks like it was unavailable for a while but looks like it's restored now.

**Comment by ZyanKLee** [comment]
Can confirm. The release 0.9.9.8 is back.
Tag was available all the time, but some server hoster seem to use automatics to install always the latest release.

**Comment by SlightlyOffSync** [comment]
looks like it works
