### ISSUE TITLE
[BUG] Valheim server crashes on start 

### ISSUE THREAD

**Issue by adrido** [valheimPlus/ValheimPlus#703]
- **OS:**  Linux Server
- **Valheim Game Version:** 0.209.8
- **V+ Mod Version:** 0.9.9.8

**Describe the bug**

Valheimserver crashes on start

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Start the server

**Expected behavior**

**Troubleshooting**

verified game files, reinstalled V+ 
nothing helped.

**Additional context**
Log in reversed order: [valheim.log](https://github.com/valheimPlus/ValheimPlus/files/8941131/valheim.log)

**Comment by Genues** [comment]
Confirmed for start game on linux.

./start_game_bepinex.sh ./valheim.x86_64
Found UnityPlayer, hooking into it instead
Segmentation fault (core dumped)

**Comment by derekjhunt** [comment]
Confirmed - Debian 11.3 amd64.  There are issues with Mono loading libraries.  

```
Begin MonoManager ReloadAssembly
Load DLL: /home/valheim/serverfiles/valheim_server_Data/Managed/UnityEngine.dll
Base: UnityEngine.dll
Redirecting to /home/valheim/serverfiles/unstripped_corlib/UnityEngine.dll
Fallback handler could not load library /home/valheim/serverfiles/valheim_server_Data/Mono/P��,�U/mono/aot-cache/amd64/UnityEngine.dll.so
```

**Comment by martijns** [comment]
A new version of Valheim was released, with an updated Unity engine version. Seems likely ValheimPlus requires an update. Title should probably be updated to reflect this.
https://store.steampowered.com/news/app/892970/view/6128850732739087108

A new version of BepInEx fixes startup issues, but I'm not sure if ValheimPlus requires an update as well.
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

**Comment by tomcoolpxl** [comment]
Confirmed bug on debian-based docker https://github.com/lloesche/valheim-server-docker 

```
Jun 20 17:38:16 /supervisord: valheim-server Base: UnityEngine.XRModule.dll
Jun 20 17:38:16 /supervisord: valheim-server Redirecting to /opt/valheim/plus/unstripped_corlib/UnityEngine.XRModule.dll
Jun 20 17:38:16 /supervisord: valheim-server Unable to find type [UnityEngine.CoreModule.dll]Unity.IO.LowLevel.Unsafe.AsyncReadManagerMetricsFilters
```

Segmentation fault (core dumped)

**Comment by WowHerbage** [comment]
Output from Valheim after using the Val+ launch script on Linux:

```
Unable to find method ClearSubsystems in [UnityEngine.SubsystemsModule.dll]UnityEngine.SubsystemManager
Unable to find method InitializeIntegratedSubsystem in [UnityEngine.SubsystemsModule.dll]UnityEngine.SubsystemManager
Unable to find method ReloadSubsystemsCompleted in [UnityEngine.SubsystemsModule.dll]UnityEngine.SubsystemManager
Unable to find method ReloadSubsystemsStarted in [UnityEngine.SubsystemsModule.dll]UnityEngine.SubsystemManager
Unable to find method ClearManagedDescriptors in [UnityEngine.SubsystemsModule.dll]UnityEngine.SubsystemsImplementation.SubsystemDescriptorStore
Unable to find method InitializeManagedDescriptor in [UnityEngine.SubsystemsModule.dll]UnityEngine.SubsystemsImplementation.SubsystemDescriptorStore
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Segmentation fault (core dumped)
```
I did try and updating BepInEx to latest and the server will still not start with Val+ 0.9.9.8

**Comment by astrooom** [comment]
Same here, also getting:
`Segmentation fault (core dumped)` and a crash.

**Comment by mrNateDog** [comment]
Having the same issue. Adding my log for additional info if needed
[Player.log](https://github.com/valheimPlus/ValheimPlus/files/8943181/Player.log)
.

**Comment by Zeraphicus** [comment]
> A new version of Valheim was released, with an updated Unity engine version. Seems likely ValheimPlus requires an update. Title should probably be updated to reflect this. https://store.steampowered.com/news/app/892970/view/6128850732739087108
> 
> A new version of BepInEx fixes startup issues, but I'm not sure if ValheimPlus requires an update as well. https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

FYI I downloaded a fresh bepinex and copied to my server and it is working now.  The same thing was happening to client side until you got a new bepinex.  This is causing issues with a lot of servers as Vplus seems to include bepinex.  Just need to update your vplus package and I think it should work good to ship out.

**Comment by theonlyfox** [comment]
Updating the Valheim Server and Client with the new BepinEx seems to fix the start up issues, but now there is a version mismatch between clients and servers.  

`06/20/2022 16:43:54: Got connection SteamID XXXXXXXXXXXXXXXXXXXXXX
06/20/2022 16:43:54: Got handshake from client XXXXXXXXXXXXXXXXXXXXXX
06/20/2022 16:43:58: VERSION check their:0.209.9@0.9.9.8  mine:0.209.9
06/20/2022 16:43:58: Peer XXXXXXXXXXXXXXXXXXXXXX has incompatible version, mine:0.209.9 remote 0.209.9@0.9.9.8
06/20/2022 16:43:59: RPC_Disconnect
06/20/2022 16:43:59: Disposing socket
06/20/2022 16:43:59: Closing socket XXXXXXXXXXXXXXXXXXXXXX`

**Comment by ersan** [comment]
> Updating the Valheim Server and Client with the new BepinEx seems to fix the start up issues, but now there is a version mismatch between clients and servers.
> 
> `06/20/2022 16:43:54: Got connection SteamID XXXXXXXXXXXXXXXXXXXXXX 06/20/2022 16:43:54: Got handshake from client XXXXXXXXXXXXXXXXXXXXXX 06/20/2022 16:43:58: VERSION check their:0.209.9@0.9.9.8 mine:0.209.9 06/20/2022 16:43:58: Peer XXXXXXXXXXXXXXXXXXXXXX has incompatible version, mine:0.209.9 remote 0.209.9@0.9.9.8 06/20/2022 16:43:59: RPC_Disconnect 06/20/2022 16:43:59: Disposing socket 06/20/2022 16:43:59: Closing socket XXXXXXXXXXXXXXXXXXXXXX`

This means Valheim Plus hasn't loaded on your server for some reason.  There should be other log lines that explain why earlier.

**Comment by theonlyfox** [comment]
> This means Valheim Plus hasn't loaded on your server for some reason. There should be other log lines that explain why earlier.

Yep, that was it.  Apparently the update screwed alot of world saves so it loaded with a new fresh seed that V+ wasn't active on.  Was able to restore a recent back up and get it going again.  There was a hot fix sometime later in the day that recovered most server world saves.  Only thing left is someone to commit the new BepinEx to the repository and everything should be back to normal.

**Comment by AdamLMark** [comment]
The fix for me was to move my world(s) from /config/worlds to /config/worlds_local (had to overwrite files)

**Comment by katanacrimson** [comment]
Likely resolved by the latest release: https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.9.8-BepInEx

**Comment by adrido** [comment]
Works for me. Thanks.
