### ISSUE TITLE
[BUG] - Main Menu Broken After Updating to Patch 0.211.7

### ISSUE THREAD

**Issue by Parounios** [valheimPlus/ValheimPlus#711]
- OS:  Windows Client
- Valheim Game Version: 0.211.7
- V+ Mod Version: Valheim Plus 0.9.9.8

**Description:**
The Main Menu is broken after updating to Patch 0.211.7 - CrossPlay

**Repro Steps:**
1. Update base game with latest patch 0.211.7
2. Install V+ client again
3. Start game

**Expected behavior**

The game starts normally with no errors

**Actual behavior**
The Main Menu UI is broken.
Please see attached screenshots and Error Log

**Troubleshooting**

Verified Steam Local files and then re-installed V+ mod, to no avail.

**Screenshots**

![Valheim Plus Error](https://user-images.githubusercontent.com/114899882/193509838-4169d4e2-0289-4e0d-9cfe-a47f61fb42bc.png)

[LogOutput.log](https://github.com/valheimPlus/ValheimPlus/files/9694959/LogOutput.log)

Kind regards

**Comment by healiha** [comment]
This will be fixed by https://github.com/valheimPlus/ValheimPlus/pull/710
We're waiting for @nxPublic to be back as he's the only one who can approve the PR and create the release on github.

In the meantime, you can use the pre-release .dll which is available in the #alpha-releases channel of our discord.

**Comment by Parounios** [comment]
Nice one, thank you!

**Comment by andrewdunndev** [comment]
@healiha do we know if @nxPublic will return? Is the project abandoned?

**Comment by mbagattini** [comment]
@andrewgdunn their message of 9/28 on Discord:

> I will be back home at the earliest on the 7-8th October, i won't be able to compile/edit/upload/test anything until i am back home on my workstation. I am very sorry for the delays but i got fixed appointments and meetings until then that i cannot miss or change to be back home earlier. Thanks for your understanding everybody, i will be on it as soon as i can.

**Comment by andrewdunndev** [comment]
@mbagattini thanks a ton for posting that, I should have sought out other discussion mediums. Awesome to see they will return!

**Comment by bytorphoto** [comment]
Maybe it could be a plan to set up a second user who can do this in your absence? Is that possible, for future updates/issues that come up?

**Comment by healiha** [comment]
Closing with 0.9.9.9 release.

**Comment by mendoza442** [comment]
has the mod been updated or where could i find the link for the prerelease

**Comment by liliancahuzac** [comment]
> has the mod been updated or where could i find the link for the prerelease

I closed the issue with 0.9.9.9 release. You can find it in the releases tab of the project.
