### ISSUE TITLE
[BUG] V+ not loading on start_server_bepinex.sh (Linux OS Dedicated Server)

### ISSUE THREAD

**Issue by Knightmare-Frame** [valheimPlus/ValheimPlus#716]
Raspberry Pi using Box86 + 64 on Raspian
Valheim Game Version: 0.211.11
V+: 0.9.9.9

**Describe the bug**

Followed all instuctions, made adjustment to lib path as per another thread, can run the start_server_bepinex.sh script which starts up but never loads any mods including Valheim +.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Install using the proper steps for Linux OS Servers.
2. Start the server.
3. Start Valheim (Modded) with matching version of V+.
4. Login to Server.
5. Get error that says mismatch versions and closes

**Expected behavior**

I expect the mod to load, however it refuses to do so even using the bepinex start script...

**Troubleshooting**

->Tried a reboot, relaying down the mod files, checking logging, found the following log lines which are concerning as it seems that maybe its just ignoring any mods?

11/11/2022 17:07:55: VERSION check their:0.211.11@0.9.9.9  mine:0.211.11

valheim isModded: False

Valheim version:0.211.11

->The @ symbol + V+ is not showing up in the version which is quite odd.

Just V+ which is the first mod I am setting up on the server.

**Comment by spy1134** [comment]
I suspect that Valheim Plus was not properly installed on the server side.
I just updated my Debian Valheim server to 0.9.9.11 and attempted to connect from a now outdated client on 0.9.9.10

This is the log output I get on version mismatch:
12/08/2022 15:45:58: VERSION check their:0.212.7@0.9.9.10  **mine:0.212.7@0.9.9.11**
12/08/2022 15:45:58: Peer REDACTED has incompatible version, **mine:0.212.7@0.9.9.11** remote 0.212.7@0.9.9.10

Note that the section "mine" lists both the Valheim version as well as the Valheim Plus version.
In your log it looks like only the Valheim version is listed.

**Comment by nxPublic** [comment]
The bug reporting section in this Github repository is not your personal troubleshooting forum.

Please use our [Discord ](https://discord.gg/AmH6Va97GT)for troubleshooting setup issues and else.
