### ISSUE TITLE
Is it possible to modify the view distance?

### ISSUE THREAD

**Issue by larssn** [valheimPlus/ValheimPlus#72]
I've been looking for a class that governs this behavior, but I'm new to modding, and having figured out how to best locate stuff yet.

Anyone know?

**Comment by GaelicGamer** [comment]
Pretty sure this is handled in the InstanceRenderer Update method with the m_lodMinDistance and m_lodMaxDistance.

**Comment by larssn** [comment]
> Pretty sure this is handled in the InstanceRenderer Update method with the m_lodMinDistance and m_lodMaxDistance. I'm not absolutely sure though as I haven't messed with it yet.

After messing around with this for a bit, I think this only applies to a specific instance. I think the key is the amount of instances loaded instead. So there has to be some code somewhere that governs how many instances is loaded into memory at once.

**Comment by nxPublic** [comment]
We have investigated this option and came to the conclusion that it can cause way to many general issues, bugs and and really really bad stuff in general. 

Sorry, we wont be doing this one.
