### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bragdonjm** [valheimPlus/ValheimPlus#724]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
Windows 11 client, Hosted server via g-portal (Linux backed)

- **Valheim Game Version:** [e.g. 0.4.11, etc]
Server: Valheim version:0.212.7
Windows Client: 0.212.7

- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]
0.9.9.9

**Describe the bug**
Valhiem+ fails to load and crashes. Server continues load up without issue and can still be playeds.  

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Update Server and Client (Windows) to latest Valhiem release. 
2. Attempt to login and play.
3. all valhiem+ features appear disabled ( was working last night)
4. Some checked things: Weight control gone, Inventory modifications (player and storage) gone. Stacks set to default levels. 

**Expected behavior**
Valhiem+ loads as normal and all features are available. 

**Troubleshooting**

What steps have you taken to try to fix?
Reload the settings and restart server.

**Additional context**

No other mods. 

[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type SEMan and name AddStatusEffect and parameters (StatusEffect, bool)
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void ValheimPlus.GameClasses.SEMan_AddStatusEffect_Patch::Postfix(SEMan& __instance, StatusEffect& statusEffect, bool resetTime)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
ValheimPlus.ValheimPlusPlugin.Awake () (at <5a95645ebf264670b7e210ece81a6e52>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by timjohnson408** [comment]
Mistlands patch dropped today, which has caused this issue.

**Comment by GuinnessDublin** [comment]
Linux client also dont work. Latest one. Valheim client dont even start with it.

**Comment by nxPublic** [comment]
Fixed with [#511f19718a1c882bcb3793fef54c8b5e68718874](https://github.com/valheimPlus/ValheimPlus/commit/511f19718a1c882bcb3793fef54c8b5e68718874)
