### ISSUE TITLE
[Feature Request] SSC - Server Side Character

### ISSUE THREAD

**Issue by nickkeane** [valheimPlus/ValheimPlus#75]
Character, Stats, Equipment, Inventory, and Progress associated with a server.
Swap normal character(s) for SSC character on join server with an SSC enabled server, matching on Character Name or something.
TShock for Terraria has an option for SSC for an example of how this could work.
Probably complex to do, if even possible at all with V+.

**Comment by nxPublic** [comment]
As soon as our networking wrapper is finished, this is one of the first things we will be adding.

**Comment by YannMCX** [comment]
It could be really nice to have that, because on my server, some people join with a high level character (full iron stuff, and other things) that ruin the gameplay...

**Comment by radmint** [comment]
https://trello.com/c/lQfHOB9m/26-ssc-server-side-character

**Comment by Raknarr** [comment]
I would love to see that. I am gonna donate 50$ for you guys if it is gonna show up:)

**Comment by kentgrav** [comment]
@Raknarr I concur. I will double your donation when this feature is implemented.  I have several guys using other servers to transport ore back and forth and they are so far ahead everyone else it ruins the gameplay.

**Comment by Raknarr** [comment]
Well problem is:
- you can duplicate your save with ores and load it X times ( simple drop ores in chest, remove save, copy that one with ores)
- you can grab ores from one server and login to second one
These two things completely destroy the game.

**Comment by nxPublic** [comment]
We are actively working on this.

**Comment by nxPublic** [comment]
This suggestion has been added to http://valheim.plus/todo under Server as "Server Specific Characters & Inventory".

**Comment by nickkeane** [comment]
Someone has made a mod for SSC support for Valheim if you need reference material

https://valheim.thunderstore.io/package/Smoothbrain/ServerCharacters/
https://github.com/blaxxun-boop/ServerCharacters
