### ISSUE TITLE
[Feature request] kills, deaths tracker/leaderboard

### ISSUE THREAD

**Issue by dkirby-ms** [valheimPlus/ValheimPlus#77]
Is it feasible to track kills, deaths, and other interesting leaderboard like stats? It would be fun to keep track of who has killed the most trolls or other enemies, who has died the most to deathsquitos, etc. 

Would this be feasible with this mod?

**Comment by nxPublic** [comment]
Yes we are having it on our list in conjunction with #64

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kills, deaths tracker/leaderboard](https://trello.com/c/UYWQKVWK/46-kills-deaths-tracker-leaderboard)

**Comment by nxPublic** [comment]
#64 is going to be the reference for this feature.
