### ISSUE TITLE
[Feature Request] Advanced Building/Editing Mode: Repeatable Placement

### ISSUE THREAD

**Issue by Samsterious** [valheimPlus/ValheimPlus#78]
Currently, placing an object exits the Advanced Building/Editing Mode, which means the player must manually realign the blueprint and re-enter Advanced Building/Editing Mode in order to place multiple objects in alignment with each other.

By remaining in Advanced Building/Editing Mode after placing an object, with the new blueprint in the same position as the last, this could make placing multiple objects in precise alignment with each other much more feasible.

**Comment by Lovis83854** [comment]
i would 2nd this one would be helpful if it remembered the last orientation

**Comment by radmint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Advanced Building/Editing Mode: Repeatable Placement](https://trello.com/c/rIMK9ipI/7-advanced-building-editing-mode-repeatable-placement)

**Comment by nxPublic** [comment]
Done with 0.9.3

**Comment by Samsterious** [comment]
This does not appear to have been implemented in versions 0.9.3 or 0.9.4.

The copy/paste rotation functionality (by default bound to Numpad 7 & 8) does not seem to function at all, and since placing an object still exits ABM, there remains no way to precisely align objects.

I've noticed that "rotation" has been used without mentioning "position" in the config documentation (such as when rotation speed adjustment became possible). Am I right to assume that the intended function of the save/load feature includes position despite being only labeled "rotation", as well?

**Comment by Lovis83854** [comment]
i think it was attempted because im noticing that the object is remembering the last postion but its not based on the object im looking at its will just place it over the same object i just placed unless i change what im building then switch back

**Comment by Samsterious** [comment]
In Win10 on v0.9.4 I am unable to see any of these behaviors. Pressing Num7 or Num8 provides no notification or change in behavior, and entering ABM after placing an object does not cause it to move to the position of the previous object.

Can you explain how you were able to achieve this behavior?

**Comment by Lovis83854** [comment]
> 
> 
> In Win10 on v0.9.4 I am unable to see any of these behaviors. Pressing Num7 or Num8 provides no notification or change in behavior, and entering ABM after placing an object does not cause it to move to the position of the previous object.
> 
> Can you explain how you were able to achieve this behavior?

im not sure when i go to build a object i hit f1 to make adjustments and after i place it, it seems the ghost of the object im build remains in the  previous position and not based on were im looking unless i select another object to build it will remain there. I havent tryed to hit f3 to reset it that way.

**Comment by Samsterious** [comment]
Interesting. In that case, this may be a configuration issue on my part.

ABM works fine (aside from #250), but there's no indication that any of its features have changed since 0.9.2, which leaves me stumped because there wasn't any new config flag for it. I noticed that `shareMapProgression` was missing from the 0.9.4 config, but not `preventPlayerFromTurningOffPublicPosition`, which was a little confusing so I added it back in; perhaps there is a flag I've missed that should be in there.

Here's a copy of the configuration file I've been using for V+0.9.4 on Win10x64, Valheim version 147.3:
[valheim_plus.cfg.txt](https://github.com/valheimPlus/ValheimPlus/files/6112074/valheim_plus.cfg.txt)

**Comment by Lovis83854** [comment]
well according to my server logs im running v+0.9.4 but its shows an update in my mod manager section
im hosting on GTXgaming so ill update it tonight and see if my issue is gone here is a copy of my config file if it helps

[valheim_plus.cfg.txt](https://github.com/valheimPlus/ValheimPlus/files/6112151/valheim_plus.cfg.txt)

**Comment by Samsterious** [comment]
Oh, I think I may have been using the `Numpad7`/`Numpad8` feature incorrectly, I believe I've just figured that out. However, I'm still not sure how to access the repeatable placement feature. Using your config on a new character and world did not seem to fix the issue for me.

The behavior I _expect_ is that I hit `F1`, place an object, use the arrows to adjust the blueprint's position, place another object, rinse and repeat until I'm finished.

Am I describing correctly how this feature was actually implemented?
