### ISSUE TITLE
[BUG] MissingFieldException: Field 'ValheimPlus.Configurations.BaseConfig`1<ValheimPlus.Configurations.Sections.MapConfiguration>.IsEnabled not found

### ISSUE THREAD

**Issue by drzewkoKamil** [valheimPlus/ValheimPlus#787]
- **OS:** Windows 10 Client
- **Valheim Game Version:** 0.212.7
- **V+ Mod Version:** 0.9.9.11

**Describe the bug**

Friend's instance of game encounters Unity error "MissingFieldException: Field 'ValheimPlus.Configurations.BaseConfig`1<ValheimPlus.Configurations.Sections.MapConfiguration>.IsEnabled' not found." when loading the modded game for the first time

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Follow manual install instructions
2. Launch the game with mod, without config for the first time
3. See error
4. Splash screen doesn't contain Valheim Plus logo

**Expected behavior**

No errors and ability to load config

**Troubleshooting**

Tried loading the game with exactly the same files which had the mod working on another machine. It seems no matter what game files I try it on, friend's machine keeps encountering this error. My PC runs Windows 11, bug occurs on Windows 10

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

https://pastebin.com/ZumzdyYk

**Comment by SSimp258** [comment]
So my question is on the CFG file in the maps section is there an issue like on the line "enabled = " and it's blank? I'd like to see the CFG file if possible since you have the log file attached above.

**Comment by drzewkoKamil** [comment]
The problem is the error happens before config is created. I tried however to run the game with a config attached, which resulted in the same error
[valheim_plus.txt](https://github.com/valheimPlus/ValheimPlus/files/10815848/valheim_plus.txt)

**Comment by SSimp258** [comment]
I can't reproduce the error. I even redownloaded V+ DLL file from GIT and can't reproduce it. Only thing i can suggest is to uninstall valheim, delete the folder and everything that's left over, and then reinstall from steam. Once valheim has been installed, reinstall V+ and bepinex from thunderstore. I also highly suggest getting on the discord so we can troubleshoot this faster.
