### ISSUE TITLE
[Feature Request] Add a enable/disable setting to remove Skill XP lost on death

### ISSUE THREAD

**Issue by NinjaKittens14** [valheimPlus/ValheimPlus#80]
I like being able to enable and disable this feature to create more playstyles to the game.

**Comment by Xiaminou** [comment]
I think it would be better to implement it so that you chose how much of your skills you lose on death. You can always set that to 0 if you want it disabled entirely.

**Comment by NinjaKittens14** [comment]
I agree! The ability to modify it to your liking is much better.

**Comment by vincentlau36** [comment]
Good news! I made a pull request (#159) for this exact configuration. Looking to get it reviewed by the main authors.

**Comment by greenskye** [comment]
This is now implemented

**Comment by kentgrav** [comment]
I would like the ability to disable skill loss entirely when killed by falling damage but keep it enabled or even increase skill loss amount when killed by any other means.
