### ISSUE TITLE
[BUG] V+ server crash on run

### ISSUE THREAD

**Issue by miloszolejnik** [valheimPlus/ValheimPlus#804]
- **OS:** Linux Server
- **Valheim Game Version:** 0.214.300
- **V+ Mod Version:**  0.9.9.11

**Describe the bug**

When starting server is crushing.
[Pterodactyl Daemon]: Exit code: 139

**To Reproduce**

Steps for the devs to reproduce the behavior:

Server starting command:

> export DOORSTOP_ENABLE=TRUE; export DOORSTOP_INVOKE_DLL_PATH=./BepInEx/core/BepInEx.Preloader.dll; export DOORSTOP_CORLIB_OVERRIDE_PATH=./unstripped_corlib; export LD_LIBRARY_PATH="./doorstop_libs:$LD_LIBRARY_PATH"; export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"; export templdpath=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH="./linux64:$LD_LIBRARY_PATH"; export SteamAppId=892970; export LD_LIBRARY_PATH=$templdpath; ./valheim_server.x86_64 -nographics -batchmode -name "Piwniczheim" -port 5000 -world "IDKitsMyFirstTimePap" -password "xxx" -public {{PUBLIC_SERVER}} -saveinterval 1800 -backups 4 -backupshort 7200 -backuplong 43200 $( [[ 0 -eq 1 ]] && echo " -crossplay ") > >(sed -uE "[hidden]") & trap "[hidden]" 15; wait $!

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

BepInEx.cfg: https://pastebin.com/dGdj5Yqa
Server log: https://pastebin.com/awNx7DbF

**SOLUTION:**

> 1st - Bepinex is now at version 5.4.2101 and your log shows 5.4.1900 or 1901 so it needs to be updated.
> 2nd - V+ needs to be updated to the community fix version 0.9.9.13.
> 3rd - https://github.com/valheimPlus/ValheimPlus/issues/1 and https://github.com/valheimPlus/ValheimPlus/issues/2 should get you running on the current version of Valheim (214.30x)

**Comment by SSimp258** [comment]
So couple items that I see:

1st - Bepinex is now at version 5.4.2101 and your log shows 5.4.1900 or 1901 so it needs to be updated.
2nd - V+ needs to be updated to the community fix version 0.9.9.13.
3rd - #1 and #2 should get you running on the current version of Valheim (214.30x)

I'm not a linux guy but i'm hoping this will get you fixed.

**Comment by miloszolejnik** [comment]
It seems i have an issue with finding a community fix.
Can you share the link with me?

**Comment by SSimp258** [comment]
> It seems i have an issue with finding a community fix. Can you share the link with me?

sure.

https://valheim.thunderstore.io/package/Grantapher/ValheimPlus_Grantapher_Temporary/

**Comment by Grantapher** [comment]
If you aren't using a mod manager, https://github.com/Grantapher/ValheimPlus/releases/latest

**Comment by miloszolejnik** [comment]
It is working now.
Thank you.
