### ISSUE TITLE
[Feature Request] Blueprints

### ISSUE THREAD

**Issue by nickkeane** [valheimPlus/ValheimPlus#82]
Would be nice to have a blueprinting system at some point ala Factorio for repetitive builds.

- [ ] Save/Load Blueprint(s) from a list (console cmd?)
- [ ] Save/Load Blueprint(s) from a file
- [ ] Blueprint Books/Categories
- [ ] Positional/Rotational Offsets
- [ ] Ghost Placement - Place see-through outlines of a blueprint's contents in the world
- [ ] Remove Blueprint from World/Undo/Redo
- [ ] Autobuild? Build all or part of a blueprint immediately if you have all the available materials (kind of immersion breaking)

**Comment by JTF195** [comment]
Another great example of this feature request would be The Forest.
The build blueprint/ghost system in that game is nearly perfect IMO

**Comment by Mixone-FinallyHere** [comment]
There are a few mods that add blueprints already such as Plan Build
We have not done any code for this and we do not think we will be implementing such a feature in the near future
