### ISSUE TITLE
[Feature Request] Armor Slots 

### ISSUE THREAD

**Issue by MoeHunt3r** [valheimPlus/ValheimPlus#87]
Would be nice to have some specific armor slots for only the armor, just like every RPG has because of the limited space in inventory.

**Comment by Mixone-FinallyHere** [comment]
Keep an eye on upcoming releases ;)

**Comment by gnouts** [comment]
Sorry @Mixone-FinallyHere, there has been 4 releases since your comment, but I couldn't find a config or a changelog talking about it. Can you point me to it please ?
