### ISSUE TITLE
[Feature Request] Ability to add custom skills

### ISSUE THREAD

**Issue by darkvergus** [valheimPlus/ValheimPlus#88]
Add the ability to be able to change the experience of custom skills that have been added, this will probably require some type of compatibility.

**Comment by nxPublic** [comment]
We have this implemented since a few weeks.

**Comment by mdcohen** [comment]
Dude one final warning. Shut the fucknup. If you have a commit just do it
silently. I swear to all that’s precious in our world just shut your mouth.
