### ISSUE TITLE
[Feature Request]  thunderstore.io/r2modman support.

### ISSUE THREAD

**Issue by Fundryi** [valheimPlus/ValheimPlus#89]
Would be great if thunderstore.io/r2modman could be supported or at least allow them to upload ValheimPlus on their site to make it easier for us to use it.

https://valheim.thunderstore.io/
https://thunderstore.io/package/ebkr/r2modman/

Regards

**Comment by nxPublic** [comment]
We are considering it at the moment. We are working on it and am in contact with them.
