### ISSUE TITLE
[Feature Request] Sleeping with multiple players

### ISSUE THREAD

**Issue by Xiaminou** [valheimPlus/ValheimPlus#90]
I would like to have something similar to Minecraft's Morpheus mod for server that have multiple players playing at all time.
Basically an option to chose the % of your players that need to be sleeping in order to skip the night.

**Comment by GaelicGamer** [comment]
Hmm, this shouldn't be too hard, let me take a quick look at this.

**Comment by GaelicGamer** [comment]
Yup got this working locally, just need to get some folk onto my server to test it with different numbers

**Comment by nxPublic** [comment]
No idea what happened to the PR but I'll add it to the to do list I am working on right now non the less.
