### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Bullstone** [valheimPlus/ValheimPlus#91]
Hello, what can I do about this server error?

Unhandled Exception:
System.MissingMethodException: void System.IO.File.WriteAllText(string,string)
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: void System.IO.File.WriteAllText(string,string)

SERVER IS OFFLINE, exit with code: 1

Server Hoster is: Host-Unlimited.de
Windows Server

I installed the mod exactly according to the instructions.

**Comment by nxPublic** [comment]
Please join the discord at http://discord.valheim.plus and use the appropriate channels to ask for help.

This repository is not a tech support center.
