### ISSUE TITLE
[Bug] Crash on Steam Server Browser Join

### ISSUE THREAD

**Issue by nickkeane** [valheimPlus/ValheimPlus#93]
Having an issue joining my server from Steam Server Browser. It crashes on join.

Joining from in-game browser works fine.

Hash: 0.145.6@0.8.5@6BF0C498747C15D9723361A86229713C
Config: https://drive.google.com/file/d/1Tqsx66wDhDA2N9sr2hMwipz4ellhpO5X/view?usp=sharing
Dump: https://drive.google.com/file/d/1LGzVAfOCx4LOOkoGo0FfMNkGEt1-7mfy/view?usp=sharing
Player Log: https://drive.google.com/file/d/1XlxI32ZmPt2T7-Dc7oECICi8ThYnKcTC/view?usp=sharing

Gut instinct is it could be something to do with the password process since on 0.8 I was able to get in from the browser (with the pass prompted twice - once in the Server Browser, once in-game), and it crashes in 0.8.5 around the time I normally get the 2nd prompt.

**Comment by nxPublic** [comment]
0.8.6 release later today should fix this issue
