### ISSUE TITLE
Fireplace does not work in ja-JP?

### ISSUE THREAD

**Issue by muro1214** [valheimPlus/ValheimPlus#97]
I'm playing Valheim with the language setting set to Japanese.
I set the CFG as follows, but the torch ran out of fuel after a certain amount of time.
The torch is still in need of refilling.

~~~
[Fireplace]

; If changed to enabled all fireplaces do not need to be refilled.
enabled=true

; If you enable this option only placed torches do not need to be refilled.
onlyTorches=true
~~~

**Comment by radmint** [comment]
Thanks @muro1214 we've located the issue and are working on a fix.

**Comment by muro1214** [comment]
Thanks!

**Comment by radmint** [comment]
Hi @muro1214 this fix has been completed and will be out with the next release. Sorry about the inconvenience and thank you for reporting!
